### ISSUE TITLE
develop a suite of test cases for tree import, etc.

### ISSUE THREAD

**Issue by chinchliff** [OpenTreeOfLife/opentree#1]
a very general idea for now. but we may want to have some pre-built test cases to help improve testing efficiency as we develop treemachine and intergrate components.

**Comment by jar398** [comment]
Would be nice if the TESTS.md file mentioned this test.sh file.

In general, I think it would be good if the TEST*.md files in every repo
gave an overview of *all* testing options related to that repo.
