### ISSUE TITLE
Study list is different (sort order) on Firefox vs. Chrome, others?

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#1000]
The default study list, with no filtering, is sorted differently in different browsers. Why?

**Comment by kcranston** [comment]
I've noticed the same thing, FWIW.

**Comment by jimallman** [comment]
OK, this was a deeper rabbit hole than I expected. There's no ECMAScript standard for "stable" list sorting (resulting order of an "equal" pair), so we now capture the initial list position for each item and use this as a "tie breaker" during list sorting, where the outcome is otherwise tied. 

See this link for useful background:
http://www.alex-arriaga.com/how-to-get-same-results-when-sorting-javascript-arrays-in-all-browsers/

I've also cleaned up some of the sorting comparators so that they always coerce properties to the expected data type, to avoid other browser quirks.

**Comment by jimallman** [comment]
This is working now (consistent list displays on all browsers) on **devtree**.
