### ISSUE TITLE
Easy-add trees to synthesis

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#1002]
Let's make it easier for people to propose trees for synthesis. Some thoughts, based on previous discussions:

* remove the study-level "this study should contribute to synthesis" box 
* better highlight the 'Preferred' status of trees (see [mockup](https://opentreeoflife.mybalsamiq.com/projects/curatormockups/New%20study%20homepage)) for one suggestion
* when someone proposes a tree for synthesis, add it to the `opentreeoflife/default` collection (and give user info about clade-specific collections and ranking)
* put all Preferred trees into the `opentreeoflife/default` collection (maybe doing a sanity check first?)

**Comment by jar398** [comment]
(isn't this issue redundant with #1070 ?)

**Comment by kcranston** [comment]
Indeed redundant, and less up-to-date.
