### ISSUE TITLE
Curator: data as singular?

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#1020]
![screenshot from 2016-08-12 12 02 43](https://cloud.githubusercontent.com/assets/808499/17628702/b6292f6a-6084-11e6-9ed6-fc3cddd223e1.png)

Can we change this to: "Data for this study _are_ archived..."

**Comment by jimallman** [comment]
Just [google 'data singular or plural'](https://www.google.com/webhp?q=data%20singular%20or%20plural) to see the arguments for both sides. [This link](http://www.quickanddirtytips.com/education/grammar/is-data-singular-or-plural) highlights a useful distinction between 'count nouns' (e.g. apples) and 'mass nouns' (e.g. information, butter) composed of stuff that's not readily countable. Maybe this is a useful guide.

Of course that can be trumped by convention, if 'data' is consistently treated as plural in scientific writing. I've seen some evidence for this, but it appears actual usage is mixed.

**Comment by josephwb** [comment]
I am aware of the issue, but hold strongly that 'data' is plural. Happy to be overruled; just one of my  :cat: :dog: :bird: :snake: :snail: peeves.

**Comment by jar398** [comment]
I used to be totally with you, until I started reading Language Log (a blog
written by a small collective of linguists). E.g.

http://languagelog.ldc.upenn.edu/nll/?p=4396
http://languagelog.ldc.upenn.edu/nll/?p=14970

I haven't made the switch from "the agenda are" to "the agenda is", however.

**Comment by josephwb** [comment]
Ok, I was counting on you to 1) be the only one who cared about this and 2) might agree with me. Since you do not agree, and have read far more on the topic than I, I'll consider myself overruled.

**Comment by jar398** [comment]
More worrying to me is the use of "data" to refer to information that is
inferred.  Data is (are) supposed to come from a sensor or measuring device
with relatively little interpretation or processing. It is "given" to us by
nature, not generated by our minds or computers. Once there is processing,
we have a calculation, interpretation, hypothesis, summary, etc., not
data.  I personally would not describe the output of a phylogeny
reconstruction algorithm as "data". But if the phylogenetics community uses
the word "data" in this other sense, maybe we should go with the flow.
