### ISSUE TITLE
Importing tree file doesn't like taxon names like this 'Bembidion (Notholopha) sp. 1'

### ISSUE THREAD

**Issue by DMaddison** [OpenTreeOfLife/opentree#1023]
Importing a tree file with this taxon name: 'Bembidion (Notholopha) sp. 1' caused importing to fail.  It also gave a non-informative error message.

**Comment by mtholder** [comment]
fixed in NCL - it was actually a core dump caused by some but not all edges having lengths. 
Fixed and deployed.
