### ISSUE TITLE
curator app: if some branches have lengths and others don't, the app lies to the user.

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#1024]
see https://tree.opentreeoflife.org/curator/study/view/ot_760

**Comment by jimallman** [comment]
My bad -- the code currently just checks a single branch (first one found), assuming that branch lengths would apply to all-or-none. Am I correct that the misrepresented tree above is the one that currently shows as "no branch lengths found"?

@mtholder (or others), please describe the proper behavior. Should I check _all_ branches for length, and treat a single instance as a tree-with-branch-lengths? If so, how should the different branches (with and without length) be represented visually in the tree view? Should they be distinct in color or style, or is it enough that the length figure (red) only appears on branches with length?

**Comment by mtholder** [comment]
I think that we need to check all. if any are missing lengths, then I think that we can disable the tree-with-branch-length view. I think we just want to say "Some of the branches are missing lengths" rather than "no branch lengths found".
I don't *think* is not a common case, but it is disconcerting to users who know that some branches have lengths.

**Comment by jimallman** [comment]
Thanks, will do!

**Comment by jimallman** [comment]
@mtholder In cases where some-but-not-all branches have length, I assume we still want to gather 'Branch length mode', and possibly time units. Correct?

**Comment by mtholder** [comment]
Yes. I think we'd want the user to be able to specify a units for the branches that have lengths.

**Comment by jimallman** [comment]
See the linked PR above for details on the proposed fix, and a test URL on **devtree**.
