### ISSUE TITLE
curator app: it would be nice to show the original label for a tip in a tree in the tree tab

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#1025]
For example,  @DMaddison is trying to set the exemplar, but it is not easy to do because all of the tips have the same label (the mapped name) in the UI. 
If the original label showed up when you clicked a tip, that would be sufficient for these purposes.

**Comment by jimallman** [comment]
I believe we do this already, exactly as you describe (click on a tip in tree view to see its original label). OK to close this?

**Comment by mtholder** [comment]
yup. sorry.
