### ISSUE TITLE
Versioning in web application URL

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#1031]
From @hyanwong on gitter:

'By the way, I think the versioning of the website is not working, as https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott361838 produces the same web page as for opentree6.1, whereas the synthetic newick for v5 which I have here is lacking all those Chlamydomonas species at the plant root.'

**Comment by jimallman** [comment]
This is a known issue. The version designator in the URL currently makes no difference — we always show the latest synthetic tree. This was added in anticipation of serving multiple versions, which i believe is coming Real Soon Now.

**Comment by jar398** [comment]
There will always be old versions that we have no saved - that was the idea
behind point releases (only one point release per major release is to be
archived). So how about showing some kind of landing page in this situation
that says: Sorry, we no longer have version 5.1, would you like to see a
similar node (ott --, or mrca of -- and --) in version 6.0?

**Comment by mtholder** [comment]
not only does it show the wrong version in the URL, but using the shortened form: https://devtree.opentreeoflife.org automatically expands to the old version number (even though you are seeing the wrong version).

**Comment by jimallman** [comment]
@mtholder, the expansion is to [the latest synthesis version](https://github.com/OpenTreeOfLife/opentree/blob/45a75fd190892290be6ff0c84da57f3a635e0e77/webapp/controllers/default.py#L123), as reported [by treemachine](https://github.com/OpenTreeOfLife/opentree/blob/45a75fd190892290be6ff0c84da57f3a635e0e77/webapp/private/config.example#L45). If we've deployed a newer synthetic tree on **devapi**, it's still reporting its version as 'opentree7.0'.

**Comment by jimallman** [comment]
The current fix is live on **devtree**. (I'll make a proper pull request once GitHub is back to normal; PR feature is borked at the moment.) There's no visible change for [URLs that use the current synthesis version](https://devtree.opentreeoflife.org/opentree/argus/opentree7.0@mrcaott47ott14921/SRB2--Bacilli), but [anything other than this version](https://devtree.opentreeoflife.org/opentree/argus/opentree6.8@mrcaott47ott14921/SRB2--Bacilli) _or_ 'ottol' will be redirected to the current synthesis version with a warning, like so:

<img width="926" alt="screen shot 2016-10-31 at 11 00 01 pm" src="https://cloud.githubusercontent.com/assets/446375/19878575/ae09f71c-9fc0-11e6-91ea-f346a3c5e9d8.png">

Note that the URL has already been changed, so this warning will not appear again unless the user jumps directly to another "bad" URL.
