### ISSUE TITLE
Confusion about edited label in New Taxon window

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#1034]
When you select a taxon and open the New Taxon window, the `New taxon name` field is populated with `Modified for mapping` label from the OTU Mapping tab (or with the `Original taxon label`, if no modified label exists). If the user then deletes that text, then are stuck in a strange state of not being able to say "I don't want to modify the label". Opening and closing the popup doesn't work, because the state is saved. I wonder if "I want to submit a modified label" should be an explicit option to avoid this confusion. 

In addition, can we just use red asterisks to indicate required fields, rather than the red boxes, at least before a user tries to hit submit? Otherwise, it looks like the form is full of errors even if filled out correctly. 

<img width="564" alt="screen shot 2016-08-18 at 2 56 53 pm" src="https://cloud.githubusercontent.com/assets/312034/17786708/1b4c761c-6554-11e6-9926-2742df8a7093.png">

**Comment by jimallman** [comment]
> If the user then deletes that text, then are stuck in a strange state of not being able to say "I don't want to modify the label".

What is the user's intent in this case? If they'rey trying to use the original label, I had assumed they would copy + paste from previous line. We could add a button to do this, I suppose, and enable it whenever the "New taxon name" doesn't match the original label. Or we can (implied in your answer) use the original label if the "New taxon name" field is empty, but this seemed pushy to me.

**Comment by jimallman** [comment]
See updates and screen grabs in PR #1036
