### ISSUE TITLE
change default sort order

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#1056]
We hoped this wouldn't be the case, but [this PR](https://github.com/OpenTreeOfLife/opentree/pull/1048) does indeed sort the studies without metadata to the top of the list. Evident on production:

<img width="1009" alt="screen shot 2016-09-21 at 9 01 38 pm" src="https://cloud.githubusercontent.com/assets/312034/18734068/9e74e4e8-803e-11e6-87a3-9629c030f89c.png">

Can we change the default sort order so that these do not appear at the top of the list?

**Comment by jar398** [comment]
Alternatively, the hopeless ones (no trees, no actionable metadata) could
be deleted, and the ones for which publications can be found could be given
proper metadata.  Probably 20 minutes of work, or less.

**Comment by jimallman** [comment]
There will always be the possibility of new unfinished studies, so it does seem best to bury these in the default sort order. This (tiny) fix is now working on **devtree**.
