### ISSUE TITLE
Curator hangs after tree window is closed

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#1079]
If you open a tree window to look at a tree and then close it using the little upper right x, you can't navigate to other tabs without refreshing the window, which causes the tree to pop up again. But it you click red 'close' then it's fine.

**Comment by jimallman** [comment]
@snacktavish  I believe this is fixed by the (pending) PR #1126 (see related issue #1123). Please try to reproduce this on **devtree** and mark this as closed if all's well. Thanks!
