### ISSUE TITLE
Conflict vis sometimes doesn't load

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#1083]
e.g. https://tree.opentreeoflife.org/curator/study/view/pg_2708/?tab=trees&tree=tree6289
Conflict with taxonomy works if you go to the analyses tab, but just doesn't load if you click 'go' on the trees tab.

**Comment by snacktavish** [comment]
follow up: if I search for a study, open it, click on the tree, conflict doesn't work, but if I refresh the page and try again it does work.

**Comment by kcranston** [comment]
Confirming that this is flaky. With devtools open, the first time you load the tree popup and try a conflict analysis, no conflict call gets sent. If you re-load and try again, it works.

**Comment by jimallman** [comment]
@snacktavish @kcranston I believe this is fixed by the (pending) PR #1126 (see related issue #1123). Please try to reproduce this on **devtree** and mark this as closed if all's well. Thanks!

**Comment by kcranston** [comment]
Yup - seems to be fixed now. Thanks!
