### ISSUE TITLE
Small changes to conflict viewer to adjust for service changes

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#1089]
As an appendix of https://github.com/OpenTreeOfLife/reference-taxonomy/pull/255 the conflict service now returns information on all mapped tips, so that we can distinguish the various cases (support, resolves, absent). This will require a very simple change to the webapp:

* In addConflictInfoToTree, in the $.each, there needs to be a check for the presence of conflict info returned by the service; if there is no info, default to the current behavior (I think), otherwise do the same for tips as for internal nodes. (Yes, that implies a black edge when the tip is absent - in the new regime, absent iff {either unmapped or mapped to a taxon that has been deleted}.)

Also - I guess this is unrelated - we now see a lot of "Resolves ???", "Conflicts with ???" and so on, where formerly we saw "Resolves anonymous synth node" etc. No change is strictly needed here, since the ??? is hyperlinked to the synthetic tree, but we might consider using a more attractive and informative placeholder instead of ???, perhaps "anonymous synth node". That would be a simple change to getNodeConflictDescription .

**Comment by kcranston** [comment]
Can we not display the mrca id for the synth tree node rather than "???" or "anonymous synth node"

**Comment by jimallman** [comment]
certainly, but in the past we tended to hide synth-tree node ids.

**Comment by jimallman** [comment]
> Can we not display the mrca id for the synth tree node rather than "???" or "anonymous synth node"

This behavior is working now on **devtree**.
