### ISSUE TITLE
Internal node label prevents node info popups

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#1094]
Not many studies have internal node labels, which is why this hasn't come up before, but there's a taxonomy here:

https://devtree.opentreeoflife.org/curator/study/edit/tt_150?tab=trees&tree=tree1

and it's impossible to get any of the node info boxes to pop up.

**Comment by kcranston** [comment]
Here is a production example from @josephwb : https://tree.opentreeoflife.org/curator/study/edit/ot_1001?tab=trees&tree=tree1

**Comment by josephwb** [comment]
>Not many studies have internal node labels

I am not sure about that; I try for every tree I upload to include node support values. Still, I have never had this problem before. In the instance above I believe it has to do with the _precision_ of the values taking up more space.

**Comment by jar398** [comment]
In (a,b)c:12345  I would expect the tree via to show 'c' as the visible
label on the displayed tree. c is often null, and then we'd have
(a,b):12345, not (a,b)12345, right? I didn't think the post-: numbers were
ever shown, but I have never tried it. Does the curator app really show
both the 'c' label and the 12345?

**Comment by josephwb** [comment]
No, the post-: numbers should not be shown, as they are edge lengths. My trees look like this:
(a:0.123,b:0.456)0.789:0.135
that is, the label '0.789' is numeric (a support value), but so is the edge length. Maybe that is confusing. I never have internal node labels that are non-numeric (say, names), and we do not support nodes having both names _and_ support values, so we are probably talking about two different situations (with similar problems).

I think I am being obtuse on this; please ignore ;)

**Comment by josephwb** [comment]
Want to mention that I have this problem (having difficulty selecting a node) in a [tree with no labels whatsoever](https://tree.opentreeoflife.org/curator/study/edit/ot_1002/?tab=trees&tree=tree1). I was able to select the node eventually, but it was very sensitive (maybe a few pixels wide).

**Comment by josephwb** [comment]
That (above) was in Safari (mac). On FireFox (also mac) I cannot select a node at all.

@jimallman Should I make a new issue, or will things get taken care of here?

**Comment by jimallman** [comment]
I'm 99% sure this issue will cover both symptoms. I'm planning on making this field "transparent" to mouse events (so it won't block the node) and adding a separate field for internal labels. (The field you're current seeing is for support values, branch lengths, etc.)

**Comment by kcranston** [comment]
we could also have a show / hide node labels option that would help with trying to select nodes (even if we do clean this up, I suspect will still be a challenge with large trees)

**Comment by josephwb** [comment]
I don't think tree size is relevant, is it? Larger trees are not more compressed, just bigger.

**Comment by josephwb** [comment]
Are we even sure it is the node label that is the problem? I link above to a tree with no node labels whatsoever, and the behaviour is exactly the same.

**Comment by jimallman** [comment]
> Are we even sure it is the node label that is the problem?

Yes, I recently added non-breaking spaces to "empty" node labels so that they will provide a visible node highlight. The fix for blocking mouse events is tiny, but I'm trying to clean up other logic related to the styling and placement of node (and edge?) labels.
