### ISSUE TITLE
labels of nodes in tree view can be too far from the node

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#1102]
See Holozoa on this view of the tree currently on devtree. It is fairly obvious that it refers to the large node up and to the left of the label, but it is surprising that the label is below the branch dashed line of the tip below the node. Seen on Chrome and FF on Ubuntu 16.04

![screenshot from 2016-11-28 09-51-10](https://cloud.githubusercontent.com/assets/136067/20674973/630af946-b550-11e6-8a7d-6519d29e3edb.png)

**Comment by jimallman** [comment]
I see that the label 'Opisthokonta' is also farther than it needs to be. It looks like we place each label to accommodate the size of its node; I'll review the logic for larger sizes.

**Comment by jimallman** [comment]
Here's the revised spacing for the view above, currently visible on **devtree**:

<img width="356" alt="screen shot 2016-11-30 at 4 04 55 am" src="https://cloud.githubusercontent.com/assets/446375/20746120/76f76472-b6b2-11e6-9ddb-ec5c7c7ef640.png">
