### ISSUE TITLE
Prevent warning on "ambiguous" tip labels?

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#1116]
@josephwb has reported that [some trees](https://tree.opentreeoflife.org/curator/study/edit/ot_1013?tab=trees) are flagged in the curation app as having "ambiguous labels", but they have no (internal node) labels as far as we know.

It seems this is happening because they have a few **tips** with `@label` properties. (The [code that detects ambiguous labels](https://github.com/OpenTreeOfLife/opentree/blob/master/curator/static/js/study-editor.js#L8713-L8718) doesn't filter these out.) As a result, we see the warning, but the tree popup doesn't know how to highlight these tips.

Should we disregard tip labels in this test, as implied by the UI? Or is it possible for tip labels to be ambiguous?

**Comment by jar398** [comment]
I can’t find anything in the nexml docs saying anything about @label for node elements. For other elements they're just supposed to be 'human readable'. That suggests arbitrary labels be allowed, which means that ambiguity (regardless of how that is determined) must be tolerated. If there is a ot:nodeLabelMode with value ot:rootNodeId, you could argue that it would be wrong for two nodes to have the same @label property, but I see no similar restriction for the other modes.

Even for mode ot:taxonNames , you could have different occurrences of the same name map to different OTT ids, and/or an exemplar could be defined, neither of which would be an error. I would say that any check of this sort should be done on mapped tips, not on @label properties.

**Comment by jimallman** [comment]
I believe this behavior has been fixed in PR #1129 (by checking only internal node labels for "ambiguity").

**Comment by jimallman** [comment]
As I'm the nominal submitter, I'll close this issue.
