### ISSUE TITLE
OTUs don't map although tip is in taxonomy

### ISSUE THREAD

**Issue by acaciamulga** [OpenTreeOfLife/opentree#1142]
I am trying to map many legume tips. There are dozens of species (such as Mariosousa russelliana) that don’t map but when I try to add them as a new OTUs, I  get a red error message stating that they are already in the OT taxonomy.  

I also tried to make two new Fabaceae genera (Parasenegalia and Pseudosenegalia).  I thought it worked but they are not available as a parent when I try to make the new species.

Any ideas?
Thanks,Joe

**Comment by mtholder** [comment]
Hi Joe, I'm not seeing Parasenegalia or Pseudosenegalia in the taxonomy (e.g. https://tree.opentreeoflife.org/taxonomy/browse?name=Pseudosenegalia ) , so they did not make it to the taxonomy server. I'm not sure where in the pipeline they got stuck. I'm out of town right now, so it'll be a few days before I can dig into the details to see where it is falling through the cracks... I'll try to get back to you early next week. 
all the best,
Mark

**Comment by acaciamulga** [comment]
Thanks Mark

Joe
------------ 
Joe Miller
Arlington, VA
http://www.acaciamulga.net/ <http://www.acaciamulga.net/>
work 703-292-7214
cell 571-451-9691

**Comment by mtholder** [comment]
Just a quick note to say that we did find the issue that was causing the message about the new taxon to be lost in the server side communication. We should be able to prevent this from happening again. I still need to schedule some downtime (probably for this weekend) to reboot the taxonomy services and get them back in sync. I'll put another comment here when it is ready. Sorry that this took longer than I anticipated...

**Comment by mtholder** [comment]
### the good news:  the pipeline for adding new taxa is fixed.
Sorry for the lag. The software issue related to the new taxa making it through to the server has been addressed (I think). See, for example, https://tree.opentreeoflife.org/taxonomy/browse?name=Parasenegalia

### the caveat:
However, there is an issue that probably means that you won't be happy with the taxonomy until it is rebuilt. 

### the other good news:
In this case is that it appears that the new taxa you need have been added to the NCBI taxonomy. So when @kcranston  and @jar398 build a new version of the taxonomy, the issues you ran into for this study should be fixed.

###  Background info about how the current "add a taxon" feature is insufficient for the general case:

If this were a not in an NCBI update, then things would be messier. The current "add a taxon" feature really only works well with the case of adding a newly described species. Looking at https://tree.opentreeoflife.org/curator/study/view/ot_1229 it appears that the new taxa _Parasenegalia_ and _Pseudosenegalia_ are new names for subsets of what our taxonomy calls _Senegalia_ (see https://tree.opentreeoflife.org/taxonomy/browse?id=92810 ).

We definitely would like to support a richer set of taxonomic amendments (see for example section 4.2.2 of our pending proposal at http://phylo.bio.ku.edu/ot/2017-OpenTree-ABI-proposal.pdf ), but in the current system the only way to correct taxonomic errors like this are to:
  1. fix them in the source taxonomy and then wait for the next version of OpenTree Taxonomy to be built. OR
  2. go through a tedious procedure of creating a new taxonomic source of the OpenTree taxonomy, OR
  3. let us know of another online taxonomic source that would work (then wait for one of us to have the time to write an adaptor for that taxonomic source to be added to the OpenTree taxonomy).

I'll close this now, but we can reopen if we find new problems related to this feature or set of taxa.
