### ISSUE TITLE
treat synonyms as exact matches

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#1155]
If you map one of the "Amnirana albilabris" in otus in https://tree.opentreeoflife.org/curator/study/edit/ot_1261?tab=otu-mapping (with the currently modified name), you find an exact match to "Hylarana albolabris" via a synonym.

But when you click the "Accept exact matches" button the match is not accepted. Presumably this is because it does not have a 100% match with what OTT considers to be the valid name. I think we should allow these to be treated as exact matches (because they are unambiguous, and OTT often lags behind the current preferred name).
Or we could add another "Accept exact matches even if to synonyms" button. 
This could really speed up the curation of some studies by requiring less clicking.

**Comment by snacktavish** [comment]
![image](https://github.com/OpenTreeOfLife/opentree/assets/1652782/b4fa4be2-7f0c-4894-a937-3ce83fb2751c)
Related - here there are exact matches, and accept exact matches doesn't cause them to be accepted. Which results in needing a lot of clicks on a big study!

**Comment by jimallman** [comment]
On closer inspection, it looks like my code assumed that an exact match would be the **only** match returned, when this is obviously not the case. The matching code should always return exact matches (on the name submitted) before synonyms, so I'll auto-accept the first provided value if its score is 1/1.0 ("exact match") for our purposes.

**Comment by jimallman** [comment]
@snacktavish Please try the updated behavior on **devtree** (in both the study curation tool, and bulk TNRS). We now handle the (many) situations where multiple exact matches are found. At this point, I'm grabbing the first result that passes all our tests, but NOTE that this could lead to not-the-best-choice, see for example results for `Casearia`:
![Screenshot 2024-03-12 at 12 39 32 PM](https://github.com/OpenTreeOfLife/opentree/assets/446375/d119bba6-3201-4879-af54-7bd65163ba9d)

I gather the first response here is not necessarily the best choice, but it's not clear how to choose automatically. And of course this dilemma goes away if the search context is more specific than "All life". Thoughts?

**Comment by snacktavish** [comment]
Only auto accepting if there is only one exact match makes sense!

**Comment by jimallman** [comment]
NOTE that searching for 'Hylarana albolabris' now gives one exact(?) match, a synonym. This is auto-accepted if we check the box, but not if we explicit click the auto-accept *button*.

**Comment by jimallman** [comment]
Please take a look at **devtree** for the new behavior (as described above):

 - both checkbox and button now auto-accept synonyms that match exactly
 - whenever there are more than one exact matches, we prompt for manual review
