### ISSUE TITLE
Using URL with non-preferred domain name will ultimately fail

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#1178]
This is not news, but I don't see any existing issues here or in the https://github.com/OpenTreeOfLife/feedback repo, so here goes:

We've found that Google will sometimes capture an URL from one of our internal aliases like **ot43.opentreeoflife.org**, e.g. https://ot43.opentreeoflife.org/opentree/argus/opentree10.4@ott844192/Bacteria 
... instead of the preferred hostname for this web-app:
https://tree.opentreeoflife.org/opentree/argus/opentree10.4@ott844192/Bacteria

The bogus URL can be returned as a search result on Google, and it will bring someone to the desired view. But since the hostname isn't expected, some features (notably login and other GitHub-related features) will fail.

It looks like someone (@mtholder?) added a fix to bounce there when a login fails, but I think we should nudge _all_ incoming HTTP requests to our preferred hostname. Fix coming soon...

**Comment by jar398** [comment]
HTML `<link rel="canonical" ...>` apparently has problems, but it's worth a try; google might respect it. There's also a replacement for it working through the standards mill but I forget what it's called (maybe "citation" but I can't find it).

**Comment by jimallman** [comment]
From my reading so far, a 301 redirect will nudge Google to modify a search result on re-indexing. The PR above will provide this (from apache), so I'm not sure we need to do more.

**Comment by jar398** [comment]
OK, that sounds right.  Not clear to me why the otxx host names would ever be used, so maybe cutting them off at their source would be another thing to do?  (belt and suspenders)

**Comment by jimallman** [comment]
> Not clear to me why the otxx host names would ever be used

We still use them as "tags" for deployment, right? This gives us one level of indirection between a numbered AWS instance and our mnemonic hostname. The fix above takes advantage of the difference between SSH/etc. and HTTP traffic to get the desired result without messing up other possible workflows.

**Comment by jimallman** [comment]
Looks like the fixes above were accepted and do the job. Closing this now (please re-open if it needs more work).
