### ISSUE TITLE
`v3/tree_of_life/induced_subtree` should return a list of all OTT ids that could not be found

### ISSUE THREAD

**Issue by gaurav** [OpenTreeOfLife/opentree#1184]
When I look up *Anthracosaurus russelli* using [`/v3/tnrs/match_names`](https://github.com/OpenTreeOfLife/germinator/wiki/TNRS-API-v3#match_names), I get back an OTT id of [6158533](https://tree.opentreeoflife.org/taxonomy/browse?id=6158533) marked with two taxon flags: `extinct` and `major_rank_conflict_inherited`, both from [the 'incertae sedis'-like flags](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/doc/taxon-flags.md#taxon-flags) category. If I then use that OTT id in a [`/v3/tree_of_life/induced_subtree`](https://github.com/OpenTreeOfLife/germinator/wiki/Synthetic-tree-API-v3#induced_subtree), I get back an error:
```
$ curl -X POST https://api.opentreeoflife.org/v3/tree_of_life/induced_subtree -H 'content-type:application/json' -d '{"ott_ids":[6158533,485827,4948430,4126507]}'
{
    "message": "[/v3/tree_of_life/induced_subtree] Error: node_id 'ott6158533' was not found!"
}
```

Note that this error message only returns one of the OTT ids that could not be found. It would be great if the [`induced_subtree` API call](https://github.com/OpenTreeOfLife/germinator/wiki/Synthetic-tree-API-v3#induced_subtree) returned a list of *all* OTT ids that could not be found, as [`/v2/tree_of_life/induced_subtree`](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#induced_subtree) used to do. That way, if I have a large number of OTT ids I am trying to calculate an induced subtree for, I could eliminate the OTT ids not found on the synthetic tree and retry the `induced_subtree` API call.

Alternatively, if the `extinct` and/or `major_rank_conflict_inherited` flags were to be included in the ["Flags leading to taxa being suppressed from the synthetic tree" section of the taxon-flags documentation](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/doc/taxon-flags.md#flags-leading-to-taxa-being-suppressed-from-the-synthetic-tree) (which would help with #777), then I could filter them out before calling `induced_subtree`. Should I be doing that? Is there another API call I should be using to determine which OTT ids are on the synthetic tree?

Finally, note that the [Open Tree Taxonomy entry for 6158533](https://tree.opentreeoflife.org/taxonomy/browse?id=6158533) has a link that says "View this taxon in the current synthetic tree" (not true), which leads to an [error page](https://tree.opentreeoflife.org/opentree/argus/ottol@6158533). I think this type of error was previously reported as #836.

**Comment by jar398** [comment]
This is a special case of https://github.com/OpenTreeOfLife/germinator/issues/80 I think

**Comment by mtholder** [comment]
not a good solution, but the file in http://files.opentreeoflife.org/synthesis/opentree10.4/output/cleaned_ott/cleaned_ott.json 
lists the pruned because of flags.

**Comment by gaurav** [comment]
After our in-person meeting last year, someone (I think @bredelings?) modified the `induced_subtree` call at https://ot39.opentreeoflife.org/v3/tree_of_life/induced_subtree so that it returned a list of all OTT IDs that could not be resolved, and I modified our software so that it would remove these IDs from the query and then would re-request the induced subtree. This worked great, but it looks like https://ot39.opentreeoflife.org/ is now offline and https://devapi.opentreeoflife.org/v3/tree_of_life/induced_subtree doesn't have this modification yet (it still reports only a single missing OTT ID at a time). Any chance you could get OT39 back online or get those changes pushed to devapi? Thanks so much for looking into this!

**Comment by bredelings** [comment]
Hi Guarav, it looks like all the servers are reporting the list of ottids that could not be resolved in the returned JSON, although the "message" field itself only lists one.  We had to keep the "message" field the same for backwards compatibility.
```
$ curl -X POST -H "accept":"application/json" -H "content-type":"application/json" https://devapi.opentreeoflife.org/v3/tree_of_life/induced_subtree --data '{"ott_ids": [292466, 501678, 267845, 666104, 316878, 102710, 176458,1234567,12345678]}'
{
    "message": "[/v3/tree_of_life/induced_subtree] Error: node_id 'ott12345678' was not found!",
    "unknown": {
        "ott1234567": "invalid_ott_id",
        "ott12345678": "invalid_ott_id",
        "ott666104": "pruned_ott_id"
    }
}
```

**Comment by bredelings** [comment]
There could be other changes that affect your site, since we replaced all of our servers with new ones during the last week, and updated the software running on them.  This was all done in a hurry, so please let us know if something isn't right.  But as a side effect, every should should be very up-to-date!

**Comment by gaurav** [comment]
Thanks for looking into this, @bredelings! My bad: I was checking for the wrong error message in the `message` field. I've fixed, and it seems to be working well now! Should we close this issue?

**Comment by bredelings** [comment]
Glad its working now!  I'll close the issue.
