### ISSUE TITLE
Including tree in synthetic tree not working in Curator app on Linux

### ISSUE THREAD

**Issue by gaurav** [OpenTreeOfLife/opentree#1189]
I just tried including the ML tree from [Crowl et al 2016](https://tree.opentreeoflife.org/curator/study/view/ot_600/?tab=trees) in the Synthetic Tree, but I got a error message ("Sorry, there was an error including this tree. Show details"). The details are blank.

I tried this on Firefox 66 and Konqueror 5 on Debian Linux. I'll try it on macOS in a bit.

**Comment by jimallman** [comment]
@guarav, Apologies for the useless error message. Any luck on MacOS? (I'm guessing this is unrelated to the OS and browser, more likely a glitch on the server side.)

**Comment by snacktavish** [comment]
I just tried it on a Mac, same error, and the call to https://ot41.opentreeoflife.org/v3/include_tree_in_synth returns a 404

**Comment by jimallman** [comment]
Hm. The initial `OPTIONS` call (CORS preflight request) is failing on ot41. Could be a configuration error, or missing CORS support? Apparently the former, since we get a similar message in CURL whether calling with OPTIONS, GET or POST. Here's the failure from the apache `access.log` on ot41:
```log
169.236.78.20 - - [18/Apr/2019:22:11:32 +0000] "OPTIONS /v3/include_tree_in_synth HTTP/1.1" 404 789 "https://tree.opentreeoflife.org/curator/study/edit/ot_600/?tab=trees" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
```
A verbose CURL call shows a web2py error ```web2py_error: invalid function (default/v3)```, which you can also see in the browser by browsing to [the method URL above](https://ot41.opentreeoflife.org/v3/include_tree_in_synth).

So it looks a configuration problem, or perhaps otindex is missing a method from the old oti. I'll keep digging...

**Comment by jimallman** [comment]
Ah, so there are [recent additions to our apache config](https://github.com/OpenTreeOfLife/germinator/blob/master/deploy/setup/opentree-shared.conf#L53-L59) to support v3 API calls throughout the webapps. These are missing on the production api server. Either it hasn't been redeployed along with the web-app repository, or it was deployed from a bad/old version of germinator. I'll confirm all branches and redeploy api server.

**Comment by jimallman** [comment]
Took a little scrutinizing, then I re-deployed phylesystem-api (only!) using the `**new**production/api.config' file that knows about ot41. Then I was able to include the ML tree as expected. (Feel free to remove and re-include it, if you want to test the fix.) Presumably other v3 API calls will work better now.

Hopefully we can remove `newproduction` (or move it ot `production`) soon... It's making me nervous. :worried:

**Comment by jimallman** [comment]
@gaurav Thanks for the heads-up about this!

**Comment by gaurav** [comment]
@jimallman My pleasure! Thanks for the quick fix, and the ML tree is now [queued for synthesis](https://tree.opentreeoflife.org/curator/study/view/ot_600?tab=trees)!

**Comment by jimallman** [comment]
Closing this now, as @mtholder has [removed the confusing `newproduction` stuff](https://github.com/OpenTreeOfLife/deployed-systems/commit/c24de71d9d60e135ce053eb6e93c7807372f3390) in deployed-systems.
