### ISSUE TITLE
Web2py error on "download subtree as newick string"

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#1231]
https://tree.opentreeoflife.org/opentree/default/download_subtree/node-id/mrcaott31957ott79793/Hipposideridae--Megadermatidae

returns a web2py error.

Seems to be related to gluon changes in new version of web2py.

**Comment by mtholder** [comment]
I think that one is one of the instances that caused me to start https://github.com/OpenTreeOfLife/opentree/issues/1230

**Comment by jimallman** [comment]
The `download_subtree` method depends on a python module `contenttype`, and I'm no longer sure where it came from. Chasing this now...

**Comment by jimallman** [comment]
It looks like we need to explicitly `import gluon.contenttype` now. But it's moot, since this import isn't being used in the rest of this method. I've commented out the line and now we get the subtree newick, as expected.

I'll make a tiny PR for this fix...

**Comment by mtholder** [comment]
https://github.com/OpenTreeOfLife/opentree/pull/1229

**Comment by snacktavish** [comment]
Fix is up on devtree and looks good!

**Comment by snacktavish** [comment]
Deployed to production! Yay!
