### ISSUE TITLE
ERROR loading details for this conflicting tree!

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#1269]
https://tree.opentreeoflife.org/opentree/argus/ottol@765185/Anas

The conflicts show up, but not the citation information.
I'm trying to recollect if this is phylesystem-api issue, or maybe otindex.

**Comment by jimallman** [comment]
@snacktavish I'm trying to clean up old issues today. I believe this one is working as expected. Can you confirm at the URL above?

**Comment by snacktavish** [comment]
Looks great!
