### ISSUE TITLE
Issue on new development website on the Add Study page

### ISSUE THREAD

**Issue by laurenholdermanphylo** [OpenTreeOfLife/opentree#1285]
Upon clicking the continue button after filling in the DOI on the publication info bar, with the no license option selected, there is no response from the site itself and it reloads only to return to the same page, with both options still selected

**Comment by laurenholdermanphylo** [comment]
Actually! Upon comparison with the older version of the site, it appears that the issue is that the new site doesn't show when there are already open studies for that DOI, instead of the above issue.

**Comment by laurenholdermanphylo** [comment]
Actually actually, upon finding a prism doi that actually works, it is revealed that both of the above issues are valid, as the page will not move on from the Add Study page, despite loading animation.

**Comment by jimallman** [comment]
Thanks for the heads-up! Chasing these issues now...

**Comment by jimallman** [comment]
@laurenholdermanphylo : Progress! I'm still cleaning up some minor bugs in duplicate-DOI testing and CrossRef importing, but you should now be able to create studies from DOI and try more features.

**Comment by jimallman** [comment]
@laurenholdermanphylo : OK, I've improved our duplicate-DOI test to match any instance of the "bare" DOI, regardless of the format (URL, "doi: " prefix, etc.) used. This should prevent "false negatives" and avoid expensive re-work.

**Comment by jimallman** [comment]
Another minor update: When importing a study with DOI, we briefly lost the publication-reference string retrieved from CrossRef. This is fixed now.

**Comment by laurenholdermanphylo** [comment]
Awesome. I will get back to testing!
