### ISSUE TITLE
Curator blocks taxon addition of existing names

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#1288]
e.g. https://github.com/OpenTreeOfLife/reference-taxonomy/issues/391

but it also seems to store names that you just typed, but didn't submit, and reject those as 'already proposed' as well.
Given that we already have homoyns anyhow, I think a less gated taxon addition process would be good.

**Comment by jimallman** [comment]
@snacktavish, OK to close this? I think it's working as expected on **devtree**.

**Comment by snacktavish** [comment]
Awesome! and Yes. I meant to test on dev tree, but didn't get a chance. Thanks!!
