### ISSUE TITLE
Taxonomy browser is broken in latest deployment

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#1289]
I'm adding an issue for this (while also trying to fix it) to document the symptoms and possible remedies.

**Comment by jimallman** [comment]
Recently the [taxonomy browser](https://devtree.opentreeoflife.org/taxonomy/browse?name=homo+sapiens) was failing on devtree (500 internal error from Apache), for three reasons:
 - apache config was pointing to an old path to find this CGI script
 - system python version has changed from python2 to python3 (updates needed)
 - missing `requests` module in the system python

Possible fixes include:

 1. Make the #! (shebang) line in browse.py dynamic, to reflect the installed location. Sadly, this requires moving the file into Ansible as a template file, which removes it from its original context in the `opentree` repo.
 2. Use some kind of wrapper defined in the apache config, to specify an interpreter inside the desired venv (so requests is available).
 3. Force the shebang to python2, and install the requests module in the system python2 environment. (This adds a lot of unneeded junk IMO.)

I'm working toward solution 2 above, since that seems cleanest...

**Comment by snacktavish** [comment]
Last deployment of devtree was using dev branch of ot-ansible, using 
`ansible-playbook playbk-install-webapp.yml -i hosts --limit devtree`

**Comment by jimallman** [comment]
For future reference, [here's an example CGI wrapper](http://bovlb.blogspot.com/2016/04/using-virtualenv-with-python-cgi-script.html) that can be used to launch in a venv. That said, I do think @bredelings 's solution above is simpler and more transparent.
