### ISSUE TITLE
link outs from tree browser to OneZoom broken

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#1309]
At least for _Pan_

**Comment by jimallman** [comment]
This seems to be working for me, on both [dev](https://devtree.opentreeoflife.org/opentree/argus/ottol@417957/Pan) and [production](https://tree.opentreeoflife.org/opentree/argus/ottol@417957/Pan). Also tested _Homo sapiens_ and others.

What should be different?

**Comment by mtholder** [comment]
agreed. it is working for me now, too. Perhaps there was a OneZoom outage that I misinterpreted as a bad link on our end.
