### ISSUE TITLE
Some AJAX errors hidden in Chrome (JSON payload ignored)

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#1320]
@bredelings I believe this might be due to an error in API method `/v3/conflict/conflict-status`. If the requested study isn't found in the specified phylesystem, a JSON error is returned, but Chrome hides this error information (no response text) and says the response status is 0. If I make the same request using cURL, the server sends the JSON error message and response status = 500):

```bash
% curl 'https://devapi.opentreeoflife.org/v3/conflict/conflict-status?tree1=ot_1022%23tree1&tree2=pg_28660%23tree6656&use_cache=false' \
  -H 'Accept: application/json, text/javascript, */*; q=0.01' \
  -H 'Accept-Language: en-US,en;q=0.9,zh;q=0.8' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Origin: https://devtree.opentreeoflife.org' \
  -H 'Pragma: no-cache' \
  -H 'Referer: https://devtree.opentreeoflife.org/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed --verbose
*   Trying 34.211.74.109:443...
* Connected to devapi.opentreeoflife.org (34.211.74.109) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Client hello (1):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Unknown (8):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, CERT verify (15):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=*.opentreeoflife.org
*  start date: Jun  1 12:37:07 2023 GMT
*  expire date: Aug 30 12:37:06 2023 GMT
*  subjectAltName: host "devapi.opentreeoflife.org" matched cert's "*.opentreeoflife.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /v3/conflict/conflict-status?tree1=ot_1022%23tree1&tree2=pg_28660%23tree6656&use_cache=false HTTP/1.1
> Host: devapi.opentreeoflife.org
> Accept-Encoding: deflate, gzip
> Accept: application/json, text/javascript, */*; q=0.01
> Accept-Language: en-US,en;q=0.9,zh;q=0.8
> Cache-Control: no-cache
> Connection: keep-alive
> Origin: https://devtree.opentreeoflife.org
> Pragma: no-cache
> Referer: https://devtree.opentreeoflife.org/
> Sec-Fetch-Dest: empty
> Sec-Fetch-Mode: cors
> Sec-Fetch-Site: same-site
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
> sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"
> sec-ch-ua-mobile: ?0
> sec-ch-ua-platform: "macOS"
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 27 Jun 2023 05:02:01 GMT
< Server: waitress
< Content-Length: 100
< Content-Type: application/json
< Connection: close
<
{
    "message": "Phylesystem: study pg_28660 not found in https://devapi.opentreeoflife.org/v3!"
}
* Closing connection 0
```
Based on the response headers shown in Chrome, I think the problem is that **this error is returned before the CORS-response headers have been set**. The same method called with a valid study ID returns as expected, even if there's another error found. Thoughts?

**Comment by jimallman** [comment]
To clarify, this bug hides the underlying problem ("Phylesystem: study pg_28660 not found in https://devapi.opentreeoflife.org/v3!") when we fail to show conflict for this URL:

https://devtree.opentreeoflife.org/curator/study/view/ot_1022/?tab=home&tree=tree1&conflict=pg_28660@tree6656

**Comment by bredelings** [comment]
Hi Jim,

I'm not sure what the right approach is here.  Part of the issue may be that we are trying to convert a GET request to a POST request.  If we simply required a POST request, then I think everything would work.

GET requests that succeed seem to have CORS headers.  However, I'm not doing anything explicit to add these headers.  All I'm doing is handling OPTIONS requests, and somehow CORS headers are magically being added to the response to the GET request.

-BenRI

**Comment by jimallman** [comment]
Yeah, there's a little too much magic going on here (GET requests to CORS methods). I'll try turning this into a POST call and see how it goes...

**Comment by bredelings** [comment]
I added the CORS headers to the exception view for ws_wrapper.  So now when ws_wrapper throws an HttpResponseError, the CORS headers will be added to the response.

Perhaps this is obvious in retrospect.  I guess most other errors are generated by otcetera and simply passed through without being altered, so most other errors "just worked" without ws_wrapper doing anything.

So https://devtree.opentreeoflife.org/curator/study/view/ot_1022/?tab=home&tree=tree1&conflict=pg_28660@tree6656 now gives a properly visible error message.  I *think* that the problem is solved then.

Thanks for your help in figuring this out!

**Comment by jimallman** [comment]
Perfect! I gather this is new-ish behavior (CORB = Cross-Origin Read Blocking) in some browsers, to avoid certain kinds of attack.
