### ISSUE TITLE
Fix number-of-tips display in tree browser to use new info from treemachine

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#279]
See https://github.com/OpenTreeOfLife/treemachine/issues/63 .
This should probably say "number of tips" or "number of terminal taxa" instead of "number of species", since not all terminal taxa are species (some are subspecies, strain, no rank, etc etc).

**Comment by jimallman** [comment]
This was fixed long ago, with accurate tip counts and the label "Descendant tips"
