### ISSUE TITLE
should move viz javascript from gcmdr to the web-app

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#299]
gcmdr/taxa_viz/synth_viz_dyn.html
gcmdr/taxa_viz/taxa_viz_dyn.html
gcmdr/taxa_viz/taxa_viz.html

could all be static files in the opentree/webapp so that we don't have to remember to copy them to some directory on whatever machine is serving as files.opentreeoflife.org

**Comment by jimallman** [comment]
Is this issue now moot? Can/should we revive these visualizations? (Last I heard, they're not working in recent deployments.)
