### ISSUE TITLE
When a taxon isn't in the synthetic tree, the reason for that should be provided

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#310]
See discussion here: 
https://groups.google.com/forum/#!topic/opentreeoflife-software/raWZ7hSfUpI

and corresponding treemachine issue here:
https://github.com/OpenTreeOfLife/treemachine/issues/98

As a first step, before the treemachine service is in place, there should be generic static text saying that the taxon is not in the synthetic tree, either because it is determined to be paraphyletic, or because it was omitted for taxonomic reasons (e.g. it was incertae sedis).

**Comment by jimallman** [comment]
> Can we as a stopgap just display some static text whenever this happens?

This is working now, including a link to the taxon in our taxonomy browser. OK to close this, or do we still want to offer a fuller explanation on demand?

**Comment by jar398** [comment]
Working great.
