### ISSUE TITLE
Direct patch from Curator

### ISSUE THREAD

**Issue by hdliv** [OpenTreeOfLife/opentree#343]
When OTUs don't map...in microbial studies many times due to strains... Can we create a direct patching system or 'ADD to OTT' so that we can directly map them?  Another study where everything has binomial species plus strain plus GB#.

![screen shot 2014-06-29 at 4 43 12 pm](https://cloud.githubusercontent.com/assets/6361361/3424399/6311b32e-ffce-11e3-9439-761428c7ec21.png)

**Comment by kcranston** [comment]
We now have a "Adding new taxa" feature in the curator app. Only took two years... ;)
