### ISSUE TITLE
Ordering of inference method in curator dropdown

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#345]
Perhaps nit-picky, but commonly used methods should be at the top of the list. Currently we have:
```
Maximum parsimony
Maximum likelihood
Neighbour-joining     <- don't forget your 'u's!
UPGMA
Bayesian inference
Least squares
Three-taxon analysis  <- I don't think this one need to be in the list at all
Other
```
I suggest we go with the following ordering:
```
Bayesian inference
Maximum likelihood
Species tree inference <- note: not in original list
Maximum parsimony
Supertree              <- note: not in original list
Neighbour-joining
Other
```
Since this might be currently on the table, perhaps we should come up with a controlled list of accepted names.

One thing I notice we don't have is a way to distinguish "molecules" from "morphology". This is one piece of information that we should be indexing. "Molecules" could of course be more narrowly defined as "DNA", "Amino acids", "Transcriptomes", etc. Erg. this is sounding like another issue...

**Comment by jimallman** [comment]
Does the current list (below) satisfy this issue? If so, please close.
<img width="387" alt="screen shot 2016-02-22 at 1 47 45 pm" src="https://cloud.githubusercontent.com/assets/446375/13228614/ede596d8-d96a-11e5-92cc-9a74d0b69736.png">

**Comment by josephwb** [comment]
I think this is now solid.
