### ISSUE TITLE
Edits to a study not being saved

### ISSUE THREAD

**Issue by chris-owen** [OpenTreeOfLife/opentree#359]
I was just editing Y. Yusa, 2012 and after pressing 'save' the edits were not saved.  I logged out and then back in, made the edits again, and saved all of the edits along the way, and when I went to leave the page to edit another study a message appeared saying that I had unsaved edits.  Any suggestions on how to get around this?

**Comment by jimallman** [comment]
@chris-owen @hdliv, we've just addressed one of the symptoms described above:

> [I] saved all of the edits along the way, and when I went to leave the page to edit another study a message appeared saying that I had unsaved edits.

I've made some changes in https://github.com/OpenTreeOfLife/opentree/pull/827 (currently on **devtree**, and heading to production soon) that should prevent some of these warnings. There's still some Nexson cleanup that occurs the first time a study is imported from TreeBASE then opened in the curation app, but these unexpected warnings should go away after saving the study.

I'm going to close this for now, but please re-open if you see the symptoms above!
