### ISSUE TITLE
Show MRCA of tree tips (OTUs) for comparison with focal clade

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#365]
When viewing a study and/or tree, compute the MRCA of all the tips/OTUs and display the nearest taxon name (using appropriate or new treemachine service). This is a simple QC step since if it says 'Eukaryota' or 'cellular organisms' then one of the OTUs is probably wrong.

Along the same lines: for any tree, show the subtended subtree of the synthetic tree for those OTUs.

**Comment by jimallman** [comment]
After [further discussion](http://irclog.perlgeek.de/opentreeoflife/2015-01-20), we've decided that saving these test results in Nexson will lead to confusion for other Nexson consumers. I'll make the change to strip these from the study Nexson before saving in the curation app.

**Comment by jimallman** [comment]
Closing this, since all requests above seem to be satisfied.
