### ISSUE TITLE
strains not mapping in Curator, though in OTT

### ISSUE THREAD

**Issue by hdliv** [OpenTreeOfLife/opentree#374]
added a study from treebase (ot_95) and the first 5-6 strains I checked that were not mapping are in OTT...at least I found them there but they are not mapping when I try to map them through curator.  On phylografter there was a scroll down bar so that I could find the correct strain.  As Curator doesn't have that...how can we can the correct strain we need for each strain when this happens??

![screen shot 2014-07-18 at 4 32 53 pm](https://cloud.githubusercontent.com/assets/6361361/3631806/2b080716-0ebb-11e4-832d-59fdfab6df8d.png)

**Comment by jar398** [comment]
I will interpret Jim's tone and Dail's "much better now" as permission to close the issue.
