### ISSUE TITLE
Include common diacritical substitutions in client-side search

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#381]
For example: Searching for "Lutzen" should find "Lützen". Since lots of this kind of filtering is done in client-side Javscript, we'll  to add a series of diacritical substitutions to search for wherever a “questionable” letter is found. The result is probably a regexp with all possible substitutions in place of each simple letter, for example:

Lutzen  ==>  /L[uü]tz[eé]n/

**Comment by jimallman** [comment]
Naturally, we're not the first to need this. [Here's a pretty thorough fix](http://stackoverflow.com/a/228006) that probably does a bit too much splitting phrases.

Note that the solution above would preserve an accented character and not match its non-accented counterpart. It seems desirable for a search "Lützen" to also find "Lutzen".

[Here's another attempt](http://stackoverflow.com/a/5913376) that strips/reduce accented characters; perhaps we could adapt both into a two-pass system that

 - detects any variant (accented or not) and substitutes the unaccented version (or a token)
 - detects unaccented chars (or corresponding tokens) and substitutes with the search-all [...]

**Comment by jar398** [comment]
FWIW, accents and diacritics are removed from taxon names before they go
into the taxonomy (they are disallowed by the nomenclatural codes). They
only occur in synonyms.

**Comment by jimallman** [comment]
See also this related article [_Accent Folding for Auto-Complete_](http://alistapart.com/article/accent-folding-for-auto-complete) and the more exhaustive [RFC 3454 - Preparation of Internationalized Strings](https://tools.ietf.org/html/rfc3454).

**Comment by jimallman** [comment]
I settled on an approach that applies all common diacritical "variants" when searching, so a search entered as `aether` will actually use this regular expression:
```
/(ae|æ|ǽ|ǣ)(t|t|ⓣ|ｔ|ṫ|ẗ|ť|ṭ|ț|ţ|ṱ|ṯ|ŧ|ƭ|ʈ|ⱦ|ꞇ)(h|h|ⓗ|ｈ|ĥ|ḣ|ḧ|ȟ|ḥ|ḩ|ḫ|ẖ|ħ|ⱨ|ⱶ|ɥ)(e|e|ⓔ|ｅ|è|é|ê|ề|ế|ễ|ể|ẽ|ē|ḕ|ḗ|ĕ|ė|ë|ẻ|ě|ȅ|ȇ|ẹ|ệ|ȩ|ḝ|ę|ḙ|ḛ|ɇ|ɛ|ǝ)(r|r|ⓡ|ｒ|ŕ|ṙ|ř|ȑ|ȓ|ṛ|ṝ|ŗ|ṟ|ɍ|ɽ|ꝛ|ꞧ|ꞃ)/i
```
It's wacky but fast and very thorough. In the current version running on **devtree** you'll see the modified search regex (as above) logged to the browser's JS console.

Please let me know if you spot any common diacritical marks that aren't handled here. See [the diffs of PR #1047](https://github.com/OpenTreeOfLife/opentree/pull/1047/files#diff-f0706e4d2cee3bf63a91062a19eeb626R2227) for the variants we currently handle.

**Comment by jar398** [comment]
Smasher code for doing this, for comparison:

https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/org/opentreeoflife/taxa/Taxon.java#L1191-L1206
