### ISSUE TITLE
When OTU mapping suggests another name...

### ISSUE THREAD

**Issue by hdliv** [OpenTreeOfLife/opentree#395]
Suggestion:

WHen OTU mapping suggests another name, it would be nice that it gives some context:

for example here

![screen shot 2014-07-28 at 3 03 29 pm](https://cloud.githubusercontent.com/assets/6361361/3725586/1f47a5cc-168a-11e4-8819-2d7985daee20.png)

It could be that the genus has been revised and I don't know, but I need to go out and look for it.  Maybe some sort of contexts like Genus species (in blablabla)

**Comment by jimallman** [comment]
Thanks, I'll look into this. This looks like a duplicate issue to #416 (and a special case of #460).

**Comment by kcranston** [comment]
Fixed with PR #861
