### ISSUE TITLE
mapping take a long time

### ISSUE THREAD

**Issue by hdliv** [OpenTreeOfLife/opentree#396]
mapping has been taking a while...is this normal now?

![screen shot 2014-07-29 at 10 56 47 am](https://cloud.githubusercontent.com/assets/6361361/3736782/e015bfa4-1730-11e4-800c-b21c3a343139.png)

**Comment by jimallman** [comment]
@josephwb asked (some time ago):
> I wonder, since this is in discussion, is everyone happy with the existing contexts? Do we need more? Should we get general input on this from curators?

See @hdliv 's request above:
> Can we do Amoebozoa instead of Amoebae. maybe i said the contraire before .

Should we solicit more input on this?

**Comment by jimallman** [comment]
Also, any thoughts about the grouped ("nested") context list as shown above? I don't recall if there was a decision made, or if this option was simply shelved waiting for comments.

**Comment by josephwb** [comment]
Can we close this? Mapping has been snappy for quite a while.

**Comment by hdliv** [comment]
yes of course.  close it

**Comment by josephwb** [comment]
:boom:
