### ISSUE TITLE
Add a "release page" for each version of the synthetic tree 

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#402]
This should offer basic information about a single version of the synthetic tree. Some ideas:
- "coverage" of the taxonomy (how many clades under synthesis)
- percentage of taxa from OT taxonomy that were included in synthesis
- percentage of OTUs mapped from all (included) source trees

Other suggestions welcome. @jimallman and @kcranston will work on designs for this page. This will incorporate @lcoghill's existing scripts that periodically gather metrics.

Add server-side requirements to https://github.com/OpenTreeOfLife/treemachine/issues/105.

**Comment by kcranston** [comment]
We now have a release page for each new version of the synthesis tree. Yay, us!
