### ISSUE TITLE
Ensure that imports are saved as supporting files

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#418]
The original Newick, NEXUS, NeXML, etc. files uploaded by the user ought to be saved as supporting files accessible in the uploads/ directory and in the UI via the 'Files' tab. If possible the original file name chosen by the curator should be preserved...

**Comment by jimallman** [comment]
> Need to do this retroactively as well. Will file a separate issue.

I can't find an open issue for this, but I've raised the same concern in #590 (more specifically [here](https://github.com/OpenTreeOfLife/opentree/issues/590#issuecomment-73946671)).
