### ISSUE TITLE
check that curator app is robust to absence of duplicateStudyIDs property in the study GET

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#426]
When the `alert-clogged-push` branch is merged to master (https://github.com/OpenTreeOfLife/phylesystem-api/pull/108) the duplicateStudyIDs property may be missing from the GET response. This should only happen if the call to OTI fails.
Looking at the Javascript, it looks like your code is robust to this. But could you confirm that?

**Comment by jimallman** [comment]
Yes, if the response doesn't have the expected `duplicateStudyIDs` property, the curation app [will set this to an empty array in the view model](https://github.com/OpenTreeOfLife/opentree/blob/7b46d253ee44c60ccded8355b9e030216fae109d/curator/static/js/study-editor.js#L738).
