### ISSUE TITLE
Synthesis tree names do not match those returned by TNRS

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#443]
Raised by @lukejharmon. For example, for ```tnrs/match_names``` a search might be:
```
curl -X POST http://devapi.opentreeoflife.org/v2/tnrs/match_names -H "content-type:application/json" -d '{"names":["Stellula calliope"], "context_name":"birds"}'
```
with result:
```json
{
  "governing_code" : "ICZN",
  "unambiguous_name_ids" : [ "Stellula calliope" ],
  "unmatched_name_ids" : [ ],
  "matched_name_ids" : [ "Stellula calliope" ],
  "context" : "Birds",
  "includes_deprecated_taxa" : false,
  "includes_dubious_names" : false,
  "includes_approximate_matches" : true,
  "taxonomy" : {
    "author" : "open tree of life project",
    "weburl" : "https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy",
    "source" : "ott2.8"
  },
  "results" : [ {
    "id" : "Stellula calliope",
    "matches" : [ {
      "is_deprecated" : false,
      "is_synonym" : false,
      "flags" : [ ],
      "search_string" : "stellula calliope",
      "score" : 1.0,
      "synonyms" : [ "Stellula calliope" ],
      "is_approximate_match" : false,
      "ot:ottId" : 536234,
      "matched_node_id" : 3502581,
      "rank" : "",
      "matched_name" : "Stellula calliope",
      "unique_name" : "Stellula calliope",
      "is_dubious" : false,
      "nomenclature_code" : "ICZN",
      "ot:ottTaxonName" : "Stellula calliope"
    } ]
  } ]
}
```
whereas a query to ```tree_of_life/induced_subtree```:
```
curl -X POST http://devapi.opentreeoflife.org/treemachine/ext/tree_of_life/graphdb/induced_subtree -H "content-type:application/json" -d '{"ott_ids":[536234, 267845, 666104]}'
```
gives the result:
```json
{
  "subtree" : "(Stellula_calliope_ott536234,(Dendroica_ott666104,Cinclus_ott267845));",
  "ott_ids_not_in_tree" : [ ],
  "ott_ids_not_in_graph" : [ ],
  "node_ids_not_in_graph" : [ ],
  "node_ids_not_in_tree" : [ ]
}
```
That is, TNRS gives ```"Stellula calliope"``` (spaces included) while ToL gives ```Stellula_calliope_ott536234``` (no spaces, and a trailing suffix). 

The use case is:
1) have a character/trait matrix for some taxa
2) search for matched names of taxa, get ottIds
3) use ottIds to get a subtree on which to do analyses from the graph DB
4) **problem:** names on returned tree do not match names returned from TNRS query (possibly applied to the character/trait matrix)

There are a number of ways to deal with this, but because it might be a common (ubiquitous?) problem, I thought I'd log it here for rumination.

One way to deal with this is just work with ottIds alone during analyses, as names can always be retrieved afterwards.

Alternatively, it could easily be possible to return trees from the synthesis graph DB without ottId suffixes (that is, names that match those from the TNRS exactly). I feel this option is not optimal because 1) ottIds are useful for disambiguation of homonyms, and 2) being of a standard format (```"_ott\d+"```), they are easily stripped out if desired.

There are probably a bunch more ways to deal with this effectively. I'm sure these approaches will emerge from the various projects being undertaken at the hackathon.

**Comment by josephwb** [comment]
I believe this is fixed.

**Comment by jimallman** [comment]
> I believe this is fixed.

I see that the original symptom remains (different names from the two original cURL calls). Are you saying (as others suggested above) that this difference is not really a problem, or that we're providing enough guidance that a careful API consumer can make sense of things?

**Comment by jar398** [comment]
The names *must* be different, for species at least, because spaces aren't
allowed in Newick labels.

And the OTT ids *must* be included because there may be homonyms and labels
must be unique.

So I think the tree_of_life behavior is both correct and desirable. The
application has to deal with it. It can parse out the OTT id and use it to
get the taxon name via another service, or it can decode the Newick label
quoting and underscores (hard, and runs the risk that there might have been
an underscore in the original).

Alternatively, it can get arguson format. Newick is really not up to the
job.

**Comment by jimallman** [comment]
Thanks, @jar398! Just wanted to be sure we aren't leaving any loose ends.
