### ISSUE TITLE
Link to treebase or Dryad when possible

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#445]
The metadata tab in the curator app should show the treebase id when there is one, or Dryad or figshare DOI when there is one of those. Or another data deposit DOI or URL if there is one.

If there is no Dryad or figshare ('data deposit') DOI or URL there should be a way to add one.

In addition, the treebase id or other data deposit URL, when there is one, should be available as a link from the bibliographic references list.

**Comment by jar398** [comment]
where does this one stand? I would like to close the Columbus Day milestone.

**Comment by jimallman** [comment]
All the described behavior is working now on production. One possible change: Did we discuss moving the "scold" messages from a popup (below) to inline text?

![screen shot 2015-01-23 at 12 53 51 pm](https://cloud.githubusercontent.com/assets/446375/5879652/f72c08ce-a2fe-11e4-8be1-6240d4857f97.png)

**Comment by jimallman** [comment]
Ah yes, #481 is the related issue (popup to inline text). So we can close this one if you like, and I'll put that one on the front burner.

**Comment by jar398** [comment]
Seems to be done
