### ISSUE TITLE
Any time a taxon name is displayed, give option to show more info about it

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#460]
Taxon names are displayed in various parts of the UI, not just in the tree browser. For example: while viewing a source tree, during OTU matching, and when choosing among alternatives in the TNRS. In each instance the user may have the question, what is this thing? It should be possible in each context to click on the name and see information about the taxon similar to (or beyond) what you see in the properties pane: NCBI/GBIF/etc links, OTT id, search-EOL link, maybe taxonomy lineage (not sure about lineage, it could be a lot of information). This could be either a popup or a separate page.

I'm not the only one who'd like to see it; I heard the request from at least one hackathon participant.

**Comment by jar398** [comment]
Another upvote: This feature (in OTU mapping) was suggested by an audience member in a presentation today at NESCent.

**Comment by kcranston** [comment]
Several upvotes for this at the SSB data sharing workshop.

**Comment by jar398** [comment]
A good, real example: Regulus in study pg_2015 - two options offered, and it was hard for the curator to figure out which one was correct.
In this case (and many others) showing the lineage, or some part of it, might be enough?

I should note that in the Regulus case, if the taxonomic context was All life when the ambiguity arose, then the bug is that the curator was not nudged strongly enough into selecting a taxonomic context.  On the other hand, if the context was Birds, we have a TNRS bug, in that a non-bird was offered as a homonym.  - But the fact that other fixes might be available in this case, doesn't negate the claim that showing taxon information in OTU mapping would probably be a good investment.

**Comment by jar398** [comment]
Mostly or entirely accomplished by PR #830
