### ISSUE TITLE
Treebase ids start with 'S'

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#484]
On the Add Study page I entered a treebase id that I found in an article: S14693. This id (with the 'S') is also known to Treebase (you can search on it, and when you do it shows up in the first column, with an 'S'). When I pressed Enter (after noticing that 'continue wasn't an option), I got "TreeBASE ID should be an integer."

I always thought the ids started with S. Could we maybe allow either variant, with or without the S, in this form?

**Comment by jimallman** [comment]
@jar398 , please take a look and close this if satisfied (or leave a comment).

**Comment by jar398** [comment]
works great on devtree.
