### ISSUE TITLE
Deletion should be accompanied by a comment

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#486]
... just like any other phylesystem commit.

**Comment by mtholder** [comment]
I've assigned it to me (bit swamped right now, so I won't make a time estimate)...

**Comment by mtholder** [comment]
Perhaps we should think about requiring an curator to put in the ID of the study that this study duplicates.

That is assuming that the only reason for deletion is duplicate studies.

If so, then the curator app could send a specially formatted commit message, and the phylesystem could store the info that it needs to redirect future requests for the study to the preserved duplicate. 

That feature would seem handy, but I'm not sure that it is worth the trouble. thoughts?

**Comment by jimallman** [comment]
> If so, then the curator app could send a specially formatted commit message, and the phylesystem could store the info that it needs to redirect future requests for the study to the preserved duplicate.

I'm not sure it's worth the extra effort. It seems easy enough to find the "real" study using oti, assuming you know what you're looking for. Hopefully the "duplicate study" notices are prominent enough that these don't stick around for long.

Incidentally, other possible reasons for study deletion include:
- kicking the tires on the curation app
- testing (rare on production, but it happens)
- :hankey: happens
