### ISSUE TITLE
Clicking on focal clade in study list current behavior not useful

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#487]
Seems like no matter which focal clade you pick from the focal clade column in the study list, all that happens is that the study list becomes empty.  If this is all that's going to happen the focal clade probably shouldn't be clickable. Probably the intent was to do something else.

Also the back button doesn't work to undo this action.

**Comment by jimallman** [comment]
Both symptoms have been fixed, closing this.
