### ISSUE TITLE
can we make curator/otu mapping / "modified for mapping" column more aggressive about fighting for width

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#501]
Making my browser window wider works fine.

But with a moderately sized window (half my 1920x1080 display), it gets so small that it is tough to compare it to the mapped text (see screenshot):
![screenshot from 2014-11-10 10 14 29](https://cloud.githubusercontent.com/assets/136067/4973448/655e7eb4-68ba-11e4-9ac4-675a11b71e0c.png)

**Comment by jimallman** [comment]
OK, I've modified this table to force more equitable column widths, as shown here in a pretty narrow browser window:

![screen shot 2015-01-02 at 12 53 27 am](https://cloud.githubusercontent.com/assets/446375/5594458/6d09144c-921a-11e4-9e40-0e6a4b38be2c.png)

Note that this is not ideal, but we're always going to hit a wall when the label text is very long.

**Comment by mtholder** [comment]
great. thanks.
