### ISSUE TITLE
uncheck select checkbox when a mapping is approved by a curator

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#505]
Currently stays checked even after approval

**Comment by jimallman** [comment]
True, the checkbox sticks around, but it's currently a no-op since the mapper will skip these OTUs. Meanwhile, it serves as a reminder of the "current batch" of OTUs the curator is working on. (Actual behavior will depend on the active OTU sort order.) I could go either way on this one..

**Comment by jimallman** [comment]
> Maybe being selected has no negative consequences, in which case it doesn't matter? I don't know. But is there some good UX reason to keep mapped OTUs selected?

So [my rationale above](https://github.com/OpenTreeOfLife/opentree/issues/505#issuecomment-68491031), about keeping track of the current "batch" of selected OTUs, doesn't seem very compelling given the trouble it's already caused you both. I'll go ahead and make this change.
