### ISSUE TITLE
we might want a separate category of OTUs that can be approved with one click

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#506]
Currently (if there are no homonyms or synonyms) we don't show the user any output to approve except for the new label. It is shown in red text.

This results in quite a bit of clicking for approval. Because we don't provide any info (other than the name) it is not clear why a curator would not want to accept a perfect match.

Perhaps we could (after mapping) sort the OTUs into two groups: 

the first group would only have OTUs in which the taxon name in OTT is case-insensitive equal to the modified for mapping name (or the original label if there were no modifications). We'd probably also want to strip the modified name of leading or trailing whitespace.  These mappings could show up in a different color and there would be a box to allow the user to approve them all.

The second group would show the current behavior (red text and one-by-one approval).

**Comment by jimallman** [comment]
I believe we have the desired behavior now, in the **Approve all and continue** button. This should immediately approve all unambiguous mappings (those with a single candidate) but leave multi-option "fuzzy matches" for closer attention.

Note that the cosmetic details described above (eg, "red text") may change if recent modifications are merged to master. Instead, there will be _one or more_ colored mapping candidates for each OTU, with clarification of synonyms, etc. shown in a rollover.

**Comment by mtholder** [comment]
cool. thanks.
