### ISSUE TITLE
Difficult to share/discuss curated studies without a simple ID

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#520]
_Email from @rgazis:_ 

The study number is difficult to find and can affect communication between curators and others. The study number/record should be better indicated. So the record of this study in the new curation tool database is  http://dx.doi.org/10.3767/003158510X494596 which corresponds to the DOI of the article. But if I am communicating with Stephen to suggest a set of tree for synthesis I will have to send this record? The tree number would be View tree 'Untitled (tree2412)' which appears when clicking on the tree file.

**Comment by jar398** [comment]
I know that the stock answer is that the study id is in the URL, but I
believe there will be many people like Romina who won't think to look there.

**Comment by kcranston** [comment]
The study id is also on the metadata tab. Assuming we can close this.
