### ISSUE TITLE
A study is lost, or never saved? (curation app)

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#527]
_Email from @rgazis:_ 

I have uploaded this study many times and it does not get stored, or recorded. I am not sure if there is a bug in this file or there is something wrong with the curation tool.

When does the system give you a deposit/record number? I have uploaded a study from tree base / selected focus clade, then click "save study" then log-out - and when I logged in again the study was gone, it does no appear in the list of studies I have uploaded. A warning should come up when your study has not been saved in the database. 

After uploading again the study and adding the DOI and mapping a couple of OTUs, the record seems to appear http://dx.doi.org/10.3852/14-076

BUT it disappears again…

The treebase number is S15569. The citation is “Thongklang, Naritsada, et al. "Morphological and molecular characterization of three Agaricus species from tropical Asia (Pakistan, Thailand) reveals a new group in section Xanthodermatei." Mycologia 106.6 (2014): 1220-1232.”

I stop curating the tree because I already lost 3 times the mapping I worked on. The study could not be recovered by my name, the authors name or the taxa of the focus clade.

**Comment by jimallman** [comment]
Sorry to hear you've having trouble with this study, @rgazis! Since you've provided its TreeBASE ID, I'll try to reproduce the problem...

I see [three(!) instances of this study in the phylesystem repo](https://github.com/OpenTreeOfLife/phylesystem-1/search?utf8=%E2%9C%93&q=dx.doi.org%2F10.3852%2F14-076), found by searching its DOI. But they don't appear in the [study list on the curation homepage](http://tree.opentreeoflife.org/curator) when I search by DOI or author.

So it looks like **oti** (our study+tree indexing tool) is not being updated properly. It looks like [a recent fix for this failure](https://github.com/OpenTreeOfLife/phylesystem-api/pull/138) is still not running on the production servers. I'll follow up with @jar398 about deploying recent bug fixes ASAP.

In the meantime, you can reach all three instances of this study at the following URLs:
 * http://tree.opentreeoflife.org/curator/study/view/ot_221
 * http://tree.opentreeoflife.org/curator/study/view/ot_225
 * http://tree.opentreeoflife.org/curator/study/view/ot_226

Please continue working with whichever version is most complete, and delete the others.

**Comment by rgazis** [comment]
Hi Jim

I was able to access the 3 links and kept the first record. But I was not able to access the study again (from the list of study at the first page of the curation tool) by searching the DOI link http://dx.doi.org/10.3852/14-076 or the author's name. 

Also, is "ot_221" the record for this study in the new curation tool database?

Thanks,

Romina

**Comment by jimallman** [comment]
The study list on the curation home page needs a minor fix. Until then, new studies will not appear in the list, sorry. This should be working as expected soon.

> Also, is "ot_221" the record for this study in the new curation tool database?

Yes, that is its phylesystem ID. We have assumed that these "internal" IDs would not be interesting to most users, so we haven't done much to "highlight" them like a TreeBASE ID.

The study's URL (in the curation app) is probably the best way to share these. In this case:
http://tree.opentreeoflife.org/curator/study/view/ot_221

**Comment by rgazis** [comment]
Jim, where does the phylesystem ID "i.e., ott_221" can be found? 
Thanks!
R

**Comment by rgazis** [comment]
I just saw that this number appears under history, but only for the newly uploaded studies right? the ones that have been transferred from phylografter do not have an ot_#?

**Comment by jimallman** [comment]
> Jim, where does the phylesystem ID "i.e., ott_221" can be found? 

Check the URL in your browser's address bar. When you share the current URL, it will take someone to the same tab and tree view (if any).

**Comment by jimallman** [comment]
> the ones that have been transferred from phylografter do not have an ot_#?

Correct, each study ID has a "prefix" that explains where it was originally created:
 - **pg_####** for Phylografter
 - **ot_####** for the OpenTree curation tool (or API)
 - ...and others that may appear over time.

**Comment by jimallman** [comment]
This should have been resolved by fixes to laggy **oti** updates.
