### ISSUE TITLE
error creating a new study

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#530]
When trying to upload new study from Treebase..

"Sorry, there was an error creating this study. (No more information is available.)"

This is the info

treebase S10351
Rees, Bettye J., et al. "Morphological and molecular data for Australian Hebeloma species do not support the generic status of Anamika." Mycologia 105.4 (2013): 1043-1058.

Thanks,

Romina

**Comment by kcranston** [comment]
When I search treebase, I can't find this study. Do you have a link for the
study in treebase?

On Wed, Jan 7, 2015 at 12:05 PM, rgazis <notifications@github.com> wrote:

> When trying to upload new study from Treebase..
>
> "Sorry, there was an error creating this study. (No more information is
> available.)"
>
> This is the info
>
> treebase S10351
> Rees, Bettye J., et al. "Morphological and molecular data for Australian
> Hebeloma species do not support the generic status of Anamika." Mycologia
> 105.4 (2013): 1043-1058.
>
> Thanks,
>
> Romina
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTreeOfLife/opentree/issues/530>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~
karen.cranston@gmail.com
@kcranstn
~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rgazis** [comment]
http://purl.org/phylo/treebase/phylows/study/TB2:S10351

but you are right, the study is not there anymore..I did see it when I compiled my list. The author might have retrieved it……sorry!

R
