### ISSUE TITLE
internal server error from to_nexson when no trees are found in a file.

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#541]

**Comment by mtholder** [comment]
line note at line 484 of https://github.com/OpenTreeOfLife/opentree/commit/076d214d2d80a13531bd55ef74ba87fa6e7f53c9#diff-a0f7583c04be2b59a48dc52bfb720819
appears to highlight the cause.

**Comment by jimallman** [comment]
To clarify, this is [the line note mentioned above](https://github.com/OpenTreeOfLife/opentree/commit/076d214d2d80a13531bd55ef74ba87fa6e7f53c9#commitcomment-9230892):
> tree_id will be undefined if there were no trees in the file.

Should be an easy fix. Thanks!

**Comment by jimallman** [comment]
OK, this is working for me with normal and tree-less NEXUS files. Available for review on **devtree**.

**Comment by jimallman** [comment]
@mtholder, I've [added a tree-less NEXUS file and test](https://github.com/OpenTreeOfLife/opentree/commit/7b358d66d0eefd3091d587bd7087b995f48c822d) to this branch. Please take a look when you have a moment and let me know if this looks OK.
