### ISSUE TITLE
boxes obscure possible mappings

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#544]
The mapping boxes on the right can cover up the 'possible mappings' choices in the third column. This is not good, since the possible mappings are more important information.
![untitled](https://cloud.githubusercontent.com/assets/2035858/5709100/eaf4d4fc-9a64-11e4-8778-e42922cb41a5.png)

**Comment by jimallman** [comment]
The simple fix above is available for review on **devtree**.

**Comment by jimallman** [comment]
Yes (see above). This was merged in our last PR review (while you were called away, I think).
