### ISSUE TITLE
Maybe change question mark in tree browser...

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#549]
to the international 'information' icon (the slanty lower case 'i')

**Comment by jimallman** [comment]
NOTE that this will require updates to some graphics in the tree-viewer legend.

**Comment by jimallman** [comment]
Checking into the relevant ISO standards:
- ISO 7001, Graphical symbols – Public information symbols 
- ISO 22727, Graphical symbols – Creation and design of public information symbols – Requirements

**Comment by kcranston** [comment]
http://commons.wikimedia.org/wiki/File:Information_icon.svg ?

**Comment by jimallman** [comment]
From the examples i've found so far, this shows the ISO "info" symbol in its simplest form:
http://commons.wikimedia.org/wiki/Category:ISO_7001_icons

I think the letter form is recognizable enough, even as red-on-white. Though I could switch all the highlights to white-on-blue... hmm, will experiment.

![image](https://cloud.githubusercontent.com/assets/446375/5767408/c687f8dc-9cd6-11e4-823f-208a8aa87c8b.png)

**Comment by jar398** [comment]
Implemented, see #559

**Comment by jimallman** [comment]
Re-opening as a reminder to replace the stale (red "?") graphics in the popup legend.

**Comment by jimallman** [comment]
This is available now on **devtree** (might require clearing cache to see the new images):

![screen shot 2015-01-28 at 4 13 54 pm](https://cloud.githubusercontent.com/assets/446375/5947088/b0e67f58-a708-11e4-91e7-4e1162ad24db.png)

**Comment by jar398** [comment]
Seems to be finished? #559

**Comment by jimallman** [comment]
Agreed, thanks for closing this.
