### ISSUE TITLE
Incomplete SSL cert chain?

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#553]
We've had isolated reports of SSL problems on the production domains, and seen some indications that the SSL cert chain is incomplete. Some possible clues here:

https://www.ssllabs.com/ssltest/analyze.html?d=tree.opentreeoflife.org&hideResults=on&latest
https://www.ssllabs.com/ssltest/analyze.html?d=api.opentreeoflife.org&hideResults=on&latest

And a possibly helpful tool to remedy this:
https://github.com/zakjan/cert-chain-resolver

I'll work with @jar398 to see if we've missing something in our deployment scripts.

**Comment by jimallman** [comment]
OK, I've tested the cert-chain-resolver script above, and it does create a nice .pem that concatenates all certificates in the chain. As a test, I've installed this on **api.opentreeoflife.org** and modified `sites-enabled/001-opentree-ssl` to recognize it by adding a `SSLCertificateChainFile` directive [as described in the Apache docs](http://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslcertificatechainfile):
```config
    SSLEngine on
    SSLCertificateFile    /etc/ssl/certs/opentree/STAR_opentreeoflife_org.crt
    SSLCertificateChainFile    /etc/ssl/certs/opentree/STAR_opentreeoflife_org.pem
    SSLCertificateKeyFile /etc/ssl/private/opentreeoflife.org.key
```
This shows up as a complete chain in the SSLLabs test above; compare to the results for **tree.opentreeoflife.org** to see the improvement.

The alternative to this combined .pem is probably to use Apache's `SSLCACertificatePath` directive (described here) to point to all the certs in our bundle (STAR_opentreeoflife_org.zip). I'll defer to @jar398 for which path he'd rather take, but I can work on these changes once a decision has been made.

**Comment by jimallman** [comment]
A quick note: This change has [already fixed a glaring problem](https://github.com/OpenTreeOfLife/phylesystem-1/issues/4#issuecomment-71295946), the inability to push recent study changes to GitHub.

@jar398 , it seems a combined (multi-cert) file is Comodo's recommended solution for Apache:

- https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/637/37/certificate-installation-apache--mod_ssl
- https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/620/1/which-is-root-which-is-intermediate
- https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/643/17/

For what it's worth, I believe the [`resolve.sh` script linked above](https://github.com/zakjan/cert-chain-resolver) is a cleaner tool to build the combined .pem file.

**Comment by jimallman** [comment]
While we're at it, we should also look into the other issues and vulnerabilities found by the SSLLabs analyzer linked above.

**Comment by jimallman** [comment]
OK, I've patched the POODLE vulnerability on **api.opentreeoflife.org**, see [our improved SSLLabs score](https://www.ssllabs.com/ssltest/analyze.html?d=api.opentreeoflife.org).

The fix is to `sites-enabled/ssl.conf`, as [described here](https://zmap.io/sslv3/servers.html#apache). The new configuration setting is specific to Apache v2.2.22 and earlier:
```config
 # enable only secure protocols: SSLv3 and TLSv1, but not SSLv2
 ## jimA: TEST of POODLE countermeasures:
 # SSLProtocol all -SSLv2
 SSLProtocol TLSv1
```
TLSv1 is newer and currently considered secure. Note that this change does drop Internet Explorer 6 from our supported browsers. :cry:

I'll incorporate this change into our deployment scripts, then test on **devapi** and **devtree**.

**Comment by jimallman** [comment]
> While we're at it, we should also look into the other issues and vulnerabilities found by the SSLLabs analyzer linked above.

I've patched for the POODLE vulnerability (commit 9774d9960215c7fc8ef5b9ce645d92f572d2bede) in branch `apache-ssl-fixes`. Will keep this branch open for the cert-chain fix, once we've settled on a remedy.

**Comment by jimallman** [comment]
It looks like we have the [cipher support in our current openssl] (https://www.openssl.org/docs/apps/ciphers.html#tls_v1_2_cipher_suites) to support **TLSv1.2**, which is recommended for stronger encryption.
```bash
$ openssl version
OpenSSL 1.0.1e 11 Feb 2013

$ openssl ciphers -v 'ALL:!ADH:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP'
ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD
ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(256) Mac=AEAD
ECDHE-RSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA384
ECDHE-ECDSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA384
ECDHE-RSA-AES256-SHA    SSLv3 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA1
ECDHE-ECDSA-AES256-SHA  SSLv3 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA1
SRP-DSS-AES-256-CBC-SHA SSLv3 Kx=SRP      Au=DSS  Enc=AES(256)  Mac=SHA1
SRP-RSA-AES-256-CBC-SHA SSLv3 Kx=SRP      Au=RSA  Enc=AES(256)  Mac=SHA1
SRP-AES-256-CBC-SHA     SSLv3 Kx=SRP      Au=SRP  Enc=AES(256)  Mac=SHA1
DHE-DSS-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=DSS  Enc=AESGCM(256) Mac=AEAD
... and many more ...
```
The cipher string above `ALL:!ADH:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP` is [the recommended default in the Apache docs](http://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslciphersuite), but registers as insecure in my tests. 

I'll keep testing with some of the [recommended SSLCipherSuite options on the Mozilla site](https://wiki.mozilla.org/Security/Server_Side_TLS), which offer a series of trade-offs in security vs. compatibility with older browsers.

**Comment by jimallman** [comment]
Tried lots of SSLCipherSuite values, and none scored particularly better than Apache 2.2.22's default:
```
SSLCipherSuite HIGH:MEDIUM:!aNULL:!MD5
```
Most importantly, none of them seems to provide real TLSv1.2 support in my tests. So I'm leaving this for now, but we might want to take a closer look down the road.

**Comment by jimallman** [comment]
Note that I revised the apache config settings on production **api** to point to the same .pem file in both the SSLCertificateFile and SSLCertificateChainFile directives, as shown below. This was in response to a warning from [Symantec's SSL test tool](https://ssltools.websecurity.symantec.com/checker/views/certCheck.jsp) that warned about multiple certs with the same common name (*.opentreeoflife.org).
```config
    SSLEngine on
    SSLCertificateFile    /etc/ssl/certs/opentree/STAR_opentreeoflife_org.crt
    SSLCertificateChainFile    /etc/ssl/certs/opentree/STAR_opentreeoflife_org.pem
    SSLCertificateKeyFile /etc/ssl/private/opentreeoflife.org.key
```

**Comment by mtholder** [comment]
Can we fix tree.opentreeoflife.org as well? (sorry)
If I try to grab a supplemental file:

     curl 'https://tree.opentreeoflife.org/curator/default/to_nexson?output=input&uploadId=ub89c4da7-cf9b-4b05-af39-bb50a1a25f7e'

I get:

    curl: (60) SSL certificate problem: unable to get local issuer certificate
    More details here: http://curl.haxx.se/docs/sslcerts.html

    curl performs SSL certificate verification by default, using a "bundle"
     of Certificate Authority (CA) public keys (CA certs). If the default
     bundle file isn't adequate, you can specify an alternate file
     using the --cacert option.
    If this HTTPS server uses a certificate signed by a CA represented in
     the bundle, the certificate verification probably failed due to a
     problem with the certificate (it might be expired, or the name might
     not match the domain name in the URL).
    If you'd like to turn off curl's verification of the certificate, use
     the -k (or --insecure) option.

**Comment by jimallman** [comment]
> Can we fix tree.opentreeoflife.org as well?

OK, I've matched the modifications made to **api.opentreeoflife.org**. Please try again!

**Comment by mtholder** [comment]
works. Thanks!

**Comment by jimallman** [comment]
As [discussed on IRC](http://irclog.perlgeek.de/opentreeoflife/2014-06-10#i_8851435), I've added the **public** SSL certs to version control, along with the `resolve.sh` script and a README file that describes how to build a self-contained `.pem` file with all intermediate certs.

**Comment by jimallman** [comment]
In commit b461657c90a439acc398076f9e1cc416cb3556f2, I've added a note (in the deployment README) to manually install the new `.pem` file (along with the private key) to enable secure web connections.

**Comment by jimallman** [comment]
These changes are working now on **devapi** and **devtree**. (I manually placed the `.pem` file on each box beforehand, then used the deployment tools normally.) The SSLLabs test shows complete certificate chains and no POODLE vulnerability.

**Comment by jimallman** [comment]
Closing this (long resolved) issue.
