### ISSUE TITLE
Inconsistent labeling of 'ot:curatedType' in curation UI

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#554]
It looks like the curation UI is inconsistent in its labeling. Here are a tree's properties when we're editing:

![screen shot 2015-01-19 at 9 34 46 am](https://cloud.githubusercontent.com/assets/446375/5802002/c01339c2-9fbe-11e4-9408-69abb2975143.png)

...and here's the same tree when we're just viewing the study (note the label for this field!):

![screen shot 2015-01-19 at 9 35 04 am](https://cloud.githubusercontent.com/assets/446375/5802004/c8a2eb3c-9fbe-11e4-88be-4875d647a35a.png)

Which label is correct? See the related (ongoing) discussion in #552...

**Comment by jar398** [comment]
'tree type' doesn't make sense as a field label. I vote for 'inference method'.

**Comment by kcranston** [comment]
I think 'inference type' and 'tree type' are two different concepts. 

* inference type = {maximum likelihood, maximum parsimony, bayesian, neighbour-joining}
* tree type is less straightforward. This could be {gene tree, species tree, supertree} or {ML tree, consensus tree, MAP tree}

More discussion needed.
