### ISSUE TITLE
Better labelling of deleted / duplicated studies in curator

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#557]
Study [pg_411](https://tree.opentreeoflife.org/curator/study/view/pg_411) lists study [pg_405](https://tree.opentreeoflife.org/curator/study/view/pg_405) as a duplicate, but clicking on the link for 405 gives an error, and no indication that it once existed and is now deleted. Probably need some conversation about how to indicate the primary version when there are duplicate studies and how to show deleted studies. Should deleted and non-primary dups be editable?

**Comment by jimallman** [comment]
@kcranston, I'm having trouble reproducing your example above. That is, I can follow the link to pg_405 and it shows up as expected.

The problem as described should not occur if **oti** is up to date. We test for duplicates by comparing studies listed there, and a deleted study will soon disappear from the index. (Just confirmed this on production, using a couple of test studies.)

Please let me know if you see the above symptoms again, as it points to some kind of lagging in **oti**. Meanwhile, I'm marking this as "wontfix" unless I can reproduce it.

**Comment by kcranston** [comment]
Yup - seems to be a lag in oti, because I no longer see the error. Closing.
