### ISSUE TITLE
failure to load node in tree browser.

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#563]
An TypeError exception keeps the ajaxSuccess callback on drawtree from executing. So I just get the spinner.

See https://devtree.opentreeoflife.org/opentree/argus/otol.draft.22@3843727

int `treeview.js` the function buildNodeNameFromTreeData hits the return null branch of code:

    // we'll need to build a name from visible children and/or their descendantNamesList
    if (node.children === undefined || node.children.length < 2) {
        // we need at least two names to do this TODO: CONFIRM
        return null;
    }

This causes an error in the recursive call a few lines later because `firstChildName` is null:

    var firstChildName = buildNodeNameFromTreeData(node.children[0]);
    var nameParts = firstChildName.split(compoundNodeNameDelimiter);

Note that I found this while walking back from the node mentioned in https://github.com/OpenTreeOfLife/treemachine/issues/151#issuecomment-71451784

This appears to be associated with a case when an unnamed node has only one child.  I'd like such nodes to be suppressed from the graph (that is the subject of the treemachine issue), but we should  make the frontend robust to this just in case they keep cropping up.

**Comment by jimallman** [comment]
I have a quick fix in place, with results like this for the URL above:
![screen shot 2015-01-29 at 12 23 51 am](https://cloud.githubusercontent.com/assets/446375/5952831/4966dd06-a74d-11e4-8dc8-09cb7a0b4525.png)
A node with a single child claims the same label for itself. This looks goofy, but I think it accurately reflects a goofy tree.

**Comment by jimallman** [comment]
Working now on **devtree**.

**Comment by mtholder** [comment]
thanks, that is very helpful.
