### ISSUE TITLE
tree browser: cannot click on edge info - I think that the presence of text is hiding inhibiting the mouse-over trigger

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#576]
For example, when I load:

https://tree.opentreeoflife.org/opentree/argus/otol.draft.22@3573046/Menispermoideae

(on firefox or chrome) I can move over the branches in the big basal polytomy and see the pretty (i) icon pop up for edge info on most of them.

But in the branches that are tightly packed and have labels (e.g in the Haematocarpus part Elephantomene) my cursor stays in the text grabbing bar icon. It doesn't become a pointer and the blue (i) icon does not appear on the edge. On chrome I can sometimes get the Elephantomene edge to light up, but not the one below it.

My suggestion (on issue https://github.com/OpenTreeOfLife/opentree/issues/573) yesterday to supply both "edge info" and "node info" on clicks at the node (and get rid of the edge click target) might be the easiest way to deal with this.

**Comment by jimallman** [comment]
> My suggestion (on issue #573) yesterday to supply both "edge info" and "node info" on clicks at the node (and get rid of the edge click target) might be the easiest way to deal with this.

Just to repeat my comment from #573: 
> Note that this is the current behavior, i.e., you can click either trigger and get node+edge information in the property inspector. Only the highlighted border changes!

Nonetheless, I agree that it's annoying. If there's no "new" info to be found in edge vs. node, perhaps it's better to omit the edge rollovers for now and re-introduce them if we have something distinct to show from the edge. But I can probably come up with some layering magic in argus to clear up the original issue (label text occluding rollover targets).

**Comment by jar398** [comment]
I think eliminating the edge info / node info distinction would make sense
if a mouseover highlighted both the node and its incoming edge.

I do think the current design, while terribly rational, is probably overly
complex, and confusing to visitors to the site.

**Comment by mtholder** [comment]
ooh. I like the idea of rolling over the edge or node bringing up the same clickable (i) icon. I agree that it would simplify the UI.  That is better than just disabling the mouse over on the edge (as I suggested on the other issue).

**Comment by jimallman** [comment]
Agreed, I'll make a single "lollipop" shaped highlight that covers both node and edge, with just one "i" on the node. If the edge is obscured, hopefully they'll think to mouse over the node.

**Comment by jimallman** [comment]
For now, I'll keep the borders that distinguish node vs. edge properties (in the property inspector), but always gray -- since we're using a single highlight for both, there's no point in a red border (which should probably have become blue in the latest revision, but whatevs).

**Comment by jimallman** [comment]
OK, the combined node+edge highlight is working now on **devtree** (along with some other misc. argus bug fixes)

**Comment by kcranston** [comment]
Nice! I like it.

On Mon, Feb 2, 2015 at 5:14 PM, Jim Allman <notifications@github.com> wrote:

> OK, the combined node+edge highlight is working now on *devtree* (along
> with some other misc. argus bug fixes)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTreeOfLife/opentree/issues/576#issuecomment-72549840>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~
karen.cranston@gmail.com
@kcranstn
~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jimallman** [comment]
I've updated the tree-view legend in master branch. Closing this now.
