### ISSUE TITLE
Clicking RETURN in tags input fires DOI lookup

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#589]
Possibly return key is being intercepted by a FORM?

**Comment by jimallman** [comment]
Check all tabs for weirdness when clicking Return key!

**Comment by jar398** [comment]
It's not just tags, it's the DOI/URL box itself. If you enter a URL in that
box it fires up the DOI lookup popup. That's not right...

**Comment by jimallman** [comment]
@jar398, this fix was so tiny (and without side effects) that I've pushed it to master. Hope that's OK.

**Comment by jimallman** [comment]
A bit of background [here](http://stackoverflow.com/questions/12325066/button-click-event-fires-when-pressing-enter-key-in-different-input-no-forms). As I guessed, this is related to browser behavior that attempts to process and submit a form when the ENTER key is pressed. 

Apparently, most browsers treat `button` elements the same as `submit` elements by default. Setting `type="button"` makes it clear that this is some-other-kind-of-button and should not be "clicked" to submit the form. (In another interesting browser quirk, sometimes an eligible button will be clicked even if the `form` doesn't exist!)
