### ISSUE TITLE
Show 'supported by' study list for selected node

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#599]
Currently the 'supported by' information is shown only when you click on a blue-i icon. I wonder if it would help to show this information for the selected node (the one you last clicked on) by default. This might be a help to people who don't think or don't know to do the blue-i click. It just happened to me that I was expecting to see a study and it took me a while to realize the study info was missing because I didn't do blue-i.

Low priority.

**Comment by jimallman** [comment]
This is a problem in the current arguson, which doesn't include support information for the target (clicked) node, nor for the "root ward" nodes on the left. This is discussed more in #627

**Comment by josephwb** [comment]
Fixed on the treemachine side as of 7e3525c6cf9b6aa4c1e5ad4438c98e03783b579f.

**Comment by jar398** [comment]
Addressed by #637, right?

**Comment by jimallman** [comment]
Yes, we should now see consistent supporting information for the target (selected) node and its visible ancestors.
