### ISSUE TITLE
Wildly different results in synth-tree view without History support

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#608]
https://tree.opentreeoflife.org/opentree/argus/ottol@81461/Aves

This URL gives one (correct) result when History is enabled in Chrome, and a completely different result when it's disabled using Preferences > Advaned Settings > Privacy > Content settings ... > **Block sites from setting any data**

**Comment by kcranston** [comment]
It is not the history settings, but cookie settings. I can reproduce the change in behaviour when I select / unselect "Block sites from setting any data".

**Comment by jimallman** [comment]
Understood (see my note above). But the side effect that matters here is that it disables support for the HTML5 History API ([browser session history](https://html.spec.whatwg.org/multipage/browsers.html#history)), which changes some [Javascript behavior in the curation app](https://github.com/OpenTreeOfLife/opentree/blob/8f9cbb1f9fa91e39cbb6cea4a5ff427b7718b3cc/webapp/static/js/treeview.js#L249-L270).

**Comment by kcranston** [comment]
Whoops. I skimmed over the latter parts. ;)

**Comment by jimallman** [comment]
This should be fixed now on **devtree**. I've refactored the code for handling inbound URLs and jumps to new nodes within the tree viewer. We should have consistent results now even when the History feature is enabled, with the sole exception that the initial URL will stay in the address bar (and of course, the Back/Forward buttons won't reflect movement from node to node).

@kcranston, please take a look when you have a moment.
