### ISSUE TITLE
Only show profile pages for GitHub users participating in OpenTree

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#612]
Currently we show a page for any user on GitHub, with a note if they're not active in OpenTree. Instead, we should attempt to gather their activity and (finding none) return a 404 or explanation that they're not in the system.

Alternately, we could maintain a list of active participants. This would support a "user search" tool (by name or userid), which would be nice. A user would be added if they "participate" by:

 - curating studies (we search oti for `ot:curatorName` values)
 - commenting on the synthetic tree (we scan the `feedback` repo using GitHub API)
 - **COMING SOON**: building tree collections (we'll presumably use GitHub API)

**Comment by kcranston** [comment]
+1 for the list of active participants

**Comment by jimallman** [comment]
Hijacking this issue (since it's already kind of broad) to discuss another related request, to make it more obvious that the user "nick" on our profile page links to a GitHub profile, and that making changes in GitHub is the way to personalize your curator profile. 

Regarding the nick hyperlink, I've tried a few different ways to make the GitHub connection more explicit (the last reflects [the current 'support-tree-collections' branch](https://github.com/OpenTreeOfLife/opentree/tree/support-tree-collections)).

_Adding "on GitHub" to the current page title:_
<img width="782" alt="gh-link-a" src="https://cloud.githubusercontent.com/assets/446375/9974091/8d1dd0e0-5e4f-11e5-8ce0-8dd59e7ea37b.png">

_Using the well-known GitHub mark instead (with rollover hint):_
<img width="782" alt="gh-link-b" src="https://cloud.githubusercontent.com/assets/446375/9974090/8d0dbfc0-5e4f-11e5-9fd3-e492d9e66a7b.png">

_A half-size GitHub mark seems more harmonious:_
<img width="782" alt="gh-link-c" src="https://cloud.githubusercontent.com/assets/446375/9974088/8d07d088-5e4f-11e5-8990-517185e46425.png">

_Can we dispense with the parentheses at this point?_
<img width="782" alt="gh-link-d" src="https://cloud.githubusercontent.com/assets/446375/9974089/8d093ed2-5e4f-11e5-8880-c5e1134b2582.png">

_I prefer this leading "badge", like the "@" before a twitter handle:_
<img width="782" alt="gh-link-e" src="https://cloud.githubusercontent.com/assets/446375/9974087/8d01be1e-5e4f-11e5-92a7-7b8030c8172d.png">

The new **Edit** button shown above will only appear when a logged-in user is looking at **their own** profile page. Clicking this shows a confirmation box that explains what to do on GitHub, then opens its profile page in another window. @kcranston, does this address your concerns?

<img width="445" alt="screen shot 2015-09-18 at 9 57 27 pm" src="https://cloud.githubusercontent.com/assets/446375/9974111/522c8214-5e50-11e5-8234-24a3fa4f706a.png">

**Comment by jimallman** [comment]
I just found this early suggestion from @kcranston, which is more straightforward at the expense of hiding their GitHub userid. Thoughts?

<img width="636" alt="screen shot 2015-09-19 at 12 00 19 am" src="https://cloud.githubusercontent.com/assets/446375/9974536/92276382-5e61-11e5-86b7-07a675e5672b.png">

**Comment by kcranston** [comment]
I like your first mockup (with github username and spelling out 'github').
The logo may not be familiar to this community. Also like the popup window.

Thanks!

**Comment by jimallman** [comment]
I've incorporated the chosen design in 655d3f1fdb0083e31fbad395de430e90d1e725aa.

**Comment by jimallman** [comment]
Closing this after moving the searchable active-user list to a new enhancement issue #789.
