### ISSUE TITLE
Define a JSON "schema" for sharable tree collections

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#616]
Here's a sketch for collection JSON, with notes inline. (Apologies in advance for any biological nonsense here.) This incorporates most of the desired features in our discussions to date:
 - storage in git (here I assume a single `collections` repo on GitHub)
 - clear "ownership" so the creator can act as a gatekeeper for proposed changes
 - easy "forking" when desired (simply copy JSON from the creator's repo folder)
 - keeping decisions (`INCLUDE`, `EXCLUDE`, `UNDECIDED`) and a rationale for each tree
 - keeping one or more relevant queries, which might include automatic "agents" 

N.B. The full JSON is repeated below without interruption.

```javascript
{
    "url": "https://raw.githubusercontent.com/OpenTreeOfLife/collections/jimallman/trees-about-bees.json",
```

This URL serves as a unique ID for each collection.

```javascript
    "name": "Trees about bees",
    "description": "We're gathering these with an eye toward local synthesis in Anthophila (Apoidea). Contributions welcome!",
    "creator": {"login": "jimallman", "name": "Jim Allman"},
```

The creator "owns" the collection and can reject proposed changes. We include both their GitHub userid (for clarity) and name (for easy display).

```javascript
    "contributors": [
        {"login": "pmidford2", "name": "Peter Midford"},
        {"login": "kcranston", "name": "Karen Cranston"}
    ],
```

This is simply a record of other users whose edits have been accepted by the creator, similar to how curators accumulate in a Nexson document.

```javascript
    "decisions": [
        {
            "name": "Andrenidae from Foster, 2002", 
            "studyID": "ot_23532", 
            "treeID": "tree9870",
            "decision": "INCLUDED",
            "comments": "Lots of good analysis here!"
        }, 
        {
            "name": "Apidae from Winkle, 1998", 
            "studyID": "ot_12345", 
            "treeID": "tree999",
            "decision": "EXCLUDED",
            "comments": "Questionable methods and major gaps. Let's not use this."
        }, 
        {
            "name": "Colletidae gene tree (also Winkle)", 
            "studyID": "ot_12345", 
            "treeID": "tree888",
            "decision": "INCLUDED",
            "comments": "This should tie together some loose ends."
        }, 
        {
            "name": "Megachilidae supertree", 
            "studyID": "ot_2222", 
            "treeID": "tree7777",
            "decision": "UNDECIDED",
            "comments": "Intriguing! Waiting for more information from authors..."
        }, 
        {
            "name": "A. mellifera supertree #2", 
            "studyID": "ot_2222", 
            "treeID": "tree7778",
            "decision": "UNDECIDED",
            "comments": "Added by automatic query 'Harvest recent Apis mellifera'"
        }
    ]
```

This decision list is the heart of the collection. It's an ordered collection of trees that have been included in the collection, along with the rationale for each. Note that we also record trees that have been excluded for any reason, and others waiting for a final decision. This might be due to pending input from outside experts, or because a tree has been added by an automated query.

```javascript
    "queries": [
        {
            "name": "Harvest recent Apis mellifera",
            "automatic": true,
            "queryType": "study",
            "filters": [
                {
                    "property": "ot:publicationDate",
                    "test": "GREATER THAN",
                    "value": "2013"
                },
                {
                    "property": "ot:focalClade",
                    "test": "WITHIN CLADE",
                    "value": "Apis mellifera",
                }
            ]
        },
        {
            "name": "Find maximum-likelihood trees",
            "automatic": false,
            "queryType": "tree",
            "filters": [
                {
                    "property": "ot:inferenceMethod",
                    "test": "EXACT MATCH",
                    "value": "maximum likelihood"
                }
            ]
        }
    ],
}
```

Stored queries will use oti to find and add likely candidate trees. These can be manual (available to select and run on demand) or automatic, in which case they'd run whenever a collection is opened, or even by a periodic service.

#### Here's the entire collection JSON without interruptions:
```javascript
{
    "url": "https://raw.githubusercontent.com/OpenTreeOfLife/collections/jimallman/trees-about-bees.json",
    "name": "Trees about bees",
    "description": "We're gathering these with an eye toward local synthesis in Anthophila (Apoidea). Contributions welcome!",
    "creator": {"login": "jimallman", "name": "Jim Allman"},
    "contributors": [
        {"login": "pmidford2", "name": "Peter Midford"},
        {"login": "kcranston", "name": "Karen Cranston"}
    ],
    "decisions": [
        {
            "name": "Andrenidae from Foster, 2002", 
            "studyID": "ot_23532", 
            "treeID": "tree9870",
            "decision": "INCLUDED",
            "comments": "Lots of good analysis here!"
        }, 
        {
            "name": "Apidae from Winkle, 1998", 
            "studyID": "ot_12345", 
            "treeID": "tree999",
            "decision": "EXCLUDED",
            "comments": "Questionable methods and major gaps. Let's not use this."
        }, 
        {
            "name": "Colletidae gene tree (also Winkle)", 
            "studyID": "ot_12345", 
            "treeID": "tree888",
            "decision": "INCLUDED",
            "comments": "This should tie together some loose ends."
        }, 
        {
            "name": "Megachilidae supertree", 
            "studyID": "ot_2222", 
            "treeID": "tree7777",
            "decision": "UNDECIDED",
            "comments": "Intriguing! Waiting for more information from authors..."
        }, 
        {
            "name": "A. mellifera supertree #2", 
            "studyID": "ot_2222", 
            "treeID": "tree7778",
            "decision": "UNDECIDED",
            "comments": "Added by automatic query 'Harvest recent Apis mellifera'"
        }
    ]
    "queries": [
        {
            "name": "Harvest recent Apis mellifera",
            "automatic": true,
            "queryType": "study",
            "filters": [
                {
                    "property": "ot:publicationDate",
                    "test": "GREATER THAN",
                    "value": "2013"
                },
                {
                    "property": "ot:focalClade",
                    "test": "WITHIN CLADE",
                    "value": "Apis mellifera",
                }
            ]
        },
        {
            "name": "Find maximum-likelihood trees",
            "automatic": false,
            "queryType": "tree",
            "filters": [
                {
                    "property": "ot:inferenceMethod",
                    "test": "EXACT MATCH",
                    "value": "maximum likelihood"
                }
            ]
        }
    ],
}
``` 
Comments and questions welcome!

**Comment by kcranston** [comment]
Couple of comments: 

* this seems to indicate that the IDs for collections are strings ("trees-about-bees"). That seems odd. I'd rather have a unique identifier and a name string
* for the user identification, can we use 'username' rather than 'login'? Matches GitHub, then (which is where this info comes from, ultimately)
* it seems strange to have a collection not contain a object called `trees` or `treelist`. What about a structure like this:

```javascript
''trees'': [
   {"included": [
       { 
          "study": "studyID",
          "tree":"treeID"
       }
   ]
  }
 { "excluded": [
       { 
          "study": "studyID",
          "tree":"treeID"
       }
  ]
 }

**Comment by jimallman** [comment]
> this seems to indicate that the IDs for collections are strings ("trees-about-bees"). That seems odd. I'd rather have a unique identifier and a name string

Due to our desire for easy copying of collections, I had patterned this on the convention for GitHub repo URLs (unique object names within a "user space"). This makes the URLs much more sensible; highlights the ownership of a collection; and avoids the need to mint serial IDs. Of course, it means we'd need to force uniqueness in rare cases, e.g. "trees-about-bees-2".

I'm open to using our familiar pattern from studies, just "collection2345" etc. in a big pool. It will make little difference to someone using the curation app, but it makes things much more opaque if they're browsing GitHub directly.

> for the user identification, can we use 'username' rather than 'login'? Matches GitHub, then (which is where this info comes from, ultimately)

I was following the GitHub User API, which [uses "username" as an URL token but "login" in the JSON for user information](https://developer.github.com/v3/users/#get-a-single-user). I'm always concerned about confusion between displayed names ('Jim Allman') vs. arbitrary ids ('jimallman'), so I tend to refer to them as 'name' and 'id' respectively. But I don't have strong feelings about this.

> it seems strange to have a collection not contain a object called trees or treelist. What about a structure like this

Sure, I can see the sense of that. It will require shuffling trees between lists and tests that no tree is in multiple lists. Note that, based on the proposal above, I'd also want a 'pending' list for trees of interest, but about which no decision has been made (and why).

**Comment by jimallman** [comment]
As an aside, I suspect we'll want to add a 'latest_reviewed_SHA' or similar to each tree listed. This will help to ensure that
 - results when using a collection don't change; and
 - decisions based on old data can be updated for a modified tree. 

This leads to some interesting UI questions:
 - Do we show the SHA? or maybe something like "(2 newer modifications)"?
 - Do we let users "fast-forward" to the latest tree, presumably after a quick review?
 - Do we let them choose to always use the latest version of a tree?
 - Am I over-thinking this?

**Comment by kcranston** [comment]
I think the SHA needs to included, but tor the first iteration of the collections feature, let's simply default to the latest version of a given tree. The important part for the synthesis use case is to be able to version the entire collection, which would presumably include the SHA for each tree at that particular time. 

If people ask to be able to specify a particular version of a tree in a collection, then we can add that later.

**Comment by jimallman** [comment]
> The important part for the synthesis use case is to be able to version the entire collection, which would presumably include the SHA for each tree at that particular time.

Ah, good point! This will certainly do the job, esp. while we have a single docstore repo.

**Comment by kcranston** [comment]
Can this issue be closed, then?

**Comment by jimallman** [comment]
I think so, since we're up and running with the schema above. I'd like to tighten things up a bit more, but that can happen elsewhere. I suppose a wiki page is the logical place for an authoritative definition.
