### ISSUE TITLE
Deleting a tree (in curation app) leaves its OTUs behind

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#618]
This is a problem if we import a tree with bad labels. Removing the tree leaves them behind, so even when I reload the improved tree, the old OTUs (and their hideous labels) appear in the Mapping tab. (For now, we can hide these using the trees filter in OTU Mapping.)

Instead, when deleting a tree we should find OTUs that are **only used in this tree** and remove them as well. 

Comments welcome, if I'm overlooking any evil side effects of doing this.

**Comment by josephwb** [comment]
An example is [here](https://tree.opentreeoflife.org/curator/study/view/ot_305/?tab=otu-mapping): "A_fasciatus" and "M_migrans" are not used in any remaining tree.

**Comment by jimallman** [comment]
This problem went away with [smarter filtering of OTUs in the Mapping tab, as discussed here](https://github.com/OpenTreeOfLife/opentree/issues/909). Closing this issue, since all the interesting/open questions are better stated there.
