### ISSUE TITLE
Restore a popup with links to recommended licenses & waivers?

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#621]
At one time, we had such a key in the study-creation workflow:
https://tree.opentreeoflife.org/curator/study/create

...but it appears to have been removed during UI revisions. We should restore this and link to it from the study creation, viewing **and** editing pages.

**Comment by jar398** [comment]
I requested its removal because I don't think we should be encouraging data
licensing in any way.

The needed change is to allow the "I am an author or authorized" CC0
selection step from the metadata page.

**Comment by jimallman** [comment]
Hm, I can't seem to find the old popup that explained licenses/waivers. In any case, I'd suggest we model this on the existing popup that explains study-download file formats (linked from the sidebar in the Metadata tab):

![screen shot 2015-03-18 at 5 18 00 pm](https://cloud.githubusercontent.com/assets/446375/6719715/ec72d822-cd92-11e4-88d8-c4b13a6e367e.png)

**Comment by jimallman** [comment]
> I requested its removal because I don't think we should be encouraging data licensing in any way.

Gotcha, this makes sense.

> The needed change is to allow the "I am an author or authorized" CC0 selection step from the metadata page.

**This is the current behavior**, assuming that there's no current license or waiver already applied.

**Comment by jimallman** [comment]
@jar398, feel free to close this issue based on the prior decision above.

**Comment by jar398** [comment]
On Wed, Mar 18, 2015 at 5:21 PM, Jim Allman <notifications@github.com>
wrote:

> I requested its removal because I don't think we should be encouraging
> data licensing in any way.
>
> Gotcha, this makes sense.
>
> The needed change is to allow the "I am an author or authorized" CC0
> selection step from the metadata page.
>
> *This is the current behavior*, assuming that there's no current license
> or waiver already applied.
>

Oh, very sorry!  I was looking at the view version of the metadata tab, not
the edit version. Excellent.
