### ISSUE TITLE
Recognized fungal orders not "mappable" 

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#623]
This issue is for study https://tree.opentreeoflife.org/curator/study/view/ot_246/?tab=otu-mapping
![screen shot 2015-04-05 at 4 57 32 pm](https://cloud.githubusercontent.com/assets/6391539/6998879/293e0c16-dbbe-11e4-9b27-71f7d5724fe1.png)
The following OTUs can't be mapped (*in some cases it might be because these are very recent decried taxa)
1. Stereopsidales http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=805763
2. Moniliellales not in Index fungorum but in Mycobank (Moniliellales Q.M. Wang, F.Y. Bai & Boekhout, Persoonia 33: 46 (2014) [MB#805230])
3. Kriegeriales http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=801220
4. Septobasidiales http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=90572
5. Mesochytriales http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=550331
6. Gromochytriales http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=805305
7. Phaeomoniellales http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=810711
8. Caliciales http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=90462
9. Holtermanniales http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=517032
10. Lepidostromatales http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=803215

**Comment by jar398** [comment]
The latest dump we have of IF doesn't have Stereopsidales, which means we
need to think about getting a more recent dump.

Any idea who is taking care of Index Fungorum these days? The web pages
still say Paul Kirk, but I thought he was laid off..

I'm very puzzled about Mesochytriales. It's in OTT:
https://tree.opentreeoflife.org/opentree/argus/ottol@5347366/Mesochytriales
but is incertae sedis. I didn't think the TNRS throws away incertae sedis
taxa, but maybe it does?

**Comment by jar398** [comment]
Oops, it's the same TNRS in the tree browser search and for mapping... so I
don't get how a name can be available in the one, without being available
in the other.

**Comment by jimallman** [comment]
In the OTU mapping UI, it seems we already trim leading and trailing whitespace from manually-edited labels when calling the mapping service. I see no reason why we shouldn't do the same for original node labels. 

The only interesting question is whether to do it in the web UI, or in the [`contextQuery` service of taxomachine](https://github.com/OpenTreeOfLife/taxomachine/blob/b11c83b59ad94a138dceefb81e412d1754905155/src/main/java/org/opentree/taxonomy/plugins/TNRS.java#L240) (to avoid repeating these mysterious results for API users). It looks like this would just require trimming leading and trailing whitespace [here](https://github.com/OpenTreeOfLife/taxomachine/blob/b11c83b59ad94a138dceefb81e412d1754905155/src/main/java/org/opentree/taxonomy/plugins/TNRS.java#L305) and [here](https://github.com/OpenTreeOfLife/taxomachine/blob/b11c83b59ad94a138dceefb81e412d1754905155/src/main/java/org/opentree/taxonomy/plugins/TNRS.java#L315).

**Comment by jimallman** [comment]
> The only interesting question is whether to do it in the web UI, or in the contextQuery service of taxomachine...

I've gone ahead and made the needed change (tested in-browser) to the master branch of opentree. We should consider whether to repeat this string-trimming in `taxomachine` as described above.
