### ISSUE TITLE
Sorting by author in curator

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#625]
I have been rooting out some duplicate studies, and would find it helpful to be able to sort studies in the curator app by author name. I think would be of general use as well.

**Comment by jimallman** [comment]
OK, I've added sort options "Sort by primary author" and "Sort by primary author (reversed)". This is working now on **devtree**.

Note that we'll use `str.localeCompare()` in newer browsers, so the sorting of names with diacritical marks etc. should conform to the user's expectations.

As usual, sorting and filtering options will also be reflected in the browser history and can be shared via URL, like so:

https://devtree.opentreeoflife.org/curator/?order=Sort+by+primary+author

**Comment by kcranston** [comment]
How much work to just make the table sortable? Sorting by reference (the first column) would have the same effect as these menu options.

**Comment by jimallman** [comment]
It would be easy to apply the same sorting when the Reference column header is clicked. I suppose I'd need to add a caret or ascending/descending indicator to the column header.

But I'm worried about the larger implications of this:
- Should all headers be available as sort options?
- Would this entirely replace the existing sort widget? (Or should we keep both?)
- If so, we'd need to add (sortable) columns to offer some of the current sorting options:
Publication Date, OTUs being in preferred trees, etc.
- How would we sort on curator name(s)? Can we detect last names?
- Would we need to follow suit on all other filtered-list pages?
- What if the header-driven sorting conflicts with other sort/filter options? 

The current UI allows for arbitrary sorting/filtering based on "business rules" as opposed to literal-minded sorting of column values.
