### ISSUE TITLE
Load supporting information (in tree-view) from oti? 

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#627]
It seems we no longer have this information in arguson "naturally", so we should consider loading all this information on-the-fly from **oti**.

What can we get from oti? We can use [its handy API](https://github.com/OpenTreeOfLife/opentree/blob/master/neo4j_services_docs.md) to check...

```bash
$ curl -X POST http://devapi.opentreeoflife.org/oti/ext/QueryServices/graphdb/getSearchablePropertiesForStudies

[ "ot:studyPublicationReference", "is_deprecated", "ot:focalCladeOTTTaxonName",
"ot:studyLastEditor", "ot:studyLabel", "ot:studyModified", "ot:comment",
"ot:dataDeposit", "ot:studyId", "ot:authorContributed", "ot:studyUploaded",
"ot:studyYear", "ot:focalCladeTaxonName", "ot:tag", "ot:studyPublication",
"ot:curatorName", "ot:focalCladeOTTId", "ot:focalClade" ]


$ curl -X POST http://devapi.opentreeoflife.org/oti/ext/QueryServices/graphdb/getSearchablePropertiesForTreeNodes

[ "ot:isLeaf", "ot:age", "ot:ottId", "ot:ageMin", "ot:nodeLabel", "ot:parent",
"ot:treebaseOTUId", "ot:tag", "ot:ottTaxonName", "ot:comment", "ot:isIngroup",
"ot:ageMax", "ot:originalLabel" ]


$ curl -X POST http://devapi.opentreeoflife.org/oti/ext/QueryServices/graphdb/getSearchablePropertiesForTrees

[ "is_deprecated", "ot:treebaseTreeId", "ot:branchLengthMode",
"ot:branchLengthDescription", "ot:comment", "ot:nodeLabelMode",
"ot:originalLabel", "ot:studyId", "ot:ottId", "ot:treeModified",
"ot:treebaseOTUId", "ot:treeLastEdited", "ot:tag", "ot:inferenceMethod",
"ot:ottTaxonName", "ot:branchLengthTimeUnits", "ot:nodeLabelDescription",
"oti_tree_id" ]
```

What do we currently show in the tree view? Can we provide it from OTI or minimal arguson (node+source)?

- **reference text**: YES, from OTI > study > ot:studyPublicationReference
- **DOI (as URI)**: YES, from OTI > study > ot:studyPublication
- **link to study in curation app**: YES, from OTI > study > ot:studyId
- **link to support tree (in curation app)**: MAYBE, from OTI > study > ot:studyId; OTI > tree > ????
        Maybe an oti field is mis-named? ot:studyId, ot:ottId, oti_tree_id?
- **curator name**: SORT OF, from OTI > study > ot:curatorName
        NOTE that oti only reports one name! see https://github.com/OpenTreeOfLife/oti/issues/35
- **data deposit URL**: not required? (this is in current arguson, but maybe not shown)

What data is available directly on the node in arguson?
- ott id
- SILVA id [if found]
- taxonomic rank
- via bare-bones 'source' property (eg 'pg_2542_5590_a2c48df995b2c48df9c8452')
  - study id
  - tree id
  - SHA/version (of the study) used in synthesis

**NOTE:** We don't currently show any supporting data for the arguson target node (discussed in #599), nor for the "upward" nodes on the left. So there's definitely room for improvement here. But we'll need to add the basic 'source' field (see above) for each of these.

**Comment by jimallman** [comment]
@josephwb mentioned this in discussion:

treemachine currently returns supported info: studyid_treeid_gitsha, for example:
```bash
curl -X POST http://devapi.opentreeoflife.org/v2/graph/node_info -H "content-type:application/json" -d '{"ott_id":810751}'
```

This should enable us to fetch data for the "target" and "rootward" nodes in tree view, albeit at the cost of an extra fetch + delay.

**Comment by jimallman** [comment]
I've updated the original comment (above) for clarity, and added a link to https://github.com/OpenTreeOfLife/oti/issues/35, which describes the single-value bug in **oti**.

**Comment by josephwb** [comment]
This might be a better example, as it is the call you are using:
```
curl 'https://devapi.opentreeoflife.org/cached/treemachine/v1/getSyntheticTree' -H 'Content-Type: application/json' --data-binary '{"treeID":"otol.draft.22","format":"arguson","maxDepth":"2","subtreeNodeID":"792659"}'
```
The relevant bit of the result:
```
  "sourceToMetaMap" : {
    "taxonomy" : {
      "study" : {
        "source" : "taxonomy"
      }
    },
    "ot_104_1_a2c48df995ddc9fd208986c3d4225112550c8452" : {
      "study" : {
        "source" : "ot_104_1_a2c48df995ddc9fd208986c3d4225112550c8452"
      }
    }
  }
```

**Comment by jimallman** [comment]
@josephwb, while we're at it, can we finally move away from strings-with-underscores and to structured JSON for these ids? This was all discussed before in https://github.com/OpenTreeOfLife/treemachine/issues/99#issuecomment-47803634, and (if I'm reading that conversation correctly) [some of the work has already been done to support this](https://github.com/OpenTreeOfLife/treemachine/issues/99#issuecomment-48385384). Thanks, @chinchliff!

The upshot is, it would be great to see something like this in the arguson instead:
```json
  "sourceToMetaMap" : {
    "taxonomy" : {
      "study" : {
        "source" : "taxonomy"
      }
    },
    "ot_104_1_a2c48df995ddc9fd208986c3d4225112550c8452" : {
      "study" : {
        "source" : {"study": "ot_104", "tree": "1", "commit": "a2c48df995ddc9fd208986c3d4225112550c8452"}
      }
    }
  }
```
There's a lot of redundancy in there, but it seems we need unique strings for study-based support so I suppose it's not terrible. This would do the job with a lot less noise, and give us the taxonomy version in the bargain:
```json
  "sourceToMetaMap" : {
    "taxonomy" : "2.8_5",
    "ot_104_1_a2c48df995ddc9fd208986c3d4225112550c8452" : {
        "study": "ot_104", 
        "tree": "1", 
        "commit": "a2c48df995ddc9fd208986c3d4225112550c8452"
    }
  }
```
It looks like [we're touching all the code](https://github.com/search?q=sourceToMetaMap&type=Code&utf8=%E2%9C%93) that cares about `sourceToMetaMap`, so I think we'd be safe to make a change like this. Thoughts?

**Comment by josephwb** [comment]
Fine with me, and easy enough to do.

**Comment by josephwb** [comment]
Arguson is now in the desired format (see 7e3525c6cf9b6aa4c1e5ad4438c98e03783b579f).

**Comment by jar398** [comment]
Time to close this?

**Comment by jimallman** [comment]
I think so, yes. There's a related bug (missing support info) due to oti indexing errors, but i believe we're tracking that separately. Closing this now.
