### ISSUE TITLE
java 8 needed

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#628]
Treemachine is dependent on java 8. Java 8 is not currently available on devapi.

**Comment by jimallman** [comment]
@josephwb: While I'm willing to try, I'm probably not the best person to attempt a side-by-side install of multiple versions of Java. (Or do you just want to upgrade to Java 8 for everything?)

**Comment by josephwb** [comment]
I would say the latter, but I am certainly not the person to make this decision.

**Comment by jimallman** [comment]
@jar398 , do you have a preference re targeting just one version of Java, or installing and managing multiple versions on **devapi**?

**Comment by jar398** [comment]
What version of neo4j are you using? Still 1.9x?

I'd rather not do side by side; if one of the neo4js can use java 8 I don't
see why they all couldn't.

It's a matter of figuring out how to do a java 8 install on the version of
debian we're using (which is no longer the latest).

Maybe we can test this on ot17 (asterales).

**Comment by jar398** [comment]
I tried installing it on ot21 with
    sudo apt-get install openjdk-8-jre
but this didn't work:
    Reading package lists... Done 
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package openjdk-8-jre
If it had worked, it would be a simple matter of editing deploy/as-admin.sh. But now we'll have to figure out what shell command on debian wheezy will succeed in installing java 8.

**Comment by jimallman** [comment]
I see lots of tips on installing Oracle's Java 8 stuff in Debian wheezy, but not much on installing openjdk. I found [these packages](https://packages.debian.org/search?keywords=openjdk-8-jre), but after applying the filters above it seems none is wheezy-compatible.

Some people suggest using a trustworthy Ubuntu [PPA](https://help.launchpad.net/Packaging/PPA) (Personal Packaging Archive). There are [several PPAs that might fit the bill](https://launchpad.net/ubuntu/+ppas?name_filter=openjdk-8-jre).

**Comment by josephwb** [comment]
Can this be closed?

**Comment by jar398** [comment]
Fixed by 11c09de
