### ISSUE TITLE
new tree name / version

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#629]
The next version will be "opentree3.0", replacing "otol.draft.22". I hear this is hardcoded in a few places. Can we (ideally) move to this a config variable, or update the name in the places that it occurs?

**Comment by josephwb** [comment]
Changing this in treemachine is easy-peasy, and web services can (and, I believe, do) use a default argument for the most recent version such that calls need not know the actual name of the tree. 

Just need to make sure changes are made in step with all things @jimallman.

**Comment by jimallman** [comment]
We'll need to backtrack each inline use of "otol.draft.22" to see what's really going on. I think we're actually handling this pretty well in the synth-tree viewer, where this string is derived from [the server-side `fetch_current_synthetic_tree_ids` method](https://github.com/OpenTreeOfLife/opentree/blob/2d2468a124942f4ba4eadcf2b5b3d42055a130d2/webapp/controllers/default.py#L120), which in turn calls the phylesystem API at https://api.opentreeoflife.org/treemachine/v1/getDraftTreeID

This should match treemachine's internal tree id and Do The Right Thing without further attention. If treemachine is the logical place to manage these ids, this is probably a useful model to emulate elsewhere.

**Comment by josephwb** [comment]
Things are good-to-go and the treemachine side. Pushing a DB to dev now so that @jimallman can iron out things.

**Comment by jimallman** [comment]
I believe we've entirely removed hard-coded synth-tree ids from the current code. A few instances remain in docs, comments, and [unused views](https://github.com/OpenTreeOfLife/opentree/blob/2d2468a124942f4ba4eadcf2b5b3d42055a130d2/webapp/views/synthview/index.html#L71).
