### ISSUE TITLE
Link to CC0 waiver

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#638]
On the Add New Study page, the two mentions of CC0 should both link to https://creativecommons.org/choose/zero/ 

![screen shot 2015-05-18 at 19 01 06](https://cloud.githubusercontent.com/assets/312034/7692282/650cca04-fd90-11e4-8dc3-61fcaac7b7df.png)

**Comment by jimallman** [comment]
This fix is available on **devtree** and in a PR request.
