### ISSUE TITLE
Under mapping options, need categories for green algae 

### ISSUE THREAD

**Issue by LouiseLewis** [OpenTreeOfLife/opentree#642]
We cannot narrow down the taxonomic category with the selections currently available. It would be good to add the phya Chlorophyta and Charophyta (or Streptophyta) for the two major lineages of green algae. The green algae currently can only go into the "All of Life" category. Cheers.

**Comment by mtholder** [comment]
Thanks for the feedback, Louise. 
I created an issue in the repository of the software tool that generates that list. You may get an email about that because I included your GitHub username.

all the best,
Mark

**Comment by LouiseLewis** [comment]
Great, thanks Mark.   Happy to get involved if questions come up.
Cheers, Louise


On May 20, 2015, at 2:33 PM, Mark T. Holder <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the feedback, Louise.
I created an issue in the repository of the software tool that generates that list. You may get an email about that because I included your GitHub username.

all the best,
Mark

—
Reply to this email directly or view it on GitHub<https://github.com/OpenTreeOfLife/opentree/issues/642#issuecomment-103988266>.

<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>

Dr. Louise A. Lewis
Professor
Ecology and Evolutionary Biology
University of Connecticut
75 North Eagleville Road
Storrs, CT 06269-3043 USA

louise.lewis@uconn.edu<mailto:louise.lewis@uconn.edu>
voice: +1 860-486-6723

General web page  ->  http://hydrodictyon.eeb.uconn.edu/
Desert Green Algae  ->  http://pediastrum.eeb.uconn.edu/
Green Algae Tree of Life Project -> http:// gratol.org

OFFICE: 200 Pharmacy/Biology
LAB: 311-313 Pharmacy/Biology

<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>

**Comment by jar398** [comment]
Issue moved to taxomachine repo
