### ISSUE TITLE
"Approve all and continue" not working

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#643]
Working with [this study](https://tree.opentreeoflife.org/curator/study/view/ot_289), I successfully mapped all tips easily (context = birds), but "Approve all and continue" does nothing.

In case it helps, here is the newick string:

(Pluvialis_squatarola:0.034210452014654086,((Charadrius_modestus:0.02656399131458202,(Eudromias_morinellus:0.022363932109329604,(Charadrius_tricollaris:0.014334507689889954,((Charadrius_vociferus:0.010544167567509775,(Charadrius_hiaticula:0.008645186579631717,(Charadrius_melodus:0.006628208600692652,Charadrius_semipalmatus:0.006628208600692652):0.002016977978939065):0.0018989809878780586):0.0033811375353723673,((Charadrius_forbesi:0.010475920057987836,Thinornis_rubricollis:0.010475920057987836):0.0018142192389543725,(Thinornis_novaeseelandiae:0.010477179886419144,(Charadrius_placidus:0.010348749299814898,Charadrius_dubius:0.010348749299814898):1.2843058660424664E-4):0.0018129594105230646):0.0016351658059399338):4.0920258700781476E-4):0.00802942441943965):0.004200059205252411):0.003725468527639393,(((Charadrius_asiaticus:0.006149064294105784,Charadrius_veredus:0.006149064294105784):0.0031421886252103563,(Charadrius_mongolus:0.004367260839817016,Charadrius_leschenaultii:0.004367260839817016):0.004923992079499125):0.0016819392427859028,((Charadrius_bicinctus:0.007327117288533507,(Anarhynchus_frontalis:0.005025347286098887,Charadrius_obscurus:0.005025347286098887):0.00230177000243462):0.0025067812812857304,(((Charadrius_wilsonia:0.006858525703978567,Charadrius_collaris:0.006858525703978567):7.713643848931469E-4,(Charadrius_montanus:0.0076174736499512175,(Charadrius_alticola:0.0025255826078745443,Charadrius_falklandicus:0.0025255826078745443):0.005091891042076673):1.2416438920496639E-5):0.0013460694057356951,((Charadrius_thoracicus:0.0031371074670612405,(Charadrius_sanctaehelenae:4.0923544758022373E-4,Charadrius_pecuarius:4.0923544758022373E-4):0.0027278720194810167):0.004775525091420948,(Charadrius_ruficapillus:0.00629851019428072,(Charadrius_nivosus:0.004132238064186829,(Charadrius_pallidus:0.0032170301706055445,(Charadrius_peronii:0.0023982515923937284,(Charadrius_marginatus:0.0018421214098348487,Charadrius_alexandrinus:0.0018421214098348487):5.561301825588796E-4):8.187785782118161E-4):9.152078935812848E-4):0.002166272130093891):0.0016141223642014684):0.0010633269361252206):8.579390752118284E-4):0.0011392935922828057):0.01931626768011937):0.0039209921724326705);

**Comment by jimallman** [comment]
OK, I suspect the problem is [here](https://github.com/OpenTreeOfLife/opentree/blob/14709922eaec61c0511029028f40b3809dd62f88/curator/static/js/study-editor.js#L4815-L4816):
```javascript
function approveAllVisibleMappings() {
    $.each(getAllVisibleProposedMappings(), function(i, OTUid) {
        var approvedMapping = proposedOTUMappings()[ OTUid ];
        if ($.isArray(approvedMapping())) {
            // do nothing, curator has not chosen a candidate
        } else {
        ...
```
We recently standardized the display of suggested mappings to use a "pickable" list, _even if there's just one suggested mapping._ The `isArray` test is probably assuming an explicit choice is required, when it can (and shoould) map to only choice available.

Should be an easy fix, I should have something shortly...
