### ISSUE TITLE
"website" URL on https://devtree.opentreeoflife.org/curator/profile

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#645]
the href is treated as relative. So, for instance, mine goes to https://devtree.opentreeoflife.org/curator/phylo.bio.ku.edu/mark-holder 
rather than http://phylo.bio.ku.edu/mark-holder

**Comment by jimallman** [comment]
@mtholder, it looks like [your GitHub profile](https://api.github.com/users/mtholder) has an incomplete URL (no scheme specified):
```json
name: "Mark T. Holder",
company: "Univ. Kansas",
blog: "phylo.bio.ku.edu/mark-holder",
```
I'll check for this and prepend "http:" if it's missing...

**Comment by jimallman** [comment]
This fix is now deployed on **devtree**, see for example https://devtree.opentreeoflife.org/curator/profile/mtholder
