### ISSUE TITLE
API example returns empty record

### ISSUE THREAD

**Issue by dwinter** [OpenTreeOfLife/opentree#651]
The example give from [`studies/find_studies`](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#find_studies) in the API docs returns an empty record

```sh
curl -X POST http://api.opentreeoflife.org/v2/studies/find_sudies \
        -H "content-type:application/json" \ 
        -d '{"property":"ot:studyId","value":"pg_719","verbose":true}'
```
```
{
  "matched_studies" : [ ]
}
```
Previously this example retuned a full record, which is the expected value in the [shared-tests for the different API wrappers](https://github.com/OpenTreeOfLife/shared-api-tests). Changing the tests is not problem, but thought you might want update the docs or know that this record had gone.

**Comment by mtholder** [comment]
thanks, @dwinter. 
It looks like we have either a bug in the study indexer, something that triggers it, or some brittleness in the indexing db bootstrapping procedure.
A similar call is also failing. see https://github.com/OpenTreeOfLife/oti/issues/41#issuecomment-109287759

**Comment by jar398** [comment]
Can you try again?  Should be fixed by https://github.com/OpenTreeOfLife/ot-base/pull/17 which was deployed today.

**Comment by dwinter** [comment]
Perfect thanks -- happy for you to close this now @jar398
