### ISSUE TITLE
Is there any way to make the links to nodes in the feedback issue tracker stable across versions of the tree?

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#657]
We probably would want to retain the full link with the synth tree ID, but it seems like it would be nice to have a link that can be checked when we redeploy a new tree.

An example is the link in https://github.com/OpenTreeOfLife/feedback/issues/53

but I suspect that all of the feedback links are now dead.

**Comment by jar398** [comment]
A agree - node ids should *never* occur in URLs. Supporting URLs for nodes
that have OTT ids should be easy. For other nodes, it's a matter of finding
OTT ids for any two nodes whose MRCA is the node in question.  That will
probably require support from treemachine.

**Comment by jimallman** [comment]
> For other nodes, it's a matter of finding OTT ids for any two nodes whose MRCA is the node in question.

Agreed. We have [an API call to find the MRCA](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#mrca) in the draft tree, given two tip taxa. We just need to **pick** two definitive tips while building the synth-tree view. Do you suppose treemachine could capture and store these (2 tips per internal node) after synthesis?

**Comment by jar398** [comment]
The two nodes don't have to be tips (of the synthetic tree), in case that
makes the problem any easier. It's better if they are, but not completely
necessary. They just need to have OTT ids.

Treemachine support would be nice, and the method you propose would be nice
too.

**Comment by jimallman** [comment]
I believe this is addressed with our current scheme of synth-tree node ids? Examples:
 - ott1234
 - mrcaott1234ott9876

For example, when clicking a node link in the curation app's conflict summary, we display the best matching node in the current synthetic tree (and a note if this might be a surprise to the user).
