### ISSUE TITLE
Use log-scale axis for the OTU-coverage graph (Progress page)?

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#665]
If we anticipate more data in the lower range of the Y axis, we might use a log scale to show smaller changes over time. Postponing this for now, since the simple linear scale seems to better reflect the proportions shown.

**Comment by jimallman** [comment]
@jar398, @kcranston: For comparison, I've implemented the log scale for the Y axis (OTUs in OT taxonomy). Here's the familiar visualization using a linear scale:

![screen shot 2015-07-02 at 6 16 47 pm](https://cloud.githubusercontent.com/assets/446375/8489201/e22195aa-20e6-11e5-9467-fffad07e5e85.png)
...and the same data presented using a log scale:

![screen shot 2015-07-02 at 6 17 04 pm](https://cloud.githubusercontent.com/assets/446375/8489193/d4048838-20e6-11e5-98b0-f8d83246cb2b.png)
The log-scale code is stashed for now, but easy to apply if you prefer this version.

**Comment by jimallman** [comment]
This version adds ticks on the Y axis to highlight the log scale:

![screen shot 2015-07-02 at 6 34 52 pm](https://cloud.githubusercontent.com/assets/446375/8489400/1d0a3f44-20e9-11e5-8400-ef5668d695a9.png)

**Comment by kcranston** [comment]
Thanks for the comparison. I actually think that the log axis looks too optimistic. What do others think?

**Comment by pmidford** [comment]
I think the second log axis example, with all the y-axis ticks, looks 
kind of busy.

**Comment by jimallman** [comment]
I'd agree with "optimistic". The log scale is flattering to the first few OTUs in synthesis, but it will quickly lose clarity as we add more.

It's really more suited to tracking the _rate_ of change. I assume we expect a more-or-less linear growth trend for OTUs in synthesis, unless curation goes viral. :smile_cat: So the linear scale makes more sense to me.

**Comment by kcranston** [comment]
Sounds like we are in agreement about linear being better than log. Closing.
