### ISSUE TITLE
Revisit stats (release history) for synthesis 

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#667]
The [current stastics](https://devtree.opentreeoflife.org/static/statistics/synthesis.json) include a [dense run of daily synthesis releases](https://devtree.opentreeoflife.org/about/progress). @kcranston mentioned that we'd really prefer to show just a few (current three) significant releases. Are we capturing stats for experimental runs or rough draft versions?

Also, it would be nice to have stats for some of the earlier synth releases. If we can assemble these, I'll restore the earlier taxonomy versions that were [removed from the hand-built taxonomy stats](https://github.com/OpenTreeOfLife/opentree/commit/742012fdb489edd5eddb090049cd9a3b8f0afdff).

**Comment by jar398** [comment]
All the versions of the synthetic tree graphdb that have been 'released'
are on  ot10:

opentree@ashby:/disk2/opentree/downloads$ ls -tl
total 54069468
-rw-r--r-- 1 opentree opentree 11485911070 May 14 19:19
treemachine.db.tgz.20150506
-rw-r--r-- 1 opentree opentree 16226964620 Sep 14  2014
treemachine.db.tgz.20140914
-rw-r--r-- 1 opentree opentree  9555496855 Jul 23  2014
treemachine.db.tgz.20140723
...

I think it's a simple matter of firing up treemachine, pointing it at the
earliest of these graphdbs, and then checking whatever needs to be checked.
Easier said than done I know.

**Comment by jimallman** [comment]
These stats have since been winnowed down to just the "official" releases.
