### ISSUE TITLE
Change warning about duplicate studies

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#668]
The current warning about duplicate studies says "There is at least one other study with this DOI in the Open Tree collection". Given the impending collections feature, we should change the wording to "Open Tree database" instead of "Open Tree collection"

**Comment by jimallman** [comment]
OK, I'm replacing this in four places where the phrase "Open Tree collection" appears. (Would "Open Tree docstore" be more descriptive, or too weird?)

**Comment by kcranston** [comment]
I'd just say "database" (or maybe "data store"). Not doc, because I don't think that people think of trees being documents.
