### ISSUE TITLE
Implement tree-collection editor and listings

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#673]
The UI for these is fairly well developed, but they're showing dummy data. They should be bound to server-side (`phylesystem`) data using the existing REST API for collections. A sensible order of operations is probably:

- [x] Add the API endpoints (URLs) to the curation app's `private/config` file
- [x] Enable the browse/list UI (will show just our example studies)
- [x] Enable the creation UI
- [x] Enable the editing UI

**Comment by jimallman** [comment]
Note that [this oti issue](https://github.com/OpenTreeOfLife/oti/issues/42) is kind of a blocker, at least if we want to add trees using their preferred names. For now, all trees will be added as untitled, for example "Untitled (tree3)"

**Comment by kcranston** [comment]
I think we can avoid using oti for the first version of the collections feature. See [irc conversation](http://irclog.perlgeek.de/opentreeoflife/2015-07-28)

**Comment by jimallman** [comment]
This is basically satisfied, with proper lookup of tree names as a standing to-do in oti. (Once tree labels are returned properly, the UI will apply them when adding a tree to a collection.)
