### ISSUE TITLE
Disable the "preferred" checkbox for a single tree in a study.

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#689]
To communicate the system's behavior (a single tree is always considered for synthesis), the curation app should dim the UI that toggles "preferred" status when there's just one tree in the study. 

NOTE that this checkbox will still reflect any choices made already, e.g. if someone had three trees, checked one as preferred, and deleted the others.

**Comment by jar398** [comment]
Subsumed/mooted by #1070 , I think ?

**Comment by jimallman** [comment]
Agreed, closing this now.
