### ISSUE TITLE
Comments in curator not recognized as edits

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#693]
Comments of the front page of a study in the curator are not registered as an edit, so can't save when it is the only change to a study.

**Comment by jimallman** [comment]
@josephwb: I gather this refers to the "Curator notes" in the Metadata tab? Will try to reproduce...

**Comment by jimallman** [comment]
This is fixed now (working on **devtree**) and will be deployed to production as part of pull request #753. Please feel free to re-open this if not satisfied.
