### ISSUE TITLE
Some changes to study are not recognized, so Save is not enabled

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#694]
_[from @josephwb on IRC]_ comments of the front page of a study in the curator are not registered as a change, so can't save

I gather this refers to the "Curator notes" in the Metadata tab. Will try to reproduce...

**Comment by josephwb** [comment]
Too slow, @jimallman. Already put an issue [here](https://github.com/OpenTreeOfLife/opentree/issues/693). Please delete one copy.

**Comment by jimallman** [comment]
This is a dupe, removing it now.
