### ISSUE TITLE
Fix treatment of requirements.txt in install-web2py-apps.sh

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#695]
There's some funny logic in deploy/setup/install-web2py-apps.sh to remove 'distribute' from requirements.txt.  Can we just remove 'distribute' from requirements.txt instead? I don't remember why this was necessary.

Finished processing dependencies for peyotl==0.1.3dev
Using branch development of repo opentree
*** git failure ***
Repository opentree is unchanged since last time
Triggering use of HTTPS from within web2py? [true]
error: Your local changes to the following files would be overwritten by checkout:
	requirements.txt
Please, commit your changes or stash them before you can switch branches.
Aborting

**Comment by jimallman** [comment]
> There's some funny logic in deploy/setup/install-web2py-apps.sh to remove 'distribute' from requirements.txt. Can we just remove 'distribute' from requirements.txt instead? I don't remember why this was necessary.

Agreed, this is a real thorn in my side during deployment (since it stops 'git pull' because of uncommitted changes). We need to retrace the origin and purpose of this.

**Comment by jimallman** [comment]
It looks like this [manipulation of the `requirements.txt` file](https://github.com/OpenTreeOfLife/opentree/blob/17b39d1745beafe16f54d14f8bcc68af6d2a4558/deploy/setup/install-web2py-apps.sh#L107-L113) has been there for a long time, since these files were added in commit 17b39d1745beafe16f54d14f8bcc68af6d2a4558:
```bash
# Modify the requirements list
# numpy etc. have all kinds of dependency problems.
cp opentree/requirements.txt opentree/requirements.txt.save
if grep --invert-match "biopython\\|numpy\\|scipy\\|PIL\\|lxml" \
      opentree/requirements.txt >requirements.txt.new ; then
    mv requirements.txt.new opentree/requirements.txt
fi
```
Over time, the list of removed dependencies has changed (https://github.com/OpenTreeOfLife/opentree/commit/1fc6333e59026cb8c3081d52b93b9ccec68d6e1a, 584fc4b7386926f0a53604d3042fbb6e6f5243ce) to be just `distribute`, but there's no comment to explain the reason for the changes.

**Comment by jimallman** [comment]
As to whether we can remove `distribute` from `requirements.txt`, I would think distribute (or a sensible substitute) comes along with the pip install anyway. I suppose we'd need to test this on a new server to know for sure.

**Comment by kcranston** [comment]
Who changed `requirements.txt` on devtree? That's causing problems with the push.sh script, which is complaining about uncommitted local changes.

**Comment by mtholder** [comment]
isn't it the deploy script that changes that file?

And we aren't trying to push from devtree, are we?

**Comment by kcranston** [comment]
Running push.sh locally, and getting this error right at the start: 

```
Using branch development of repo opentree
error: Your local changes to the following files would be overwritten by checkout:
	requirements.txt
Please, commit your changes or stash them before you can switch branches.
Aborting
*** git failure ***
Repository opentree is unchanged since last time
```

**Comment by kcranston** [comment]
Sorry - didn't read the initial comment from @jar398 closely enough, and we are indeed getting the same error. I am going to make a new issue to stop the deployment if the git fetch fails - continuing is useless, and the script buries the error message at the very start of a huge amount of output.

**Comment by jimallman** [comment]
As described above, this is done in `install-web2py-apps.sh`, for reasons that are no longer clear but apparently had to do with our installation of numpy or other python packages. We can probably fix this by removing `distribute` from the requirements list instead (as it's likely installed with pip itself), but we'll need to test carefully on a fresh server.

:+1: on stopping the deployment entirely, if something like this happens

**Comment by jimallman** [comment]
In the meantime, here's the incantation to reset the remote git repo when a push fails:
```bash
ssh ot16   
cd repo/opentree
git reset --hard
exit
```

**Comment by jar398** [comment]
Here is my memory of what happened - this is from a long time ago so could
easily be fabricated:
- When initially setting up the deployment system, I received installation
instructions and scripts from a variety of sources, including one or more
requirements.txt files
- When I tried using the full set of requirements that I received, the
installation didn't work, either because the requirement couldn't be
fulfilled, or it was incompatible in some way, or it was redundant
- I didn't want to edit the requirements file since that was in someone
else's purview (and a fix to my scripts might have broken other methods of
installation), so instead I added a sed command to remove the problematic
(and as it turned out unnecessary) requirement

If this is the case, and the other methods of installation are simply not
done any more, then we should be able to edit requirements.txt in github,
and get rid of the sed command. It shouldn't be hard to test this using
devtree or asterales; just delete the virtualenv and try out the updated
install method.

**Comment by jar398** [comment]
This needs to get fixed... the failure is inconspicuous so the last time I did an update of tree.opentreeoflife.org I missed it, and new code didn't get deployed.

I'm puzzled because I don't remember this happening until recently. Maybe it's fallout from some change to git_refresh.

Using branch master of repo opentree
error: Your local changes to the following files would be overwritten by checkout:
	requirements.txt
Please, commit your changes or stash them before you can switch branches.
Aborting
*** git failure ***
Repository opentree is unchanged since last time

**Comment by jimallman** [comment]
@mtholder: As I'm reviewing our various `requirements.txt` files, I see that the [curation app has a tiny one](https://github.com/OpenTreeOfLife/opentree/blob/51a96f3885c5eecc3a14547d6c664a0e714d49b8/curator/requirements.txt) with just the locket package. But for the life of me, I can't find where it's installed. 

Both devtree.opentreeoflife.org and tree.opentreeoflife.org have locket installed. Is it possible this was done manually, or installed along with some other dependency?

Do we clobber the opentree virtualenv before a fresh deployment? If not, perhaps we should for greater confidence that we're installing everything we need.

**Comment by jimallman** [comment]
@pmidford: We'll also need to avoid this error (git fetch failure) after we've updated statistics files, since [some of these are stored in git](https://github.com/OpenTreeOfLife/opentree/tree/master/webapp/static/statistics) to preserve manual tweaks like release dates. Can we commit+push just these changed files, as new statistics are appended?

**Comment by jar398** [comment]
I understand that it would be nice to rebuild the virtualenv on every
update, but the virtualenv is used by web2py, so if you blow it away, you
will have to reinstall web2py (or at least its dependencies).

Maybe we could have two virtualenvs. Can they be nested?

**Comment by pmidford** [comment]
The statistics files are all generated on ot10 and moved to production via rsync, with the originals remaining on ot10.  We could commit them somewhere (germinator?).  I don't know what backup (if any) is covering ot10.

**Comment by jimallman** [comment]
Ah, good point. I think it would be sufficient to test using a "clean slate" once in awhile, just to make sure we're not kidding ourselves about when and how things are being installed. (At this point, I'm worried that we're coasting on manual operations or other history that isn't reflected in the latest deployment tools.)

> Maybe we could have two virtualenvs. Can they be nested?

Not to my knowledge, no.

**Comment by jimallman** [comment]
Regarding a "clean slate" test, it seems we could do this by using a fresh AWS instance (or equivalent system running Debian Jessie). Or I could clobber lots of stuff on the existing **devtree** like so:
```bash
# connect to devtree with sudo privileges
ssh admin@ot16
# stop apache (and web2py)
sudo apache2ctl stop
# remove our virtualenv directory
sudo rm -rf /home/opentree/venv
# disconnect form devtree
exit
```
... then re-deploy (using `push.sh`) from my local machine.

As a precaution, I'd use `pip freeze' to stash the currently installed packages and versions, both within the venv and in the main system python. Thoughts?

**Comment by jar398** [comment]
I just searched the deployment scripts and it seems the 'sed' of requirements.txt is no longer being done. So the problem should be resolved now.
