### ISSUE TITLE
"Download subtree as Newick string" broken?

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#701]
This link has been in the tree browser for a long time, but does not appear to work. When I click on it, the page simply loads forever. If it is indeed not working, we should delete the link.

**Comment by kcranston** [comment]
Looks like this is using old getDraftTreeForottId / getDraftTreeForNodeID calls [see code](https://github.com/OpenTreeOfLife/opentree/blob/51a96f3885c5eecc3a14547d6c664a0e714d49b8/webapp/controllers/default.py#L72) rather than [/tree_of_life/subtree](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#subtree_tree)

**Comment by kcranston** [comment]
@josephwb and @blackrim do any of these services have an upper bound on nodes?

**Comment by jimallman** [comment]
Regarding the maximum depth, the v2 method ‘subtree’ uses a maximum number of tips (currently 25000) and [returns an error if the subtree is larger than that](https://github.com/OpenTreeOfLife/treemachine/blob/2214f2ae435991f968c5ad555a78f42247a7b895/src/main/java/opentree/plugins/tree_of_life.java#L401-L404).

**Comment by jimallman** [comment]
If we had a (real, not displayed) tip count in argus, we could detect this condition up front and offer an alternate UI -- as @kcranston suggested, perhaps a link to the full Newick download.

**Comment by jimallman** [comment]
For the record, the old v1 method (used by the UI) does work, but can be very slow for large subtrees, even though the `maxDepth` is always capped at 4.

**Comment by jar398** [comment]
The tip count feature was originally requested here
https://github.com/OpenTreeOfLife/treemachine/issues/63​ in March 2014

**Comment by jimallman** [comment]
This should be all fixed, now that 
- we have proper tip counts, 
- we're using the newer `/tree_of_life/subtree` API method,
- and we offer a different link (to the full Newick download) for too-large trees.
