### ISSUE TITLE
Abort deployment if git_refresh fails

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#702]
If the git_refresh called from [install-web2py-apps.sh](https://github.com/OpenTreeOfLife/opentree/blob/master/deploy/setup/install-web2py-apps.sh) fails when running [push.sh](https://github.com/OpenTreeOfLife/opentree/blob/master/deploy/push.sh), the script outputs a `*** git failure ***` warning but continues on its merry way, burying the warning in a mountain of other output. This makes debugging a challenge, and if the repo doesn't refresh, there isn't much point continuing the deployment.

**Comment by jar398** [comment]
I believe this is done.
