### ISSUE TITLE
Perhaps we should update Raphael to avoid warnings in dev console?

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#705]
I don't know the implications of updating.

Symptom I'm trying to address: In Chrome when you have the developer console on and you load a view of the tree (e.g. https://tree.opentreeoflife.org/opentree/argus/ottol@81461/Aves ), you see multiple errors like this:

    Error: Invalid value for <svg> attribute preserveAspectRatio="meet"
    q @ raphael-min.js:10
    c._engine.setViewBox @ raphael-min.js:11
    v.setViewBox @ raphael-min.js:10
    argusObj.loadData.ajaxSuccess @ drawtree.js:479
    v.Callbacks.l @ jquery.js:2
    v.Callbacks.c.fireWith @ jquery.js:2
    T @ jquery.js:2
    v.support.ajax.v.ajaxTransport.send.r @ jquery.js:2

A little googling led me to: http://stackoverflow.com/questions/17687942/unexpected-value-meet-parsing-preserveaspectratio-attribute
which indicates that it was solved in the version of raphael that was the latest in May 2014.

**Comment by jimallman** [comment]
This fix is live on **devtree**, along with other changes to reduce console chatter. N.B. that you might need to clear browser cache to see the change!

**Comment by mtholder** [comment]
handled by https://github.com/OpenTreeOfLife/opentree/pull/713
