### ISSUE TITLE
unable to retrieve studies AND to add new studies

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#714]
I get the same error in both cases - with different to or pg # 

![screen shot 2015-08-24 at 12 42 58 pm](https://cloud.githubusercontent.com/assets/6391539/9446588/78cb7b40-4a60-11e5-92cd-6be7839e0aba.png)

Thanks, Romina

**Comment by rgazis** [comment]
now it seems to be working...

**Comment by jimallman** [comment]
@rgazis, thanks for the heads-up! It seems treemachine was hung, which blocks both curation and the synthetic-tree viewer. I'm not sure of the cause, but I forced a restart of treemachine and now all services are back online.
