### ISSUE TITLE
Be clear that "Approve all" means only perfect matches

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#718]
Currently the curator has a button to "Approve all" mappings. However, it would be nice to also have "Approve all perfect", because it is only the remainder that require curator scrutiny. :boar:

**Comment by josephwb** [comment]
This would be a good candidate: https://tree.opentreeoflife.org/curator/study/view/ot_307/?tab=otu-mapping

**Comment by rgazis** [comment]
I agree there is a need for distinction, but I think right now if you click "approve all" only perfect matches get accepted…?

**Comment by josephwb** [comment]
D'oh. Looks like you are correct; I didn't hit the button, as I didn't want to approve potentially suspicious mappings.

**Comment by josephwb** [comment]
Updated the issue.

**Comment by josephwb** [comment]
It looks like "Approve all" accepts synonym hits too. These can sometimes be wrong, so I'd like those to not be included in the "Approve all"

**Comment by josephwb** [comment]
Closing this for a more clear issue.
