### ISSUE TITLE
Option to "Approve all perfect matches" only

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#719]
The "Approve all" button on the mapping page apparently accepts all unique mappings, whether they are perfect or not (e.g. synonyms). I would like an option to accept all perfect matches only, as it is only the remainder that require scrutiny. :rocket:

This replaces the unclear issue https://github.com/OpenTreeOfLife/opentree/issues/718

**Comment by josephwb** [comment]
If this is not going to happen, having the ability to sort by map type (perfect, synonym, etc.) would be helpful.

**Comment by josephwb** [comment]
Another idea: when clicking on "Approve all", a window pops up asking what should be approved:
1) All mapped
2) Only perfectly mapped

This seems related to https://github.com/OpenTreeOfLife/opentree/issues/730.

**Comment by rgazis** [comment]
Having the options would be a good idea. "All mapped" would accept all the labels colored in green, right? because in some cases I noticed that even the labels colored in blue (synonyms) are also automatically accepted.

**Comment by josephwb** [comment]
No, my idea was that:

2) Only perfectly mapped

would be for the green matches, and 

1) All mapped

would be any non-ambiguous mapping (i.e. may map to a single (blue) synonym). I believe that this is the way the curator currently works (and what I would like changed).

**Comment by jimallman** [comment]
For now, I'm modifying this behavior to be more restrictive, as requested in #730. (All synonyms, homonyms, and less-than-perfect matches will require manual review.)
