### ISSUE TITLE
Confirm that we clearly mark leaf nodes in argus (synth-tree view)

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#721]
We do have code that [tries to distinguish leaves (with no children)](https://github.com/OpenTreeOfLife/opentree/search?utf8=%E2%9C%93&q=isActualLeafNode&type=Code), but we should review to see if this should be a more dramatic difference.

**Comment by jar398** [comment]
Does the new nLeaves feature (
https://github.com/OpenTreeOfLife/treemachine/pull/191) make a difference
here?

**Comment by jimallman** [comment]
> Does the new nLeaves feature ... make a difference here?

For overall size and style, the new `nTipDescendants` (all leaves in the current clade) is a more useful datum than the `nLeaves` (just its visible leaves in argus). I'll tinker with size and style to find a pleasing effect, including a distinct treatment for true leaf nodes.

**Comment by jar398** [comment]
Oh, I misunderstood which was which !  Sorry

**Comment by jar398** [comment]
I think it's fine. Can we close the issue?

**Comment by jimallman** [comment]
Yes, we now clearly distinguish between visible leaves (in the argus view) and actual leaf nodes in the tree.
<img width="619" alt="screen shot 2015-12-10 at 1 37 38 pm" src="https://cloud.githubusercontent.com/assets/446375/11724678/5c21e514-9f43-11e5-8492-6f4296e7851e.png">
