### ISSUE TITLE
Option to indicate "new species"

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#724]
I wonder if it would be possible to add an option (when mapping) in which the author/curator could indicate that the terminal/OTU is a new species described in the publication which is being uploaded. 

Example 

https://tree.opentreeoflife.org/curator/study/edit/ot_330/?tab=otu-mapping&order=Mapped+OTUs+first

This study includes many species of Cortinarius, which can make a great contribution to synthesis but it includes many novel species described as part of the study. Most of these species are already in Index Fungorum (they were described in 2014) but not in OTT. This could be very frustrating to authors.

Romina

**Comment by jar398** [comment]
I think the new taxon additions features covers this.
