### ISSUE TITLE
Explain/mention that some non-binomials can be mapped to OTT

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#726]
In some cases, terminals comprising on genus + strain # can be mapped to OTT. 
![screen shot 2015-08-28 at 2 11 33 pm](https://cloud.githubusercontent.com/assets/6391539/9553726/fcc25ece-4d8e-11e5-9e82-b5aaa6e0f419.png)

Can be confusing to authors, and it might be good to mention in the tutorial/manual in which cases non-binomials can be mapped.

**Comment by jimallman** [comment]
Am I correct that this refers to names like "Lecanicillium sp. CBS 100890"? What would be the desired mapping in this case?

**Comment by jar398** [comment]
I think the question is less about what the mapping is (in this case it's quite clear), than about the user wanting some model of when they'll find something and when they won't.

About the only thing to say about this is that a non-binomial like this is in OTT only if NCBI Taxonomy has it, and whether NCBI Taxonomy has it has to do with the vagaries of curation of the Genbank record. So it is quite spotty and out of our control. The policy for strains in the taxonomy has recently changed; NCBI is phasing out strains as "taxa" in their taxonomy.

**Comment by jar398** [comment]
This is probably oversharing, but for most molecular studies, all of the sequences are in Genbank, which means that all the tips are mappable. Assuming the sequences were deposited prior to the NCBI Taxonomy capture used in the latest OTT, if the TNRS doesn't give a mapping, you ought to be able to find a table among the supporting material for the publication that lists all of the samples, with Genbank id and something resembling the tip label. You can then look up the Genbank id in nuccore, and the nuccore record will always link to an NCBI taxon record. You can then feed the name in that record to the TNRS to get a good OTT mapping for the tip. I bet $1 this would work for the failed mapping in Romina's example.

I've done this and it works, but it's incredibly labor intensive.  You sort of wish they had just put the Genbank id in the tip label. If they did that, we could write a script to look them all up. But of course this would not be natural given the authors' workflow - they do the phylogenetic analysis and prepare the Newick before they do the Genbank deposits.

Alternatively, the curator could upload the tip table from the supporting material, and we could parse it to find the Genbank ids, and so on. But usually the table is in a PDF, not in any useable form, so this usually this will just be a dream.

**Comment by jimallman** [comment]
Food for thought, thanks @jar398!

**Comment by jimallman** [comment]
I've added some initial help text to the mapping status panel. (This can be expanded once we support direct mapping of NCBI and other IDs on terminals.) This is working now on **devtree**.

<img width="390" alt="screen shot 2017-06-01 at 12 20 14 pm" src="https://cloud.githubusercontent.com/assets/446375/26689754/c005dd90-46c4-11e7-94d4-f4fc12416b8d.png">

**Comment by jimallman** [comment]
I've also added a persistent message (see "genus + strain") in the Help panel for OTU Mapping:

<img width="389" alt="screen shot 2017-06-01 at 12 25 05 pm" src="https://cloud.githubusercontent.com/assets/446375/26689928/7960299e-46c5-11e7-8286-45c685ef306a.png">

Suggestions for revised text are of course welcome!

**Comment by jimallman** [comment]
@rgazis Since the related PR #1131 has been accepted and merged, I'm closing this issue. Please feel free to re-open if you think more action is needed here.
