### ISSUE TITLE
document meaning / usage of 'focal clade'

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#729]
Issue #728 made me think that we aren't doing a good job of letting people know the meaning and usage of the focal clade. In that case, Romina wants to assign the focal clade to a tip (because the study is about describing and placing that tip). That usage seems different than how we have used it in other contexts (describing the major clade in the study).

**Comment by jar398** [comment]
I think that from the point of view of utility for scripts (e.g. conflict reporting), the focal clade would best be chosen as "the smallest taxon that contains the ingroup".

**Comment by jimallman** [comment]
I've added @jar398's phrasing to the prompting text for the Focal Clade widget. This is working now on **devtree**.

<img width="698" alt="screen shot 2015-12-15 at 11 21 43 am" src="https://cloud.githubusercontent.com/assets/446375/11816393/3a4803ea-a31e-11e5-818a-bff0d9bbda09.png">

**Comment by kcranston** [comment]
This helps with the meaning of the focal clade, but doesn't help people understand usage. Feels like it needs a little 'info' or 'i' button with a description of why this is important (how does it affect synthesis, search, etc).

**Comment by mtholder** [comment]
Do we use it? I'd be fine with dropping it.
I think that it is a study-level property, which means that it could be awkward to describe in the context of the ingroup of a tree (since there might be multiple trees in the study with differing ingroup composition).

The focal group info is not used in synthesis.

**Comment by kcranston** [comment]
Good point, @mtholder . If we aren't using this field, then dropping it seems reasonable.

**Comment by jar398** [comment]
I've been using it in analyzing studies for OTU mapping and conflict
problems. If the calculated MRCA is way above the focal clade that suggests
something's amiss.

It can also be used in searches.

**Comment by jar398** [comment]
The outcome of yesterday's discussion was that there should be a property (in the nexson file) on trees that is a user input giving the taxon that the user expects will contain the ingroup. We can make a pass over the phylesystem and initialize this property with the study's focal clade, when there is one.

Then there would be no curated study-level property of this kind. A study-level property can be computed for display in the study search list and/or the study metadata tab; it could be either the expected ingroup taxon for one of the preferred trees, or the LICA of the e-i-ts of all the study's trees.

The expected ingroup taxon is to be used for consistency checking only.  If the LICA in the taxonomy of all the tips under the ingroup node does not fall under the e-i-t taxon, then the situation is flagged for curator attention; either the e-i-t should be changed or an OTU mapping needs to be fixed. We might also choose to flag situations where the ingroup node as represented in the synthetic tree does not fall under the e-i-t as mapped to the synthetic tree. And perhaps there could be other uses.

**Comment by jar398** [comment]
Discussion of 'expected ingroup taxon' continuing at #878
