### ISSUE TITLE
"approve all and continue" also approve non-exact matches

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#730]
Study
https://tree.opentreeoflife.org/curator/study/edit/ot_365/?tab=otu-mapping

Normally only exact matches are accepted when clicking "approve all and continue" (green and only one option for mapping).

In this case, the mapping options with a blue legend and a different name are accepted when clicking "approve all and continue".

P.S. I will not save the mapping in this study, so somebody can check if there is a bug

R

**Comment by rgazis** [comment]
It seems that these mappings would need to be approve - they correspond to synonyms- but I thought only exact matches should be automatically accepted when clicking "approve all and continue".

**Comment by jar398** [comment]
I agree, "approve all and continue" should not approve inexact matches
(other than maybe those involving case and other very minor differences).
They are too hard to spot manually.

**Comment by jar398** [comment]
This may be related to #769 (inexact matches getting approved without review)

**Comment by jimallman** [comment]
N.B. that the more restrictive "auto-approval" behavior will **approve** fuzzy-matched names that differ in case ("homo sapiens" => "Homo sapiens"), but will **not** approve them with different punctuation ("Homo.sapiens" => "Homo sapiens"). This follows the TNRS scoring algorithm, which assigns a score of 1.0 (perfect match) even where case differs.

**Comment by jimallman** [comment]
The new, more restrictive "auto-approval" is working now on **devtree**. I've imported the study above, which is available at this URL: 
https://devtree.opentreeoflife.org/curator/study/edit/tt_101?tab=otu-mapping 

N.B. that we will now skip (not auto-approve) a single mapping suggestion if it's a synonym *or* homonym, or if it's a less-than-perfect match (not including differences in upper/lower case).
