### ISSUE TITLE
Addition to the "Fuzzy" matching options

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#732]
Hi

The fuzzy matching is GREAT, super useful for mapping - at least fungal studies-. I was wondering if the option "only keep the first two words" can be added?  I understand you can make your own expression but it could be useful to have it as an option for people that do not know how to do it.

Hypomyces odoratus ex. Agaricus SRB I.P.17

just keep

Hypomyces odoratus

Would have been very useful for mapping the study https://tree.opentreeoflife.org/curator/study/edit/ot_374/?tab=otu-mapping

R

**Comment by jimallman** [comment]
Glad it's proving useful! Please feel free to ask for suggestions in situations like this, esp. if it'll save lots of tedious work.

> I was wondering if the option "only keep the first two words" can be added?

This should have the desired effect (paste these into a new substitution). 
**Replace this...**  `^(\S*\s+\S*).*` 
**with this** `$1`

I'll add this to the "common substitutions" list in the next build.

**Comment by rgazis** [comment]
it works! yay!

This will be VERY useful. Thanks!

Romina

**Comment by jimallman** [comment]
Closing this. The new substitution should appear in the next deployment to production.
