### ISSUE TITLE
Focal clade/taxa not in OTT 

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#733]
![screen shot 2015-09-01 at 12 06 14 pm](https://cloud.githubusercontent.com/assets/6391539/9609497/e85f09f8-50a1-11e5-98d5-c3ef374ff841.png)

https://tree.opentreeoflife.org/curator/study/edit/ot_377

No option to map genus Melampsora

 http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=16205

**Comment by rgazis** [comment]
In this case the genus Melampsora can be mapped to Podocystis which is now a synonym? http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=16269

but the current name is Melampsora - which is a valid name stored in IF

**Comment by jar398** [comment]
See last comment under #729.  I think we are going to do away with "focal clade" for the study in favor of "expected ingroup taxon" for each tree. If there is important information about the study that doesn't fit in the data model it should go in the curator comments.  In this case, for the 'expected ingroup taxon', you just have to find the best approximation within the taxonomy (that would probably be Podocystis, yes?) - the smallest taxon in OTT that contains eveything in the ingroup. The new taxonomy browser should be a big help for this purpose.

Does that address the question sufficiently?

**Comment by jar398** [comment]
@rgazis feel free to reopen this issue, but for now it looks like there's nothing to be done.
