### ISSUE TITLE
Unresponsive script when viewing large trees (1000s of tips)

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#740]
![screenshot from 2015-09-03 14 16 48](https://cloud.githubusercontent.com/assets/808499/9666852/8bd6b34c-5246-11e5-9af3-bbba074ac674.png)

**Comment by jar398** [comment]
dup of #604?

**Comment by jimallman** [comment]
Yes, I'd say it's a duplicate. Closing now.
