### ISSUE TITLE
Option to download tree in newick after mapping (with mapped labels)

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#743]
Hi

I already talked this with Emily and she taught me a way to download a tree after mapping (using some coding). However, I feel that an option to do this would be good.

There is an option to download the tree in newick under "Files" when the curator uploads his/hers own newick. Example https://tree.opentreeoflife.org/curator/study/edit/ot_455/?tab=files 

OR under the metadata tab when trees come from TreeBase

BUT

these trees still contains the original labels, would it be a possibility to add an option to download the tree with the mapped labels?

R

**Comment by jar398** [comment]
Is this a dup of #989 ? Or at least closely related?

**Comment by jimallman** [comment]
I believe it's a dupe, since the last request would be handled by a per-tree download feature:

> would it be a possibility to add an option to download the tree with the mapped labels?
