### ISSUE TITLE
is the curation tool website down?

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#746]
error: An error occured, please reload the page

Thanks!
Romina

**Comment by kcranston** [comment]
Yes, it's down at the moment. We are trying to fix it!

On Thu, Sep 10, 2015 at 2:44 PM, Romina Gazis <notifications@github.com>
wrote:

> error: An error occured, please reload the page
>
> Thanks!
> Romina
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTreeOfLife/opentree/issues/746>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~
karen.cranston@gmail.com
@kcranstn
~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jimallman** [comment]
Closing this (old news)
