### ISSUE TITLE
Branch length mode should not be 'Unspecified' for trees without branch lengths

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#747]
We bind the results of [getBranchLengthModeDescriptionForTree](https://github.com/OpenTreeOfLife/opentree/blob/a7631c1bf5d78017e916649c09a51bc0d0688300/curator/static/js/study-editor.js#L2342) to the [Branch Length Mode](https://github.com/OpenTreeOfLife/opentree/blob/26aa74928e2c5d38c2ae397fc63c3d1c72164410/curator/views/study/edit.html#L2368) field in the tree view. This function checks if the branch length mode has been set, but doesn't also check whether the tree has branch lengths. This means that a tree without branch lengths has this field set of 'Undefined' rather than 'No branch lengths' or simply hiding the field. This is related to issue #738.

**Comment by jimallman** [comment]
@kcranston, please review.

**Comment by kcranston** [comment]
Yup. Done.
