### ISSUE TITLE
Deploy statistics to production

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#749]
I copied the file phylesystem.json from devtree:web2py/applications/opentree/static/statistics/  to the corresponding location on tree:, and now we have the progress chart running on production.

Not sure what needs to be done to get the stats files updated dynamically on production.

**Comment by jimallman** [comment]
Closing, as I believe this work has all been completed. @pmidford, please re-open if I'm mistaken. (Is there any server setup that should be incorporated into our deployment scripts?)
