### ISSUE TITLE
file download link simply re-loads page

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#750]
On the Files tab, the filename is a link that we claim you can (click to download). However, clicking on these links simply re-loads the Files tab. Example here:

https://tree.opentreeoflife.org/curator/study/view/ot_99/?tab=files

**Comment by kcranston** [comment]
Also (and this should probably be a separate issue, but could probably be fixed together) the size should never be 0, right? It is in this example.

**Comment by jimallman** [comment]
Yes, these bugs are close together (let's keep just one issue). The failures above are due to missing data in older supporting files, but in these cases I'll show something more sensible:
 - remove the hyperlink from a file with no `@url`
 - show an em-dash if there's no `@size` found

**Comment by jimallman** [comment]
It looks like there's another problem in some studies, including your example above, where the supporting file is listed twice in the Nexson: once [for the study as a whole](https://github.com/OpenTreeOfLife/phylesystem-1/blob/master/study/ot_99/ot_99/ot_99.json#L106-L113), and again [under the tree for which it's a source file](https://github.com/OpenTreeOfLife/phylesystem-1/blob/master/study/ot_99/ot_99/ot_99.json#L951-L959).

In these cases, it seems only the second annotation is getting proper values for `@url` and `@size`, and the curation UI is checking the "wrong" annotation and finding neither. I'll chase this down...

**Comment by jar398** [comment]
(While we're on the topic, remember I'm sitting on a bunch of supporting
files that had been deleted by accident... they need to be put back in
place)

**Comment by jimallman** [comment]
Regarding duplicate annotations for these files, I've created a separate issue #752 to track this (larger) problem.

**Comment by jimallman** [comment]
The original reported symptom is now resolved by PR #753 (current working on **devtree**). OK to close this? Or would you like to keep it open as a reminder of [@jar398's pending file restoration](https://github.com/OpenTreeOfLife/opentree/issues/750#issuecomment-140524570)?

**Comment by jar398** [comment]
No need from my end to keep it open as a reminder about those files - I
worry about them quite frequently

**Comment by jimallman** [comment]
> I worry about them quite frequently

OK, let me know if you'd like some help replacing them.
