### ISSUE TITLE
The instructions in the README could be obsolete if you provided a Docker image for installation

### ISSUE THREAD

**Issue by MrThomasWagner** [OpenTreeOfLife/opentree#757]

**Comment by mtholder** [comment]
well, sort of. There is a thread on installers [here](https://groups.google.com/forum/?fromgroups&hl=en#!topic/opentreeoflife-software/gWKW6GyLWOc), though that thread is not about docker image *per se*.

However, even if we made images available, we'd still need decent installation instructions for developers on the project who produce the images.
