### ISSUE TITLE
Newick download (from synth-tree viewer) is broken?

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#758]
From an anonymous guest on IRC: 
> Hi, I'm wondering if there was some sort of issue with the "Download subtree as Newick string" feature on the Open Tree site?  Every group I've tried it on has returned a blank file, except for Eukaryota which only returned six species.

I'm finding two issues here:

- The Newick download does seem to return an empty file on current production. For example, [Antonospora](https://tree.opentreeoflife.org/opentree/opentree3.0@2992438/Antonospora) has a tiny subtree, but its Newick quickly returns as a complete empty file.

- I think our Newick-download prompt is confusing for some users, since Newick for Eukaryota is not downloadable ("This tree is too large to download through webservices, but you can download the entire synthetic tree as Newick"). I'm guessing the user was looking at the properties for a smaller clade in the view of Eukaryota, and thought they'd get the Newick for Eukaryota instead of the node whose properties they were looking at. I suppose we can make this text more explicit, but I'm not sure how to phrase this.

**Comment by jimallman** [comment]
Current prompting text is "Download subtree as Newick string". Maybe it could refer (once more) to the specific node, something like 
- "Download Antonospora as Newick string"
- "Download Antonospora subtree as Newick string"
- "Download subtree (from Antonospora) as Newick string"

Thoughts?

**Comment by kcranston** [comment]
For the second point, we could change the text to say "Download the subtree for [node name]..." to help with confusion about what will be in the download.

**Comment by jimallman** [comment]
Sounds good, thanks!

Meanwhile... it seems Newick download is also broken(!) on **devtree**. Investigating now...

**Comment by jimallman** [comment]
Some Newick downloads work fine on **devtree**, some fail. The pattern suggests there might be some kind of "poison pill" (e.g. unexpected punctuation in taxon names), but that's just a hunch.

WORKS: https://devtree.opentreeoflife.org/opentree/argus/ottol@770311/Hominidae

FAILS: https://devtree.opentreeoflife.org/opentree/opentree3.0@3654999/Candidate-division-WS6

**Comment by jimallman** [comment]
To clarify, the difference is not based on passing the OTT id vs. node id. (I've tested both for Hominidae.)

Here's the underlying service call for the failed (empty) Newick above, which returns sensible Newick:
```bash
curl -X POST https://api.opentreeoflife.org/v2/tree_of_life/subtree \
>   -H "Content-Type: application/json" \
>   --data-binary '{"ott_id":"511800"}'
{
  "tree_id" : "opentree3.0",
  "newick" : "(Antonospora_scoticae_ott887491,(Antonospora_locustae_HM-2013_ott371242)Antonospora_locustae_ott120820,Antonospora_psocopterae_ott276362)Antonospora_ott511800;"
}``` 

So what's going wrong? Ah, here's the culprit (a missing value in the server-config file). This is from the diagnostic footer information on production:
> v2_api: //devapi.opentreeoflife.org/v2

This should be pointing to `api.opentreeoflife.org`. I'll hot-fix this on production for now, but it definitely needs to be addressed in the server-config file (or deployment tools?).

**Comment by jimallman** [comment]
This is now handled correctly in the deployment tools. Closing!
