### ISSUE TITLE
error when saving edits in study pg_978

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#768]
Merge needed - 915269eba072abff6c52f223b4c6d7cee6adc47b

Your changes were saved, but an edit by another user prevented your edit from merging to the publicly visible location. In the near future, we hope to take care of this automatically. In the meantime, please report this error to the Open Tree of Life software team

**Comment by jar398** [comment]
I see that this has not yet been handled yet... @mtholder I'm not sure what the proper way to repair this is, or I'd take care of it. I see the branch and I see that it is different from master, does one just merge it into master?

**Comment by mtholder** [comment]
yeah. one would need to:
  1. stop the phylesystem-api to avoid collisions, 
  2. merge the change, 
  3. cd to the mirror
  4. push to GitHub
  5. restart the phylesystem-api. 
  6. make a trivial change to the study to trigger re-indexing by OTI.

I'm not sure when the best time to do this is.

**Comment by mtholder** [comment]
It looks like this study was deleted, so I could not move these changes over (easily, at least). See https://github.com/OpenTreeOfLife/opentree/issues/770

I'll close this issue.

I did write a helper script for locking the repo:

    $ ssh api
    $ source venv/bin/activate
    $ cd repo/phylesystem-1_par/phylesystem-1
    $ python ~/repo/peyotl/extras/lock-phylesystem.py .
    ...
    <Ctrl-D> to release the lock.

(this requires a non-merged branch of peyotl at the moment. you need https://github.com/OpenTreeOfLife/peyotl/commit/a0fa3915c6f37eb6018277ae5b6bfcb6fdbbeb7a).

**Comment by mtholder** [comment]
Instructions placed on: https://github.com/OpenTreeOfLife/opentree/wiki/Manual-merge-of-curation-data
