### ISSUE TITLE
Missing taxa - dinoflagellates

### ISSUE THREAD

**Issue by Katzlab** [OpenTreeOfLife/opentree#77]
The following taxa don't map....  Study 2618:

Biecheleria pseudopalustris
Tyrannodinium berolinense
Palatinus apiculatus

**Comment by kcranston** [comment]
We now have a 'Adding taxa' feature in the curator app, which would be the way to add unmapped taxa.

**Comment by hdliv** [comment]
I saw.  This is a great feature!
