### ISSUE TITLE
Error loading a study, pg_978

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#770]
Error:
{"description": "Study #pg_978 GET failure", "error": 1}

**Comment by jimallman** [comment]
Hm, I don't see a study with this ID in the curation app either:
https://tree.opentreeoflife.org/curator/?match=pg_978

How were you trying to reach this study? From a saved link, maybe?

**Comment by rgazis** [comment]
https://tree.opentreeoflife.org/curator/study/edit/pg_978

I copy and paste the link to the tree:
https://tree.opentreeoflife.org/curator/study/edit/pg_978/?tab=trees&tree=tree5758

**Comment by jimallman** [comment]
I was wondering about the source of these links. They appear to link to a study that has been removed from phylesystem. (checking history now...)

**Comment by jimallman** [comment]
I found [this commit](https://github.com/OpenTreeOfLife/phylesystem-1/commit/e927c2414652aaaf042446a9ee33243053da864c) in the git log. It looks like you (@rgazis) deleted this study earlier today?

**Comment by rgazis** [comment]
? hmmm weird, I have been curating it but I did not delete it. Oh well.....maybe I deleted it by error.
 Thanks for checking! I will upload it again.

Romina

**Comment by jimallman** [comment]
Closing this for now (@rgazis, feel free to re-open if you want to salvage some of your older work)
