### ISSUE TITLE
Taxa creating conflict - Dactylella ambrosia

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/opentree#773]
Hi

Few studies contain this taxa: Dactylella ambrosia, which is stored under two different classes in Index Fungorum (Orbiliomycetes and Sordariomycetes). 

Dactylella ambrosia according to IF belongs to the Orbiliomycetes BUT is also the synonym of Fusarium ambrosium (which belongs to the Nectriaceae, Hypocreales, Sordariomycetes) - also based on IF. This creates conflict in the trees and makes the MCRA go back to Pezizomycotina. 

R

**Comment by jar398** [comment]
What is the correct placement?​ We can fix it in the taxonomy.

**Comment by rgazis** [comment]
The real Dactylella belongs to the Orbiliomycetes BUT Dactylella ambrosia (=Fusarium ambrosium) to the Nectriaceae (Hypocreales, Sordariomycetes). 

No idea how to deal with cases like this one…which must be very common due to our crappy taxonomy.

**Comment by jar398** [comment]
Moved to reference-taxonomy repo issues
