### ISSUE TITLE
Newick, nexus, etc. syntax diagnostics should be available to user

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#776]
Right now all you get for syntax errors in tree uploads is 'server error'.  E.g. if you put ((A,B),C) in the paste box there's no clue that what you've done is left off the semicolon.

**Comment by jimallman** [comment]
Here's what appears in the footer for me when I attempt to import "(a,b)" (note the missing final semicolon). The detailed response appeared when I clicked the "Show details" link:
<img width="1426" alt="screen shot 2015-10-01 at 7 11 04 pm" src="https://cloud.githubusercontent.com/assets/446375/10236127/594bfc3a-6870-11e5-9301-81dddf54816e.png">

**Comment by jar398** [comment]
I'm getting no information in the 'details' for a different example, and mistakenly thought this situation was the same. Will work on isolating the other example
