### ISSUE TITLE
Create default commit message for collections

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#784]
It would improve usability if the commit message for changes to a collections included a default message about adding `treeID` from `studyID` (in cases where the commit involves adding trees). Once the popup appears, the information about treeID & studyID are hidden, so most commit messages will probably be "adding trees" which isn't very helpful.

**Comment by jimallman** [comment]
Done (fix available for review on **devtree**). Here are some details from an email sent following this update:

> I’ve added some code that keeps track of trending collection changes and tries to generate sensible commit messages. Here are some examples, first after a simple operation:

> <img width="622" alt="screen shot 2015-10-07 at 10 55 47 pm" src="https://cloud.githubusercontent.com/assets/446375/10370908/f1e419c6-6dae-11e5-9895-b36a67cb3682.png">

> … and again, after several operations. These messages are of course presentable in git and on GitHub.

> <img width="615" alt="screen shot 2015-10-07 at 10 56 48 pm" src="https://cloud.githubusercontent.com/assets/446375/10370925/00315bf6-6daf-11e5-8217-8e6d134b2f66.png">
