### ISSUE TITLE
When adding trees to a collection, help text in URL box should match treeURL format

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#785]
The URL shown as help text when adding trees to a collection has the form `http://tree.opentreeoflife.org/curator/ot_study/123/tree/456` but the URL for the tree popup has the form `https://tree.opentreeoflife.org/curator/study/view/pg_2826/?tab=trees&tree=tree6573`. The form of the URL in the box should match a URL that the user can find on the site.

**Comment by kcranston** [comment]
Noting that URLs of the second type work.

**Comment by jimallman** [comment]
Fixed, available for review on **devtree**. Closing this issue based on positive email feedback.
