### ISSUE TITLE
Curator "Ingroup clade" display unuseful

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#787]
The "Ingroup clade: Unnamed internal node":
![screenshot from 2015-10-07 14 29 34](https://cloud.githubusercontent.com/assets/808499/10347007/e740ffc0-6cff-11e5-8e7f-79a08aa638c4.png)
in the curator is not useful. Almost no trees will have internal node labels. I say throw it out (it is taking up valuable screen space), or (probably better) put in the field the result of the MRCA test.

**Comment by kcranston** [comment]
The UI needs to indicate that it is important that the ingroup be designated and whether or not this has been done. Agree that the name of that node is not important.

**Comment by jimallman** [comment]
@josephwb, @kcranston: If I understand correctly, we're not so interested in reporting the details (like ingroup node name), but instead reporting a tree's "curation status" and readiness for synthesis. Correct? 

Is this information primarily intended to prompt remedial action by a curator, or as a warning to others?

Here's one approach, combining these less-interesting checks into a single cell:
![screen shot 2016-01-23 at 10 40 00 am](https://cloud.githubusercontent.com/assets/446375/12530993/07ccf178-c1be-11e5-9300-b122b48c174d.png)

Here's the current view, for comparison:
![screen shot 2016-01-23 at 10 29 01 am](https://cloud.githubusercontent.com/assets/446375/12530994/07d14700-c1be-11e5-98f4-52df3df4cb7d.png)
