### ISSUE TITLE
Web2py problem pickling a session (watch for this)

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#804]
@josephwb experienced this when trying to add a study on https://tree.opentreeoflife.org. Here's the ultimate cause, from the traceback in web2py's `errors/`:
```
  File "/home/opentree/web2py/gluon/main.py", line 479, in wsgibase
    session._try_store_in_cookie_or_file(request, response)
  File "/home/opentree/web2py/gluon/globals.py", line 1089, in _try_store_in_cookie_or_file
    return self._try_store_in_file(request, response)
  File "/home/opentree/web2py/gluon/globals.py", line 1096, in _try_store_in_file
    or self._unchanged(response)):
  File "/home/opentree/web2py/gluon/globals.py", line 1041, in _unchanged
    session_pickled = cPickle.dumps(self)
  File "/usr/lib/python2.7/copy_reg.py", line 84, in _reduce_ex
    dict = getstate()
TypeError: \'NoneType\' object is not callable'
```

Normally, this means that a session has un-pickleable elements within it. But it seems to be a known issue that can result from using our combination of apache, mod_wsgi, and multiple "instances" of web2py -- in our case, on ports 80 (HTTP) and 443 (HTTPS). See discussion here:

- https://groups.google.com/forum/#!topic/web2py/CSuT_CknD20
- http://comments.gmane.org/gmane.comp.python.web2py/109600
- https://www.mail-archive.com/web2py@googlegroups.com/msg124892.html

If this problem persists, I gather there are ways of more explicitly "separating" the instances of `WSGIDaemonProcess` in apache config. We can try to glean those from the support threads above.

**Comment by jar398** [comment]
or maybe we could try to ensure that there is only one instance, by setting
up apache redirects from http: to https:.

**Comment by jimallman** [comment]
> maybe we could try to ensure that there is only one instance, by setting
up apache redirects from http: to https:.

Yes, we should probably remove the VirtualHost for HTTP entirely and run production just on HTTPS. i'm tied up today, but will look into this soon.

**Comment by jimallman** [comment]
A few more war stories and possible solutions for the record:

For what it's worth, [some believe this bug appeared in web2py 2.8](https://groups.google.com/d/msg/web2py/UFHn0Xet6QY/QyHcHJoyikUJ). Perhaps a clue for later.

Someone [made changes in config for the cherokee(?) web server](http://markmail.org/message/7ebxyskql73xybbu#query:+page:1+mid:d5fqibqte7xsorui+state:results) that solved this problem. Perhaps there's an analogous change in apache config.

Here's a bit more detail on how to [isolate the wsgi daemon, etc. for different instances of web2py](https://groups.google.com/d/msg/web2py/CSuT_CknD20/zKAWeWrprrEJ). This is probably relevant, since we have two subtly different instances on HTTP vs HTTPS. But of course they share **lots** of state, so this might be tricky. (I'm liking the simpler solution of removing the HTTP instance entirely.)

**mdipierro** points out another possible cause, [upgrades to the server that might break old sessions](https://groups.google.com/d/msg/web2py/DDzdK8skVlo/6I2wsr9Aau4J), but I don't think this applies in our case.

Some have [switched from apache to nginx](http://web2py.narkive.com/ZnBY3sU0/error-when-logging-in#post3) and had better results. This would be a pain, but there it is. Others have switched from uwsgi (which [no longer seems to be favored](https://groups.google.com/d/msg/web2py/CSuT_CknD20/jgJJ76mBA94J) for web2py on linux), but it's not clear what they switched **to**. Sigh.
