### ISSUE TITLE
Suppress 'unsaved changes' dialog unless there are unsaved changes

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#806]
1. edit study
1. save changes
1. navigate away and get warning dialog
1. save again - get footer warning that there are no unsaved changes
1. navigate away and get warning dialog

Compare footer warning and dialog warning:

<img width="1032" alt="screen shot 2015-11-18 at 3 19 34 pm" src="https://cloud.githubusercontent.com/assets/312034/11253172/fde477f6-8e07-11e5-9c5a-ed951a41d7ea.png">

**Comment by jimallman** [comment]
@kcranston, please review.
