### ISSUE TITLE
Prevent duplicate check until some number of characters in DOI / URL box

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#808]
When adding a new study, if you:
* select "I will upload tree data from my computer"
* click in the DOI / URL box
* navigate away from the page (for example, to look up a DOI)

You return to the page to find this:

<img width="726" alt="screen shot 2015-11-19 at 2 45 25 pm" src="https://cloud.githubusercontent.com/assets/312034/11282249/4edfd30c-8ecc-11e5-8e26-98c84eeb38f2.png">

Should be waiting until there is some text there before checking duplicates.

**Comment by jimallman** [comment]
OK, I've updated the logic in both study creation and editing. Whenever a DOI field is "blurred" (user moves focus elsewhere)...

1. If its value is a "naked" DOI (e.g. `"10.9876"`), we normalize it into URL form.
2. If the new value is a valid URL (incl. normalized DOI), we check for duplicates and update the list.
3. If the new value is **not** a valid URL, we clear any stale duplicate list.

This is working now on **devtree**.
