### ISSUE TITLE
Syntax of synthetic tree node references

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#813]
It is proposed to replace the use of neo4j node identifiers in the tree of life API, feedback forms, and browser URLs with tokens that, unlike neo4j node ids, will be resolvable to "similar" nodes in future version of the synthetic tree.

The tokens could take on a variety of syntactic and semantic forms.  For semantics, it is proposed that the token correspond to either one or two OTT ids.  Resolution in any synthetic tree is to the node in that is the MRCA of the nodes designated by the OTT ids (or the node designated by the OTT id, if there is only one). Implementation considerations are not taken up here.

In the following let N range over finite sequences of decimal digits not beginning with 0.

It is proposed that whenever such a token is returned by the API as a string, its content will also be provided in a structured form, so that the user doesn't need to know how to parse it, e.g.
     {"nodeid": &lt;token>, "mrca_of": [N, N]}

It is desirable, although not strictly necessary, that it be possible to place a &lt;token>  in a URL without %-escaping.  If so, many characters, such as +, &, % would be unavailable.

If &lt;token>s do not look like integers, then we will have to institute an incompatible change to the tree_of_life API, which assumes that neo4j node ids are integers.  (taxomachine doesn't use node ids any longer.)

Here are some syntactic options for &lt;token>. For each option there is the case of a single OTT id, followed by the case of two OTT ids, separated by a semicolon. There are infinitely many variants on these.

1. N ; N '.' N   -- e.g. 123.4567
1. N ; N '-' N
1. N ; N '!' N
1. N ; 'mrca(' N ',' N ')'
1. N ; 'mrca-' N '-' N
1. 'ott' N ; 'mrca-ott' N '-ott' N   -- e.g. mrca-ott123-ott4567
1. N ; N   -- tm-lite could maintain the mapping from ids to single or double OTT ids as private knowledge and/or state, and carry it over from one synthetic tree version to the next.  Node ids could be either strings or integers
1. N ; N   -- If it is desirable to maintain compatibility with the current API, which assumes node ids are integers, this can be arranged via any bijection between Z + (Z x Z) to Z. An example of such a bijection is to map a single OTT id n to 2n, and ids (n1,n2) to 2m+1 where m is the low-order-to-high interleaving of the digits of n1 and n2, e.g. (123, 56789) -> 506172839 -> 1012345679. I doubt anyone will want to do this, but it is an option.

**Comment by mtholder** [comment]
just linking to https://github.com/OpenTreeOfLife/treemachine/issues/183.

**Comment by kcranston** [comment]
Assuming we will provide the response in the structured form described above, then I prefer a simple token. No need to repeat the MRCA info in the token, if we pair the token with the MRCA statement:

`{"nodeid": <token>, "mrca_of": [N, N]}`

So, any of 1, 2, 3 or 7. Since we are going to be making a bunch of changes to the API, then it seems ok to drop the requirement that the token be an integer and prefer 1, 2 or 3, which do not require that tm-lite store the mappings between versions of the synthetic tree.

**Comment by jar398** [comment]
Other characters might work for an infix operator, e.g. $ @ : (those should all be safe from %-escaping).  Any letter would work too, e.g. 123m4567.  Vertical bar | is too close to the notation we use for splits. Caret ^ looks too much like the infimum operator from lattice theory, which is the opposite of what we want (mrca = join). I'm ok with 2 or 3 ( - or !)

**Comment by kcranston** [comment]
Barring any further opinion, I say we use 2: `N ; N '-' N`. @bredelings is going to use the same format in output from the synthesis step.

**Comment by bredelings** [comment]
Does #2 imply dropping the ott prefix on ott nodes?

**Comment by kcranston** [comment]
the APIs do not currently return ottIDs with the ott prefix, so no change to the APIs for ottIDs

**Comment by bredelings** [comment]
I suppose monotypic nodes are always going to have OTT Ids, so we don't need to use MRCAs to sppecify them.

**Comment by bredelings** [comment]
I have made a version of the synth tree with nodes labeled mrca-ottX-ottY in the newick.

**Comment by jar398** [comment]
Karen's request was to use option 2, and I concur. So please use that
syntax instead, if you use any at all. That would be N '-' N  where N is a
sequence of digits.

On the other hand, it's not obvious to me that synthesis is the right place
to assign these. I had always assumed the assignment would be done by
treemachine (or tm-lite), perhaps on the fly, but it hadn't even occurred
to me that it would be done in synthesis so I hadn't considered it.  What
is the reason to do this in synthesis?


On Mon, Dec 7, 2015 at 7:49 PM, Benjamin Redelings <notifications@github.com

**Comment by jar398** [comment]
An advantage of putting the id choice logic in tm-lite is that it could
then be used for trees generated by any synthesis method (e.g. old
treemachine trees). The modularity seems better to me.

Also note that in choosing the two ids, non-incertae-sedis-like taxa should
be preferred.

**Comment by mtholder** [comment]
I think that the ("final") decision made on the call was: mrcaott123ott4567
Starting with letter (so that it is an XML-friendly NCName) and lacking punctuation so that it does not require quoting in newick (and is unlikely to find weak spots in client code's newick parsers).

**Comment by bredelings** [comment]
And, I presume, "ott123" for nodes in ott.

**Comment by jar398** [comment]
I presume so as well, for consistency.

Were you thinking of putting the taxon names in the non-mrca node labels, as treemachine does? Or should we leave that up to a postpass (or not do it all)? I'm fine with either approach.

**Comment by bredelings** [comment]
We will leave that to something downstream, either tm-lite or a 
post-processing pass.
