### ISSUE TITLE
Normalize DOI reference when importing from treebase

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#816]
E.g. ot_303 has "^prism:doi": "10.1038/ncomms5473", which comes from treebase, but when it is imported to studyPublication it becomes
"@href": "10.1038/ncomms5473"
which is wrong - all studyPublication values should be URLs, and furthermore if they are DOIs they should start with http://dx.doi.org/.

I think the normalization works well elsewhere, and that this problem only occurs on treebase import.

This affects 58 studies. They will have to be fixed.

**Comment by jimallman** [comment]
Copied this issue into the **peyotl** repository, closing it here.

**Comment by jimallman** [comment]
See https://github.com/OpenTreeOfLife/peyotl/issues/138
