### ISSUE TITLE
Accepting individual mapping should clear selected checkbox?

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#817]
Maybe I'm missing something, but I know that when I was doing some OTU mapping recently, the selected checkbox remained checked after I clicked on the accept-mapping checkmark.  This was annoying because having mapped the OTU, I had no further reason to have it selected. And especially annoying because the OTU gets moved out of sight after acceptance, so you aren't even aware that it is still selected.

I eventually got into the habit of de-selecting OTUs before accepting their mappings, but this seems artificial.

Maybe being selected has no negative consequences, in which case it doesn't matter? I don't know. But is there some good UX reason to keep mapped OTUs selected?

**Comment by jimallman** [comment]
I've copied @jar398's comment above into the earlier duplicate issue #505. Closing this one now.
