### ISSUE TITLE
Advance from draft3 to draft4

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#833]
Under 'latest synthesis release' we currently have https://tree.opentreeoflife.org/about/synthesis-release/v3  i.e. v3 when it should be v4

**Comment by jimallman** [comment]
@jar398, I'm guessing this is due to a lack of statistics for this release. Will investigate further...

**Comment by jimallman** [comment]
See [the manually-constructed file `synthesis.json`](https://github.com/OpenTreeOfLife/opentree/blob/master/webapp/static/statistics/synthesis.json), which will need an entry for v4.

**Comment by jimallman** [comment]
@jar398, I've [added an entry for synth draft 4](https://github.com/OpenTreeOfLife/opentree/blob/988c71d05e6672120d84740c6e0c9a72c5beaead/webapp/static/statistics/synthesis.json#L26-L36), with sensible-looking information (sources noted in inline "comments"). 

Can you confirm this information and add sensible values for `tree_count`, `total_OTU_count`, and `tip_count`? Or remind me how I can determine them myself -- I haven't found any notes on how to do this with confidence.

**Comment by jimallman** [comment]
From #864:
> Updated and added to development branch. Needs to be tested.

I've tested the links (on **devtree**) from the About menu, between synth-release versions, and between the taxonomy and synth-release pages. All are working as expected. Can we close this issue?

**Comment by jar398** [comment]
Yes.
