### ISSUE TITLE
"view this taxon in the latest synthetic tree" when there is no such taxon in the synthetic tree

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#836]
E.g.:

Taxon details
family Mantamonadidae ncbi:1238961 barren, sibling_higher (OTT id 5571518)
View this taxon in the latest synthetic tree

This is a lie, since the taxon is not in the synthetic tree at all.

I think I would prefer to omit this feature entirely, but I know that others disagree. If it's to be kept, then either the label should be changed ("see if this taxon is in the latest synthetic tree") or an API call should be done to check to see if it's really there before offering to go there. I really don't like the latter because it introduces ax extraneous dependency, making the architecture weaker. You should be able to browse a taxonomy even if there is no synthetic tree anywhere, and no particular synthetic tree should be privileged with regard to a taxonomy - "latest" assumes some kind of centralization or essential integration of taxonomy and synthesis.

Consider, for example, the use case of an unrelated project using the open tree taxonomy as its reference taxonomy. A link to "the latest synthetic tree" will be confusing to *their* users who may not know anything about *our* synthetic tree.

If the linkout were given the same presentation and weight as the other linkouts (gbif, ncbi, etc.) that would make more sense. Then open tree's synthetic tree would be unprivileged and there could be multiple linkouts to multiple synthetic trees.

**Comment by jimallman** [comment]
> This is a lie, since the taxon is not in the synthetic tree at all.

Point taken. This is perhaps most embarrassing for the 'Life' node.

**Comment by mtholder** [comment]
The file with this info is http://files.opentreeoflife.org/synthesis/opentree5.0/output/labelled_supertree/broken_taxa.json

**Comment by mtholder** [comment]
sorry. my previous comment should go in a new issue.

**Comment by jar398** [comment]
The originally reported problem was solved a while ago. Closing.
