### ISSUE TITLE
problem adding study through treebase

### ISSUE THREAD

**Issue by hdliv** [OpenTreeOfLife/opentree#843]
<img width="1033" alt="screen shot 2016-01-13 at 11 03 54" src="https://cloud.githubusercontent.com/assets/6361361/12305959/55fbae86-ba05-11e5-9491-439e1ecf4f17.png">

**Comment by jar398** [comment]
Works for me on devtree; fails for me on tree same as it does for Dail.

**Comment by jimallman** [comment]
Thanks for the heads-up! Obviously this is a priority issue. From what I can see, it's actually a [failure in the `POST` method for studies](https://github.com/OpenTreeOfLife/phylesystem-api/blob/42699a6667261d4ebf4551fdf7dd93f303e42501/controllers/default.py#L960) in phylesystem-api, or (more likely?) in the [peyotl version](https://github.com/OpenTreeOfLife/phylesystem-api/blob/42699a6667261d4ebf4551fdf7dd93f303e42501/controllers/default.py#L21) installed on **production** vs. **devtree**.

**Comment by jar398** [comment]
Correct diagnosis. I refreshed the deployed phylesystem-api and now things seem much better. Dail, can you try again now?
I'll try harder to keep the production system in sync with new code in the future.

**Comment by hdliv** [comment]
hi.  now this problem
<img width="1189" alt="screen shot 2016-01-14 at 10 08 25" src="https://cloud.githubusercontent.com/assets/6361361/12327889/d2d5db92-baa6-11e5-92ec-396853ca637b.png">

**Comment by jimallman** [comment]
Thanks @hdliv, i'm chasing some related messages in the logs (`/home/opentree/log/api.log`):
```
[14:48:24] default.py (847):    ERROR: call to OTI check for duplicate DOIs failed
Traceback (most recent call last):
  File "/wd/opentree/web2py/applications/phylesystem/controllers/default.py", line 845, in GET
    duplicate_study_ids = _fetch_duplicate_study_ids(study_DOI, resource_id)
  File "/wd/opentree/web2py/applications/phylesystem/controllers/default.py", line 613, in _fetch_duplicate_study_ids
    duplicate_study_ids = [x['ot:studyId'] for x in response_json['matched_studies']]
KeyError: 'matched_studies'
```

**Comment by jar398** [comment]
taxomachine seems out of date too... will try resetting it as well... hang
on​

**Comment by jar398** [comment]
hmm, I think the taxomachine repo change only had to do with the taxonomy
browser. In any case the production api server seems to be entirely up to
date with master branches now.

**Comment by hdliv** [comment]
great.  let me know when I should try again.

**Comment by jimallman** [comment]
@hdliv, when you re-try, please clear your browser cache. I'm having trouble reproducing the error message you showed above. If you see the same error, please give a bit more detail about the sequence of steps that preceded it. Thanks!

**Comment by jimallman** [comment]
@hdliv, please try again at your earliest convenience. (If it works, please close this issue.)

**Comment by hdliv** [comment]
working now closing out @jimallman @jar398
