### ISSUE TITLE
Grow source tree viewer panel vertically

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#844]
On a 27" display, only about 1/4 of the screen space vertically is used to display the tree. The effect is of a very tiny window into a very large object.  Wondering if there's a way we can get the tree viewer panel to grow to take up available browser window real estate.

**Comment by jimallman** [comment]
I believe this was addressed in the merged PR https://github.com/OpenTreeOfLife/opentree/pull/895.
