### ISSUE TITLE
Duplicate suggestions in OTU mapping (pick one?)

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#860]
See for example this study (or force the same name in any study):
https://devtree.opentreeoflife.org/curator/study/edit/pg_2854/?tab=otu-mapping&match=melicy

Clear all mappings, set context to **All life** and fuzzy mapping = yes. Now look at the suggestions for taxon _Melicytus novae zealandiae_. Three suggested mappings, all pointing (for different reasons) to the same ottid. We should pare these down and present only the most sensible one.

<img width="804" alt="screen shot 2016-01-22 at 12 05 35 pm" src="https://cloud.githubusercontent.com/assets/446375/12517410/826046c4-c100-11e5-80de-08a439919904.png">

**Comment by jimallman** [comment]
On further discussion, the example suggestions all get to the same result (ottid) by different means, so are presented differently. The initial (green) "88% match" seems like the logical choice, vs. any synonyms, if both exist. In these cases, the "synonyms" shown are alternate spellings, which seem intended to do the work of fuzzy matching. Which is odd.

**Comment by kcranston** [comment]
Not sure whether this is a curator bug (i.e. need a different way of handling TNRS results that all have the same OTT ID) or a TNRS bug (should not return multiple results to same OTT ID)

**Comment by jar398** [comment]
Having alternative spellings in OTT is not odd at all. Alternative
spellings are very common in taxonomy because authors make mistakes or
correct mistakes (e.g. changing a masculine species epithet to feminine
when the genus is feminine and a previous author got it wrong; or simply
transcribing incorrectly). Fuzzy matching might handle some of these, but
matching on a misspelling is correct even for non-fuzzy matching if the
misspelling occurs in the literature or in a taxonomic database.

When we correct a spelling in preparing OTT, the old spelling is not
removed, it just turns into a synonym. Another common case is
diacritic-like markings (umlauts and so on), which are removed for OTT,
with the original version left behind as a synonym.

This is going to be very common.

**Comment by kcranston** [comment]
The issue here is that we are presenting three options to the user, but the options have identical taxon name strings and identical OTT IDs. This is really confusing.

**Comment by jar398** [comment]
I understand & agree, I was just responding to Jim's particular comment "the
"synonyms" shown are alternate spellings, which seem intended to do the
work of fuzzy matching. Which is odd." arguing that it is *not* odd at all,
and fuzzy matching would not be a substitute for including the spelling
variants. I would think a TNRS call should return a list of distinct taxa,
i.e. there should not be duplicate taxa in the result set for a single
string. So I vote for TNRS bug.

**Comment by kcranston** [comment]
agree with what @jar398 said about not returning duplicate taxa in TNRS result set

**Comment by jimallman** [comment]
> arguing that it is *not* odd at all

I'm convinced! Also agree that TNRS should only return one suggestion per ottid, assuming the rules for picking which presentation/suggestion to return are fairly straightforward.

**Comment by jar398** [comment]
Not so sure about this now.  It's just a question of rearranging information currently returned by the TNRS.  It's not complicated code, just a matter of collating matches by common taxa. We could write it in Java and put it in the TNRS, which means documenting a new method (or going to v4 with a change in interface), or we could write it in Javascript.  New taxomachine issue: https://github.com/OpenTreeOfLife/taxomachine/issues/144

**Comment by jar398** [comment]
Related: #499 - how do you make synonyms visible if multiple matches to a taxon are collapsed?  (each match could be to a different synonym.)

**Comment by jimallman** [comment]
> how do you make synonyms visible if multiple matches to a taxon are collapsed? (each match could be to a different synonym.)

See the current behavior on **devtree** for a working solution. In the event that TNRS returns multiple matches for a single taxon, the logic for choosing which match to show is dirt-simple (too simple?): 

If any match is exact (`is_approximate_match === false`), show it. (I recognize that this is unlikely, since TNRS would probably return only that match.) 

If all matches are approximate, we simply show the one with the highest score for similarity to the search string, i.e. the curator's proposed label. So the curator will see a single result with a sensible guess based on the taxon's unique name or a synonym (explained in mouse-over text as shown below).

<img width="272" alt="synonym-tooltip" src="https://cloud.githubusercontent.com/assets/446375/20999873/97eb4412-bce5-11e6-8067-afbcaeae29ba.png">
