### ISSUE TITLE
Investigate reason for drop in synthesis tips from input trees

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#865]
We've merged #864, but in computing the stats for v4 I discovered that there are only 40,000 tips from input trees, down from 60,000 in v3.  This is a big drop, so it is important to understand why - was there a mistake in the way tips were counted, or some serious change in taxonomy, or ... ?

**Comment by josephwb** [comment]
The numbers for the PNAS tree:

>Of the 2,339,460 tips in the synthetic tree of life, 37,525 are represented in at least one input phylogeny, with an addi- tional 4,254 nonterminal taxa represented as tips in phylogenetic inputs

were calculated by otcetera (the function seems to have been dropped or renamed/subsumed).

This doesn't agree at all with the v3 numbers currently in the [file](https://github.com/OpenTreeOfLife/opentree/blob/master/webapp/static/statistics/synthesis.json) (~60k), but agree nicely with the v4 tree.

I have no idea where these 60k numbers came from. Perhaps the set of _all_ (i.e. not just unique) input terminals? Although 20k seems to me to be more overlap than was present.

**Comment by josephwb** [comment]
BTW the numbers for v2 were wrong; I've created a [PR](https://github.com/OpenTreeOfLife/opentree/pull/866/files) that corrects the values.

**Comment by jar398** [comment]
I checked the hypothesis that 60,000 included duplicates. For v4 the
numbers are 41029 not counting dups, 45385 counting dups.  That would be
only about 4,000, not enough to account for the 20,000 disparity.

Since 60k was wrong for v2 I'm inclined to think it's wrong for v3 as well,
but I will do the measurement (when I get a minute).

**Comment by jar398** [comment]
The v3 number (as just measured from files provided by Joseph) is 41580.

Current measurements of v2, v3, and v4 are all in the 40ks.  The json file is updated by PR #866, and now at least there's no discrepancy in the json file and the plots look more sensible. The mystery of why we had numbers of 60k before remains but I'm not sure it's worth pursuing further.

**Comment by josephwb** [comment]
Hmm. The PNAS paper (see above) reports 41779, so 199 are unaccounted for. Not sure what is going on there. I'll dig around to see what otcetera command I used to compute those numbers (numbers which I believe @mtholder confirmed).

**Comment by jar398** [comment]
Maybe my jython script is wrong. Here it is
```
import sys, os
from org.opentreeoflife.taxa import Taxonomy
def doit():
    dir = sys.argv[1]
    table = {}
    i = 0
    for filename in os.listdir(dir):
        input = Taxonomy.getNewick(os.path.join(dir, filename))
        for node in input:
            if node.children == None and node.name != None:
                table[node.name] = True
                i += 1
                if len(table) % 1000 == 0:
                    print len(table)
    print len(table), i
doit()```
