### ISSUE TITLE
'Search EOL for' links in properties panel broken

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#886]
They show: Search EOL for 'OTT: 178412' 
which is not right. Should be taxon name.

**Comment by jimallman** [comment]
I just noticed this bug yesterday! It's fixed in the new `adapt-to-new-arguson` branch.

**Comment by jimallman** [comment]
N.B. This should be working as expected on **devtree** and will appear on production along with the conversion of webapps to use v3 "treemachine" APIs.
