### ISSUE TITLE
Offer full-screen view of input trees in curation app?

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#887]
Suggested by @hdliv on Gitter:
> question: in curator when one is in the tree viewer, can there be a way to enlarge the box for better visualisation of the tree?
...
> this would really help. when comparing paper to tree

We might offer a full-screen toggle for this, with a minimal header to return to normal view (as done in the Tree Illustrator).

**Comment by snacktavish** [comment]
+1

**Comment by jimallman** [comment]
I believe this was addressed in the merged PR #895, albeit in a maximized popup, instead of a proper full-screen view.
