### ISSUE TITLE
Make taxon label copy-able in otu mapping

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#890]
When taxa don't map automatically it would be convenient to copy and search them, in a document or online, but it isn't possible to highlight and copy the labels on the otu mapping page.

**Comment by kcranston** [comment]
Adding a +1 to this. Trying to look up additional information about the name string is less accurate and more annoying when you have to re-type the string rather than copy + paste.

**Comment by josephwb** [comment]
I think there is an existing issue for this. You do not have to re-type, but rather click on the edit button and then copy from there.
Not that I like this solution; I too would rather be able to copy straight from the original list.

**Comment by jar398** [comment]
I encountered this one today.​ +1

**Comment by jimallman** [comment]
This is (finally) fixed and working on **devtree**. This comes at the expense of a smaller trigger--just the leftmost cell--for toggling the highlight of the current row. Would it be weird, or helpful, if clicking anywhere in this cell (or just the label) selected all of its text?

**Comment by kcranston** [comment]
Yay, thanks! I think the current behaviour on devtree is good. Selecting part of the name is probably as common as all of the name. Is there a PR for this feature?

**Comment by jimallman** [comment]
Thanks for noticing! I hadn't created a PR, but it's there now (#1114).
