### ISSUE TITLE
Give helpful error message when trying to load "My collections" if no OpenTree profile

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#893]
In cases where a user has no profile page, trying to access "My collections" simply presents the "Loading tree collections list" message without any further progress. We should present a helpful error message instead (and perhaps a link to the full collections list). Related to #882

**Comment by jimallman** [comment]
Alternately, we might simply hide this menu item if there's no detectable project activity (and thus no profile page) for this user. 

Same for the 'My curator profile' menu item; this could disappear, or their empty profile page could include information on how to participate in the project..?

**Comment by jar398** [comment]
I think creating a collection is a legitimate first activity for a
visitor.  If there's a clear way to do that, I guess it doesn't matter if
"My collections" doesn't work beforehand.

**Comment by kcranston** [comment]
Removed the 'My collections' menu item with #905 (which removes the whole menu and just replaces it with a link to the collections page).
