### ISSUE TITLE
Crafting the prompt for DOI or URL in feedback dialog

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#896]
We finished #889 but left one or two things outstanding; here's one (see [gitter](https://gitter.im/OpenTreeOfLife/public?at=56be09360295dc53403dd905)).

The prompt "Provide a supporting reference (DOI or URL)" is good as far as it goes but (1) it's a bit awkward for the case of suggesting new phylogenetic info and (2) I can imagine ways it could be ignored or misinterpreted, in the other cases.  It's a bit too easy for someone to read to quickly and think that's wanted is a URL on the open tree site.

I don't know exactly what prose to suggest instead; it will need some crafting. (I guess mouseover is another option.)

"Provide a supporting {web | external} reference"
"Provide a database reference or published article reference"
...

**Comment by jimallman** [comment]
Please review the latest prompts and suggest revisions (or close this, if satisfied).

**Comment by jar398** [comment]
OK with me. @kcranston ?

**Comment by kcranston** [comment]
Sorry, on phone. What are latest prompts?

**Comment by jimallman** [comment]
For 'Suggest a phylogeny to incorporate':
> Provide a database reference or published article (URL or DOI)

For corrections to synth. tree or names (taxonomy):
> Provide a supporting article or website (URL or DOI)

**Comment by kcranston** [comment]
Fine with me. We could wordsmith these endlessly, so let's make the change
and revisit if users do strange things.

**Comment by jar398** [comment]
I'll merge this if you make a new PR.  (the old one doesn't give me the
option to merge again.)​

**Comment by jimallman** [comment]
The changes mentioned above were already merged to master. I just wanted to close this issue if the original request is satisfied. I'm closing it for now, please feel free to re-open (or create a new one) if users do strange things. :cat:
