### ISSUE TITLE
Convert web-apps to use v3 API calls

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#899]
The current web2py apps are still using a mix of v1 and v2 APIs. It's time to use the newer stuff.

First priority is the "treemachine" (now tm-lite) APIs. Here are the methods used in each app, so we can check off each as it's migrated to v3. Just look for these identifiers in the webapp code (JS and sometimes Python) to see where and how each is used. _Any unused methods should be deleted for clarity!_
## Main webapp (synthetic tree viewer)
- [x] getDraftTreeID_url 
- [x] getSyntheticTree_url 
- [x] getSourceTree_url 
- [x] getDraftSubtree_url 
- [x] getSynthesisSourceList_url 
## Curation webapp
- [x] getDraftTreeID_url 
- [x] getSyntheticTree_url 
- [x] getSourceTree_url 
- [x] getSynthesisSourceList_url 
- [x] getDraftTreeMRCAForNodes_url 
- [x] getDraftTreeSubtreeForNodes_url

**Comment by kcranston** [comment]
findAllStudies is an OTI method, not treemachine / tmlite

**Comment by jimallman** [comment]
Quite right, and so was singlePropertySearchForStudies. Both removed!

**Comment by jimallman** [comment]
Here's my general roadmap for this;
- Redefine TREEMACHINE_BASE_URL and similar (in system-config files) to restore their original meaning, which was simply to set a domain (scheme and hostname) for the different APIs. Update system-config files (in `deployed-systems`) accordingly.
- Move version and path information to the individual method definitions.
- Look for all uses of each method (via the `*_url` JS identifiers above), in both JS and Python.
- Remove any unused methods from the webapp config files and in-page definitions (as JS vars).
- Modify any calls to update to v3 arguments, response formats, error codes, etc.

**Comment by jimallman** [comment]
I'm marking `getDraftTreeID_url` and `getSyntheticTree_url` as complete for the main webapp, even though these methods still use v1 URLs under `/treemachine/v1/`. These "private" methods are only used by the synthetic-tree viewer. @josephwb, please let me know if we plan to move to v3 equivalents for these.

**Comment by josephwb** [comment]
I have no idea how this would be done. There are no "vN" whatsoever in the code. Someone else set this up (redirects?).
I do know that the "v1" services (what I know as GoLS services) use rest, while none of the others do (i.e. "tree_of_life"). 
HTH :bowtie:

**Comment by jimallman** [comment]
@kcranston, I've removed `getSourceTree_url` from both webapps in ca1e8a7. This method has not been used in years, and the URL in our web2py config files doesn't appear in v1 or later APIs. (By implication, it would be used to load a _different_ tree into argus, other than the synthetic tree.)

**Comment by jimallman** [comment]
> There are no "vN" whatsoever in the code. Someone else set this up (redirects?).

For the record, versioning of the neo4j-powered APIs is generally done through apache rewrite rules.

**Comment by jar398** [comment]
This sounds good. It's what peyotl does.

-- apologies for brevity / using handheld gizmo --

On Feb 16, 2016, at 16:21, Jim Allman <notifications@github.com> wrote:

Here's my general roadmap for this;

   - Redefine TREEMACHINE_BASE_URL and similar (in system-config files) to
   restore their original meaning, which was simply to set a domain (scheme
   and hostname) for the different APIs. Update system-config files (in
   deployed-systems) accordingly.
   - Move version and path information to the individual method definitions.
   - Look for all uses of each method (via the *_url JS identifiers above),
   in both JS and Python.
   - Remove any unused methods from the webapp config files and in-page
   definitions (as JS vars).
   - Modify any calls to update to v3 arguments, response formats, error
   codes, etc.

—
Reply to this email directly or view it on GitHub
<https://github.com/OpenTreeOfLife/opentree/issues/899#issuecomment-184879702>
.

**Comment by jar398** [comment]
V3 equiv is tree_of_life/about

-- apologies for brevity / using handheld gizmo --

On Feb 16, 2016, at 23:01, Jim Allman <notifications@github.com> wrote:

I'm marking getDraftTreeID_url and getSyntheticTree_url as complete for the
main webapp, even though these methods still use v1 URLs under
/treemachine/v1/. These "private" methods are only used by the
synthetic-tree viewer. @josephwb <https://github.com/josephwb>, please let
me know if we plan to move to v3 equivalents for these.

—
Reply to this email directly or view it on GitHub
<https://github.com/OpenTreeOfLife/opentree/issues/899#issuecomment-185006395>
.

**Comment by jimallman** [comment]
> V3 equiv is tree_of_life/about

Indeed, switching to this now.

**Comment by jimallman** [comment]
I believe this is complete. All API calls have been v3 for some time, even on production. Any [remaining "old" methods](https://github.com/OpenTreeOfLife/opentree/issues/899#issuecomment-185006395) can be easily updated via apache configuration, if we want to stop serving old API versions.
