### ISSUE TITLE
Creating collections does not trigger creation of profile page?

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#902]
For example, 
https://tree.opentreeoflife.org/curator/profile/bredelings

and
https://github.com/OpenTreeOfLife/collections-1/commit/c1456b801b048a58438ff55184b786bb4af1c175

@bredelings has no other activity (curation or feedback issues).

**Comment by bredelings** [comment]
Also, currently https://tree.opentreeoflife.org/curator/profile/ hangs for me.

**Comment by kcranston** [comment]
I wonder if we should add a "do you want to create a profile page?" option when a logged-in user is trying access their own profile page.

**Comment by jimallman** [comment]
Thanks @bredelings, this would have bitten us eventually. We need to detect and recognize collection activity as project activity in [this general test for an OpenTree profile page](https://github.com/OpenTreeOfLife/opentree/blob/7a6c19386b582572a119087e048e99d463697c4f/curator/controllers/default.py#L197).

**Comment by jimallman** [comment]
Yep, here's [my little reminder to add this when collections were done](https://github.com/OpenTreeOfLife/opentree/blob/7a6c19386b582572a119087e048e99d463697c4f/curator/controllers/default.py#L290). :bowtie:

**Comment by jimallman** [comment]
> I wonder if we should add a "do you want to create a profile page?" option when a logged-in user is trying access their own profile page.

What's your intention here? To "force" the creation of a profile for someone who has no detectable activity? Or to let them keep a low profile (no profile page) regardless?

**Comment by bredelings** [comment]
For me the main issue is discoverability of collections.  I kept on trying 'Manage my collections' (which would hang), but I guess if I had clicked 'Browse all collections', then that would have allowed me to make a new collection.  Currently 'Add new collections' doesn't do anything.

**Comment by kcranston** [comment]
I propose that we remove the Tree collections menu and simply make it a link that opens the collections page. People can get to their collections from their profile page.

**Comment by kcranston** [comment]
This is partially fixed with #905 (which removes the 'My Collections' menu item entirely). Leaving this issue open, because we do want collections activity to trigger profile page creation.

**Comment by jimallman** [comment]
Pull request #913 fixes the original complaint and restores the **My Collections** menu.
