### ISSUE TITLE
url syntax for nodes in trees

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#914]
Could be handy to have a way link to nodes in trees

**Comment by kcranston** [comment]
Need the view from [this internal function](https://github.com/OpenTreeOfLife/opentree/blob/b14c84ca17bd7a4e426c91ac1c2cf1beb26a1f52/curator/static/js/study-editor.js#L3595) but with a change in URL. This gets a +1 from @mtholder and me for two different use cases.

**Comment by jimallman** [comment]
The latest pull request implements this by adding a "share" link to the curation app's node-info popup:

<img width="477" alt="node-menu-grab" src="https://cloud.githubusercontent.com/assets/446375/23640504/2ea9001c-02bc-11e7-8ce0-8d25c50cbc8c.png">

This will open [a node-specific URL](https://devtree.opentreeoflife.org/curator/study/view/tt_103?tab=trees&tree=tree2&node=node1040) in a new window, or of course the user can choose to copy the URL to the clipboard for use in emails, etc.

This is tested and working on **devtree**.
