### ISSUE TITLE
How to confirm rooting in webapp not clear

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/opentree#923]
(moved this over from feedback) A user (and also one time me) saw the error message about "root not confirmed" and went back to the tree, and click and set the root again. I'm not really sure what the better answer is - maybe clicking on that linking to the properties tab? Or the fact that they selected and set a root could be enough?

**Comment by jimallman** [comment]
I'm adding a fix to the latest PR (since it's somewhat related to validation for synthesis). See the commit message above for details. This is available for review on **devtree**, see for example https://devtree.opentreeoflife.org/curator/study/edit/pg_2606?tab=trees&tree=tree6051
