### ISSUE TITLE
"Conflict" is used in two different ways. This is confusing.

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#931]
We have conflict between trees, and conflict between tips of the same tree.  We should not use the word "conflict" for both of these. Personally I do not think of the latter as "conflict" but I do not know what to call it.  Maybe "OTT ids assigned to multiple tips" or "exemplar tip not chosen".  There is no real scientific conflict or inconsistency anywhere in sight, it's just an artifact of the desire to relate tips between trees.

**Comment by jimallman** [comment]
Agreed, this has been bugging me as well. It's also confusing in the client-side code. The good news is (iirc) we don't use "conflict" in either sense in NexSON itself, so changes would be strictly in the UI and code.

Regarding how else to refer to the OTT-mapping conflicts, perhaps something along these lines:
 "duplicate taxon mapping" or

**Comment by kcranston** [comment]
I can tackle this one, and I vote for 'duplicate'.

**Comment by kcranston** [comment]
I am going tackle this today, because I am in airports / airplanes for most of the day and I can get this done without internet / with short attention span. I branched master before we merged #925 , so hopefully there won't be too many conflicts.

**Comment by kcranston** [comment]
This is fixed on branch [`two-types-of-conflict`](https://github.com/OpenTreeOfLife/opentree/tree/two-types-of-conflict) but the merge is a mess. (I branched off master before PR #936).

**Comment by jimallman** [comment]
Maybe something has changed since then? This looks like a reasonable PR to me (whitespace-only changes hidden here): https://github.com/OpenTreeOfLife/opentree/compare/two-types-of-conflict?expand=1&w=1

**Comment by kcranston** [comment]
Yes, looks reasonable now that development has caught up. I am having trouble testing locally, so haven't pushed to devtree. If you can test locally and push to dev, that would be great. Otherwise, I'll pick this up again when I get back next week.

**Comment by jimallman** [comment]
> If you can test locally and push to dev, that would be great.

Done! See the new PR #949 for a diff vs. `master`, and a few minor corrections. But this is already merged to branch `apache-mods-for-v3` (and visible on **devtree**), so it will most likely be merged to master along with PR #898. Closing this now.
