### ISSUE TITLE
Designating exemplars should require login + edit more

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#934]
For example, see [study ot_642](https://tree.opentreeoflife.org/curator/study/view/ot_642/?tab=trees). I can mark the exemplar from this 'view' mode without logging in.

**Comment by jimallman** [comment]
A fix is available for review on **devtree**. Compare this [read-only view](https://devtree.opentreeoflife.org/curator/study/view/tt_103?tab=trees) and [editing view](https://devtree.opentreeoflife.org/curator/study/edit/tt_103?tab=trees).
