### ISSUE TITLE
browser back action from the expanded front page generates an error

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#955]
This is very minor....

For me (using Chrome on ubuntu), loading https://tree.opentreeoflife.org triggers some rewriting of history to make the URL point to the root (currently https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott93302 ). And it looks fine.

But if I hit my browser's back arrow (or backspace hot key equivalent in Chrome), It takes me back to the brief form of the URL and then displays a "Sorry, there was an error checking for taxon status." error message. Hitting refresh fixes that.

As I say, it is not a big deal, but I thought I'd mention it.

**Comment by jimallman** [comment]
Thanks for the heads-up! I'll take care of this.

**Comment by jimallman** [comment]
We now **replace** the default incoming history state in this case, rather than appending the "expanded" URL to the browser history. This fixes the problem (code working now on **devtree**).
