### ISSUE TITLE
should have link from taxonomy release page to taxonomy browser

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#969]
https://tree.opentreeoflife.org/about/taxonomy-version/ott2.9

**Comment by jimallman** [comment]
This would only work for the _current_ taxonomy, right? Is your intention that we'd try to support browsing _all_ versions of the taxonomy?

**Comment by kcranston** [comment]
I just wanted a link to the current version.

**Comment by jimallman** [comment]
Just to be clear: So this link would appear on the page describing the current/latest version, and would be omitted on previous versions. If this is correct, that should be an easy fix.

**Comment by kcranston** [comment]
I suppose so. They way that the page is set up (for example, the title is "Taxonomy version", not "Open Tree Taxonomy"), there isn't an obvious place to put a link to the current version that wouldn't seem strange when you weren't looking at the current version.

**Comment by jimallman** [comment]
Please see PR https://github.com/OpenTreeOfLife/opentree/pull/1018 . I'm hoping the solution shown there will work for both new and old OTT versions.
