### ISSUE TITLE
tree browser layout when presenting

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#970]
@mtholder just gave a demo of the website at NSF, and we ran into two issues related to screen resolution when projecting:

* the properties panel disappears, leaving a huge blank space on the right side of the screen and no way to show the properties / links to external resources
* the menus change to mobile layout (i.e. they disappear from the top bar) which is not ideal

Is there a way to force non-mobile layout, or otherwise prevent this situation?

**Comment by jimallman** [comment]
All of these layout changes are driven from CSS, based on the current window size in pixels. We can certainly reconsider the "threshold" sizes that trigger these changes.

From your description, it sounds like the projector forced a _very_ narrow browser window. Any idea what its resolution was set to?

In any case, you should always be able to toggle the properties panel using the **Show/Hide properties** button in the upper right:

<img width="295" alt="screen shot 2016-04-26 at 11 59 45 am" src="https://cloud.githubusercontent.com/assets/446375/14825139/a73c5780-0ba6-11e6-8a21-a6c2cee47a34.png">

In the narrowest-screen (phone) layout, this is reduced to a small button with an "i" as shown here:

<img width="293" alt="screen shot 2016-04-26 at 12 00 22 pm" src="https://cloud.githubusercontent.com/assets/446375/14825151/b3a94604-0ba6-11e6-8800-5e9b8a5d51fe.png">

**Comment by jimallman** [comment]
And of course, clicking on any node (or edge) in the synth-tree view should show the properties panel for that node+edge.

**Comment by mtholder** [comment]
we'll try to use their projector during one of the breaks to see if we can reproduce it.  It was odd - there were no properties in the panel, just a large empty panel.

**Comment by jimallman** [comment]
> there were no properties in the panel, just a large empty panel

Ah, this symptom points in another direction. After my recent changes to the layout code (how much space is devoted to these panels vs. the underlying tree view), a couple of us reported this "empty" panel, but it was difficult to reproduce. 

This smells like crowding to me; we can probably add some "insurance" by adding negative margins to the panel contents, so they're not squeezed out of view.

**Comment by mtholder** [comment]
just reproduced this (with the help of the projector that first showed the issue).  Firefox looked fine, but Chrome shows the empty panel.

**Comment by jimallman** [comment]
thanks @mtholder! there must be a subtle difference in dimensioning. i'll chase this.

**Comment by kcranston** [comment]
We are also seeing this when resizing the browser window (no projector). On Chrome. See also [convo on gitter](https://gitter.im/OpenTreeOfLife/public?at=5728f27972798bd77be9aa2f)

**Comment by jimallman** [comment]
We finally realized (thanks @kcranston) that this bug only appears in a browser window that is zoomed in or out. It seems to be a rounding error in the resize, just enough to push panels offscreen at some window sizes. I've added tiny negative margins (-1px) to the side panels to compensate for this, working now on **devtree**.
