### ISSUE TITLE
Coerce DOI to URL

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#976]
Tiny low priority thing:

In a feedback issue, if the user gives 'supporting reference' as, say, 10.1098/rspb.2009.1178, it should be coerced to http://dx.doi.org/10.1098/rspb.2009.1178  (using the same logic as DOI entry in study metadata form).

**Comment by jimallman** [comment]
I realize this is low priority, but it was a nice break from some heavier features. It's working now on **devtree**.
