### ISSUE TITLE
"download subtree as Newick string" link generating empty file for some nodes

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/opentree#977]
If I search for "Crotalus" in the "Search for this taxon" box of https://tree.opentreeoflife.org/opentree
 then I get taken to the rattlesnakes in the tree. If I click "download subtree as Newick string" then I get an empty tree file (with no indication of an error). From the chrome dev tools, I learn that it is calling the equivalent of:

    curl 'https://tree.opentreeoflife.org/opentree/default/download_subtree/ottol-id/ott27078/Crotalus' --compressed

(with some cruft removed from the call). That returns an empty document (`curl` exits with no error, so I assume that the status code indicates no problems).

If I click on the info "i" for the same node, and then download the tree again works (I get a tree). That time the call to be backend is the equivalent of:

    curl 'https://tree.opentreeoflife.org/opentree/default/download_subtree/node-id/ott27078/Crotalus' --compressed

(note the change from `ottol-id` to `node-id`). grepping the opentree repo finds several usages of "ottol-id", so I'm not sure which is the culprit here.

**Comment by jimallman** [comment]
Probably some confusion here about whether the 'ottol-id' value is a string or number. I'll chase this down.

**Comment by jimallman** [comment]
> From the chrome dev tools, I learn that it is calling the equivalent of:
> 
> curl 'https://tree.opentreeoflife.org/opentree/default/download_subtree/ottol-id/ott27078/Crotalus' --compressed

Actually, it seems we're correctly capturing a numeric (integer) ottid, so the equivalent curl call is:
```
curl 'http://devtree.opentreeoflife.org/opentree/default/download_subtree/ottol-id/27078/Crotalus' --compressed
```
But I did in fact find a weird typo, an attempt to convert a string ottid to an integer using `Number()` and not `int()`. This is fixed now on **devtree** and available to merge from this PR: https://github.com/OpenTreeOfLife/opentree/pull/979

**Comment by jimallman** [comment]
This fix has been merged to master. Closing now.
