### ISSUE TITLE
"Show All" details option on fron page of curator

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/opentree#986]
A "show all" option for study details on the front page of the curator would be nice, I think. For example, I'd (often) like to see all study detail at a glance, and clicking on each "show details" is tedious.

**Comment by jimallman** [comment]
I've added this feature, working now on **devtree**. See the new filter above the study list:

<img width="859" alt="screen shot 2016-09-15 at 12 18 28 am" src="https://cloud.githubusercontent.com/assets/446375/18538251/0302b878-7ada-11e6-8048-795e3ed81464.png">

As with our other list filters, changing this will modify the current URL (in the browser's address bar). Sharing this URL will also share your choice of compact/full format. This also makes it easy to reload the page, or use the Back button, to stick with your preferred view.

**Comment by josephwb** [comment]
Looks good to me!

I do not recall requesting this, but: what a great idea!

**Comment by josephwb** [comment]
I think this is good. Closing.
