### ISSUE TITLE
Suggest other units when branch-length mode is 'Time'?

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#987]
On the latest **devtree**, I've added a couple of suggested units, so now we offer 'Myr', 'Kyr', and 'Coalescent time units'. Any problem with these? Are there other likely units we should add?

**Comment by josephwb** [comment]
@jimallman Could we add "relative time" or "proportional to time" to the list of possibilities?

**Comment by jimallman** [comment]
> Could we add "relative time" or "proportional to time" to the list of possibiliti

@josephwb I can't see why not. Would this require specifying a time unit?

**Comment by josephwb** [comment]
I guess I meant that _as_ the time unit. Select "Time" for "Branch length mode", and for units set "Relative time". So just add that to the list with "Myr", "Kyr", and "Coalescent time units".

**Comment by jimallman** [comment]
Ah, I think I understand: So the actual branch length values would be ambiguous, but correct in proportion to one another? 0.1, 0.24, 8.77, etc. This should be quite easy to add, if nobody objects.

**Comment by jimallman** [comment]
This is working now on **devtree**. I've used "Relative time" since that's the phrase you repeated above, but this is easy to change if desired.

**Comment by josephwb** [comment]
Looks great.
