### ISSUE TITLE
add new taxa popup too large

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/opentree#992]
At my default browser resolution on my laptop, the popup for adding new taxa is too large to fit on the screen, so the Cancel and Submit buttons are off the bottom of the screen. There is no scroll, so the only way to close the popup is to change the zoom level. 

<img width="1191" alt="screen shot 2016-06-07 at 11 27 23 am" src="https://cloud.githubusercontent.com/assets/312034/15863940/fb8442a4-2ca2-11e6-9c41-78ff90968b98.png">

**Comment by jimallman** [comment]
This is fixed in the latest, no?
